(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Model[Reaction], {
	Description->"Model describing a chemical reaction between a set of reactants to generate a set of reaction products.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {

		(* --- Organizational Information --- *)
		Name -> {
			Format -> Single,
			Class -> String,
			Pattern :> _String,
			Description -> "The name of the model.",
			Category -> "Organizational Information",
			Abstract -> True
		},
		Synonyms -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> _String,
			Description -> "List of possible alternative names this model goes by.",
			Category -> "Organizational Information",
			Abstract -> True
		},
		Deprecated -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> BooleanP,
			Description -> "Indicates that this model is historical and no longer used in the ECL.",
			Category -> "Organizational Information",
			Abstract -> True
		},
		Authors -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[User],
			Description -> "The people who created this model.",
			Category -> "Organizational Information"
		},
		DeveloperObject -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> BooleanP,
			Description -> "Indicates that this object is being used for test purposes only and is not supported by standard SLL features.",
			Category -> "Organizational Information",
			Developer -> True
		},

		(* --- Model Information --- *)
		Reaction -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> ReactionP,
			Description -> "A reaction construct detailing the reactants, products, and reaction rates.",
			Category -> "Model Information"
		},
		ForwardRate -> {
			Format -> Single,
			Class -> Real,
			Pattern :> FirstOrderRateP | SecondOrderRateP,
			Units -> None,
			Description -> "The kinetic rate of the forward reaction.",
			Category -> "Model Information",
			Abstract -> True
		},
		ReverseRate -> {
			Format -> Single,
			Class -> Real,
			Pattern :> FirstOrderRateP | SecondOrderRateP,
			Units -> None,
			Description -> "The kinetic rate of the reverse reaction, if the reaction is reversible.",
			Category -> "Model Information",
			Abstract -> True
		},
		Reactants -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> StructureP,
			Description -> "All of the reactant species consumed by this reaction.",
			Category -> "Model Information",
			Abstract -> True
		},
		ReactantModels -> { (* TODO: Port this to be only molecules. *)
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Molecule, Oligomer][Reactions]|Model[Molecule, cDNA][Reactions]|Model[Molecule, Transcript][Reactions],
			Description -> "Models describing the reactants involved in this chemical reaction.",
			Category -> "Model Information",
			Abstract -> True
		},
		ReactionProducts -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> StructureP,
			Description -> "All of the product species generated by this reaction.",
			Category -> "Model Information",
			Abstract -> True
		},
		ProductModels -> { (* TODO: Port this to be only molecules. *)
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Molecule, Oligomer][Reactions]|Model[Molecule, cDNA][Reactions]|Model[Molecule, Transcript][Reactions],
			Description -> "Models describing the products involved in this chemical reactions.",
			Category -> "Model Information",
			Abstract -> True
		},
		ReactionType -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> RateTypeP,
			Description -> "A general short hand descriptor of this reaction.",
			Category -> "Model Information",
			Abstract -> True
		},

		(* --- Associated Simulations --- *)
		EnthalpySimulations -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Simulation, Enthalpy][ReactionModel],
			Description -> "Binding enthalpy simulations of this reaction model.",
			Category -> "Experiments & Simulations"
		},
		EntropySimulations -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Simulation, Entropy][ReactionModel],
			Description -> "Binding entropy simulations of this reaction model.",
			Category -> "Experiments & Simulations"
		},
		FreeEnergySimulations -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Simulation, FreeEnergy][ReactionModel],
			Description -> "Binding free energy simulations of this reaction model.",
			Category -> "Experiments & Simulations"
		},
		EquilibriumConstantSimulations -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Simulation, EquilibriumConstant][ReactionModel],
			Description -> "Binding equilibrium constant simulations of this reaction model.",
			Category -> "Experiments & Simulations"
		},
		MeltingTemperatureSimulations -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Simulation, MeltingTemperature][ReactionModel],
			Description -> "Melting temperature entropy simulations of this reaction model.",
			Category -> "Experiments & Simulations"
		},

		(* --- Migration Support --- *)
		LegacyID -> {
			Format -> Single,
			Class -> String,
			Pattern :> _String,
			Description -> "The SLL2 ID for this Object, if it was migrated from the old data store.",
			Category -> "Migration Support",
			Developer -> True
		}
	}
}];
