(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[UnitOperation,Dissolution],{
	Description->"A detailed set of parameters that specifies a single dissolution step in a larger protocol for capturing the visual information and taking samples of an oral solid dosage being dissolved in a liquid media at a controlled temperature.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		(* --- General Category --- *)
		Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Instrument,DissolutionApparatus],
				Model[Instrument,DissolutionApparatus]
			],
			Description -> "The instrument stirs the input sample (oral solid dosage) in a temperature-controlled medium, taking aliquots and capturing images of the dissolution vessels at specified time points.",
			Category -> "General",
			Abstract -> True
		},

		(* --- Sample Category --- *)
		SampleLink -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Sample],
				Model[Sample],
				Model[Container],
				Object[Container]
			],
			Description -> "The oral solid dosage samples that are being dissolved in the medium during this unit operation.",
			Category -> "General",
			Migration->SplitField
		},
		SampleString -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> _String,
			Relation -> Null,
			Description -> "The oral solid dosage samples that are being dissolved in the medium during this unit operation.",
			Category -> "General",
			Migration->SplitField
		},
		SampleExpression -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> {_Integer|_String, _String|ObjectP[{Model[Container], Object[Container]}]},
			Relation -> Null,
			Description -> "The oral solid dosage samples that are being dissolved in the medium during this unit operation.",
			Category -> "General",
			Migration->SplitField
		},
		SampleLabel -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> _String,
			Relation -> Null,
			Description -> "The label of the sample that is being used in the experiment, which is used for identification elsewhere in sample preparation.",
			Category -> "General"
		},
		SampleContainerLabel -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> _String,
			Relation -> Null,
			Description -> "The label of the sample container that is being used in the experiment, which is used for identification elsewhere in sample preparation.",
			Category -> "General"
		},
		SampleBuoyancy->{
			Format->Multiple,
			Class->Boolean,
			Pattern:>BooleanP,
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, indicates if the sample is buoyant and will float on the surface of the medium.",
			Category->"General"
		},

		(* --- Medium Category --- *)
		Medium->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[
				Object[Sample],
				Model[Sample]
			],
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the buffer used to dissolve oral solid dosage. This is often chosen to mimic a biologically relevant environment.",
			Category->"Medium",
			Migration->SplitField
		},
		MediumVolume->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Milliliter],
			Units->Milliliter,
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the volume of the medium used to dissolve the oral solid dosage and from which the aliquots are taken throughout the experiment.",
			Category->"Medium"
		},
		MediumTemperature->{
			Format->Multiple,
			Class->Real,
			Units->Celsius,
			Pattern:>GreaterEqualP[0 Kelvin],
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the nominal temperature of the media the instrument seeks to maintain for each vessel by using the heating jacket around the dissolution vessel. The recording of the temperature of the media during the experiment can be found in the Temperature field in the Data objects generated by the protocol.",
			Category->"Medium"
		},

		(* --- Mixing Category --- *)
		Agitator->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item,Agitator],Object[Item,Agitator]],
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the implement used to transfer the rotational energy from the shaft to the dissolution medium.",
			Category->"Mixing"
		},
		MixingStrategy->{
			Format->Single,
			Class->Expression,
			Pattern:>DissolutionStrategyP,
			Description->"The type of the mixing implement used to transfer the rotational energy from the motor to the dissolution media to facilitate the proper mixing.",
			Category->"Mixing"
		},
		AgitatorMaterial->{
			Format->Single,
			Class->Expression,
			Pattern:>ShaftMaterialP,
			Description->"The material of the shaft used to transfer the rotational energy from the motor to the dissolution media to facilitate the proper mixing.",
			Category->"Mixing"
		},
		MixRate->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterP[0 * RPM],
			Units->RPM,
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the frequency at which the shaft is rotated during the experiment.",
			Category->"Mixing"
		},
		MixTime->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			IndexMatching->SampleLink,
			Pattern:>GreaterEqualP[0 Minute],
			Description->"For each member of SampleLink, the duration of time the oral solid dosage is mixed during which the sampling occurs at the specified SamplingTime intervals. After the initial mixing period is completed, the optional InfinityMixing is performed at a higher rotation rate to achieve the final saturation point.",
			Category->"Mixing"
		},
		Sinker->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Container,Sinker],Model[Container,Sinker]],
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the weighted enclosure used to keep the oral solid dosage below the surface of the media during the experiment to facilitate proper mixing.",
			Category->"Mixing"
		},
		SinkerType->{
			Format->Multiple,
			Class->Expression,
			Pattern:>SinkerTypeP,
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the type of sinker used to keep the oral solid dosage below the surface of the media during the experiment to facilitate proper mixing.",
			Category->"Mixing"
		},

		(* --- InfinityMixing Category --- *)
		InfinityMix->{
			Format->Multiple,
			Class->Boolean,
			Pattern:>BooleanP,
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, indicates if additional mixing at higher rotational speed is performed at the end of the MixTime. The Infinity Mixing period is used to achieve the final saturation point.",
			Category->"Infinity Mixing"
		},
		InfinityMixRate->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterP[0 * RPM],
			Units->RPM,
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the frequency of rotation used by the dissolution instrument at the end of the experiment to achieve final dissolution condition. This is typically set to a higher value than the MixRate to achieve the final saturation point.",
			Category->"Infinity Mixing"
		},
		InfinityMixTime->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			Pattern:>GreaterEqualP[0 Minute],
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the duration of time for which the oral solid dosage will be mixed at InfinityMixRate after MixTime to achieve the final saturation point.",
			Category->"Infinity Mixing"
		},

		(* --- Sampling Category --- *)
		Sampling->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if samples of the dissolution media should be taken during the experiment. These samples are commonly used to determine the amount of the sample that was dissolved in the medium at a given time point.",
			Category->"Sampling"
		},
		NumberOfAliquots->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"Indicates the number of samples taken from the dissolution medium during the experiment.",
			Category->"Sampling"
		},
		SamplingTime->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			Pattern:>GreaterEqualP[0 Minute],
			Description->"The list of the time points at which aliquots of the dissolution medium are taken.",
			Category->"Sampling"
		},
		SamplingVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the aliquot taken from the dissolution media at each SamplingTime time point.",
			Category->"Sampling"
		},
		SampleOutStorageCondition->{
			Format->Single,
			Class -> Expression,
			Pattern :> Alternatives[LinkP[Model[StorageCondition]], SampleStorageTypeP, Desiccated, VacuumDesiccated, RefrigeratorDesiccated, Disposal],
			Description->"The non-default condition under which the created aliquotes are stored after the protocol is completed.",
			Category->"Sampling"
		},
		ReplaceMedium->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the liquid removed from the dissolution vessel during sampling is replaced with a new medium.",
			Category->"Sampling"
		},
		ReplacementMedium->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[
				Object[Sample],
				Model[Sample]
			],
			Description->"The medium used to replace the liquid from the dissolution vessel removed for sampling each time an aliquot is taken.",
			Category->"Sampling"
		},
		SamplingPrimeVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the liquid from the dissolution vessel used to flush the sampling lines in the autosampler at each sampling time point prior to dispensing SamplesOut.",
			Category->"Sampling"
		},
		RecycleSamplingMedium->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the buffer removed for sample flushing is returned from the lines back to the dissolution vessel. Refer to the instrument diagram of the liquid flow path during the instrument operation for more details.",
			Category->"Sampling"
		},
		NumberOfSamplingWashCycles->{
			Format->Multiple,
			Class->Integer,
			Pattern:>GreaterP[0,1],
			Description->"Indicate the number of times the system wash cycle is performed between each sampling timepoint.",
			Category->"Sampling"
		},
		CollectionFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed at which the medium is aspirated during the experiment.",
			Category->"Sampling"
		},
		SamplingFlushVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the flush medium used to flush the sampling lines in the autosampler at each sampling time point prior to dispensing SamplesOut.",
			Category->"Sampling"
		},
		DispenseFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed at which the medium is dispensed during the experiment.",
			Category->"Sampling"
		},
		VesselReturnFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed at which the medium is returned to the dissolution vessel.",
			Category->"Sampling"
		},
		NumberOfSamplingFlushes->{
			Format->Multiple,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"Indicate the number of times the sampling lines should be cleaned prior to sampling.",
			Category->"Sampling"
		},
		ContainersOut->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Container,Vessel],Model[Container,Vessel]],
			Description->"The vessels used to store the aliquots of the dissolution medium taken during the experiment.",
			Category->"Sampling"
		},

		(* --- Sampling Filtration Category --- *)
		NumberOfFilterUses->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[1,1],
			Description->"The number of times the AutosamplerFilter is used before being replaced with a new one.",
			Category->"Sampling Filtration"
		},
		FilterSamples->{
			Format->Multiple,
			Class->Expression,
			Pattern:>DissolutionFiltrationTypeP,
			Description->"Indicates the types of filtration applied to the dissolution media samples during transfer to ContainerOut. Accepts a list of filtration types that are applied in sequence. CannulaTipFiltration: filters during sample transfer through cannula tip. InLineFiltration: filters immediately after removal from vessel before entering autosampler. AutosamplerFiltration: filters before dispensing into ContainerOut (changed between aliquots). Multiple types can be specified as a list (e.g., {InLineFiltration, AutosamplerFiltration}).",
			Category->"Sampling Filtration"
		},
		AutosamplerFilter->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,Filter],Model[Item,Filter]],
			Description->"The filter disks used to filter the aliquots of samples that are taken from the dissolution medium at the specified time points before the sample is dispensed into the ContainerOut. This filter is applied after the InLineFilter and is optionally changed between each aliquot.",
			Category->"Sampling Filtration"
		},
		AutosamplerFilterMaterial->{
			Format->Single,
			Class->Expression,
			Pattern:>FilterMaterialP,
			Description->"The material of the filter used to filter the aliquots of samples that are taken from the dissolution medium at the specified time points before the sample is dispensed into the ContainerOut. This filter is applied after the InLineFilter and is optionally changed between each aliquot.",
			Category->"Sampling Filtration"
		},
		AutosamplerFilterPoreSize->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Micron],
			Units->Micron,
			Description->"The pore size of the filter used to filter the aliquots of samples that are taken from the dissolution medium at the specified time points before the sample is dispensed into the ContainerOut. This filter is applied after the InLineFilter and is optionally changed between each aliquot.",
			Category->"Sampling Filtration"
		},
		InLineFilter->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,Filter],Model[Item,Filter]],
			IndexMatching->SampleLink,
			Description->"For each member of SampleLink, the filter that is used to remove impurities from the samples right after they are removed from the dissolution vessel and prior to the liquid entering the autosampler for optional secondary filtration.",
			Category->"Sampling Filtration"
		},
		InLineFilterMaterial->{
			Format->Single,
			Class->Expression,
			Pattern:>FilterMaterialP,
			Description->"The material of the filter used to filter the aliquots of samples that are taken from the dissolution medium at the specified time points before the sample is dispensed into the ContainerOut. This filter is applied after the InLineFilter and is optionally changed between each aliquot.",
			Category->"Sampling Filtration"
		},
		InLineFilterPoreSize->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Micron],
			Units->Micron,
			Description->"The pore size of the filter used to filter the aliquots of samples that are taken from the dissolution medium at the specified time points before the sample is dispensed into the ContainerOut. This filter is applied after the InLineFilter and is optionally changed between each aliquot.",
			Category->"Sampling Filtration"
		},
		CannulaTipFilter->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,Filter],Model[Item,Filter]],
			Description->"The filters attached to cannula tips used to filter samples during transfer from the dissolution vessel to the collection container.",
			Category->"Sampling Filtration"
		},
		CannulaTipFilterMaterial->{
			Format->Single,
			Class->Expression,
			Pattern:>FilterMembraneMaterialP,
			Description->"The material of the cannula tip filters used during sample transfer.",
			Category->"Sampling Filtration"
		},
		CannulaTipFilterPoreSize->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Micron],
			Units->Micron,
			Description->"The pore size of the cannula tip filters used during sample transfer.",
			Category->"Sampling Filtration"
		},

		(* --- Degas Category --- *)
		Degas->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the dissolution medium should be degassed by bubbling Helium prior to the experiment.",
			Category->"Degas"
		},
		DegasTime->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Minute],
			Units->Minute,
			Description->"The duration of time the dissolution medium is degassed by bubbling Helium prior to the experiment.",
			Category->"Degas"
		},

		(* --- Experimental Results Category --- *)
		MeasuredMediumTemperatures->{
			Format->Multiple,
			Class->Distribution,
			Pattern:>DistributionP[Celsius],
			Units->Celsius,
			Description->"The observed temperature of the dissolution medium measured during the experiment.",
			Category->"Experimental Results"
		},
		MeasuredMediumTemperatureData->{
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data, Temperature],
			Description -> "For each member of MeasuredMediumTemperatures, the recorded temperature of the dissolution medium during the experiment, as measured by the temperature probe.",
			IndexMatching->MeasuredMediumTemperatures,
			Category -> "Experimental Results"
		},
		SamplingDate->{
			Format->Multiple,
			Class->Date,
			Pattern:>_?DateObjectQ,
			Description->"The date at which each aliquot was taken from the dissolution medium.",
			Category->"Experimental Results"
		},
		ImageData->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[Data, Appearance],
			Description->"Images captured of the dissolution vessels at specified time points during the experiment.",
			Category->"Experimental Results"
		}
	}
}];