(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Software, ManifoldKernelCommand], {
	Description -> "A command to be run on a manifold kernel.",
	CreatePrivileges -> None,
	Cache -> Download,
	Fields -> {
		ManifoldKernel -> {
			Format -> Single,
			Class -> Link,
			Pattern :> ObjectP[Object[Software, ManifoldKernel]],
			Relation -> Object[Software, ManifoldKernel][Commands],
			Description -> "The kernel this command runs on.",
			Category -> "Organizational Information"
		},
		Command -> {
			Format -> Single,
			Class -> String,
			Pattern :> _String,
			Description -> "The mathematica command to run via ToExpression.",
			Category -> "Organizational Information"
		},
		DateStarted -> {
			Format -> Single,
			Class -> Date,
			Pattern :> _DateObject,
			Description -> "The date this command started executing.",
			Category -> "Organizational Information"
		},
		DateCompleted -> {
			Format -> Single,
			Class -> Date,
			Pattern :> _DateObject,
			Description -> "The date this command completed executing.",
			Category -> "Organizational Information"
		},
		Status -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> Pending | Running | Completed | TimedOut,
			Description -> "Whether the command is in the processing of running or not.",
			Category -> "Organizational Information"
		},
		ZDriveFilePaths -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> _String,
			Description -> "A list of all Z-drive file paths needed by this command.",
			Category -> "Organizational Information"
		},
		Result -> {
			Format -> Single,
			Class -> String,
			Pattern :> _String,
			Description -> "The result of the command, if it is small enough to be stored as a string.  If not, it will be stored in ResultCloudFile.",
			Category -> "Organizational Information"
		},
		ResultCloudFile -> {
			Format -> Single,
			Class -> Link,
			Pattern :> ObjectP[Object[EmeraldCloudFile]],
			Relation -> Object[EmeraldCloudFile],
			Description -> "The result of the command, if it is too large to be stored as a string.  If not, it will be stored in Result.",
			Category -> "Organizational Information"
		},
		Messages -> {
				Format -> Multiple,
				Class -> {String, String, String},
				Pattern :> {_String, _String, _String},
				Description -> "The messages generated by the command.",
				Category -> "Organizational Information",
				Headers -> {"Name", "Text", "Expression"}
		},
		LoadedVolumes -> {
			Format -> Single,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates whether the files have been loaded into the manifold job.",
			Category -> "Organizational Information"
		}
	}
}];
