(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Software, DocumentationJob, HTMLJob], {
	Description->"A single run of a documentation job that builds HTML.",
	CreatePrivileges->None,
	Cache->Download,
	Fields -> {
		GitHubURL -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> _String,
			Description -> "The URL(s) of the pull request generated by this job.",
			Category -> "Organizational Information"
		},
		PreviewURL -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> _String,
			Description -> "The URL(s) of a preview of the built documentation.",
			Category -> "Organizational Information"
		},
		LoadSLL -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> BooleanP,
			Description -> "If True, the webdocs builder will load SLL prior to running the docs building script.",
			Category -> "Organizational Information"
		}
  }
}];
