(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Model[Part, LaserOpticModule], {
	Description->"Model information for a laser-based optic module used in a flow cytometer instrument.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {
		
		ChannelName -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> FlowCytometryFluorescenceChannelP,
			Description -> "The name of the fluorescence channel that this Laser Optic Module defines.",
			Category -> "Organizational Information",
			Abstract -> True
		},
		SchematicFile-> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[EmeraldCloudFile],
			Description -> "Image file showing the layout of the optic module, including optical path, mirrors and filters.",
			Category -> "Optical Information"
		},
		Laser -> {
			Format -> Single,
			Class -> Real,
			Pattern :> FlowCytometryLaserWavelengthP,
			Units -> Meter Nano,
			Description -> "Wavelength of excitation light generated by the laser light source.",
			Category -> "Optical Information"
		},
		EmissionFilterWavelength -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0*Meter*Nano, 1*Nano*Meter],
			Units -> Meter Nano,
			Description -> "Wavelength of emitted light after passing through emission filter on the way to the detector.",
			Category -> "Optical Information"
		},
		EmissionFilterBandwidth -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0*Nano*Meter, 1*Nano*Meter],
			Units -> Meter Nano,
			Description -> "The range of wavelengths, centered around the emission filter wavelength, that the filter will allow to pass through.",
			Category -> "Optical Information"
		}
	}
}];
