(* ::Package:: *)

DefineObjectType[Model[Part, EluentGenerator], {
	Description->"Model information for a cartridge that automatically generates Buffer in the flow path for Ion Chromatography experiments.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{

		Eluent->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Model[Sample],
			Description->"The specific type of chemical solvent the cartridge generates.",
			Category->"Physical Properties",
			Abstract->True
		},
		AnalysisChannels->{
			Format->Single,
			Class->Expression,
			Pattern:>AnalysisChannelP,
			Description->"The analysis channel compatible with the type of Buffer generated by the cartridge. For example, an Buffer generator with strong base is typically used for anion channel.",
			Category->"Physical Properties",
			Abstract->True
		},
		IonChromatographySystem->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Description->"The Ion Chromatography instrument that is compatible with this model of the Buffer generator.",
			Relation->Model[Instrument, IonChromatography][IntegratedEluentGenerator],
			Category->"Physical Properties",
			Abstract->True
		},
		MinConcentration->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0*Milli*Mole/Liter],
			Units->Milli Mole/(Liter),
			Description->"The lowest concentration of the specific Buffer this cartridge can generate.",
			Category->"Physical Properties"
		},
		MaxConcentration->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0*Milli Mole/(Liter)],
			Units->Milli Mole/(Liter),
			Description->"The highest concentration of the specific Buffer this cartridge can generate.",
			Category -> "Physical Properties"
		},
		MinFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0*Milli Liter/Minute],
			Units->Milli Liter/Minute,
			Description->"The lowest flow rate compatible with the Buffer generator.",
			Category->"Physical Properties"
		},
		MaxFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0*Milli Liter/Minute],
			Units->Milli Liter/Minute,
			Description->"The lowest flow rate compatible with the Buffer generator.",
			Category->"Physical Properties"
		},
		MaxPressure->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0*PSI],
			Units->PSI,
			Description->"The highest pressure level that can be applied to the cartridge.",
			Category->"Physical Properties"
		}
	}
}];
