(* ::Package:: *)

DefineObjectType[Model[Part, Suppressor], {
    Description->"Model information on the suppressor, that is used to reduce the background signal from the buffer in Ion Chromatography instrument.",
    CreatePrivileges->None,
    Cache->Session,
    Fields->{

        AnalysisChannels->{
            Format->Single,
            Class->Expression,
            Pattern:>AnalysisChannelP,
            Description->"The analysis channel compatible with the type of Buffer generated by the cartridge. For example, an Buffer generator with strong base is typically used for anion channel.",
            Category->"Physical Properties",
            Abstract->True
        },
        IonChromatographySystem->{
            Format->Multiple,
            Class->Link,
            Pattern:>_Link,
            Description->"The Ion Chromatography instrument that is compatible with this model of the Buffer generator.",
            Relation->Model[Instrument, IonChromatography][AnionSuppressor]|Model[Instrument, IonChromatography][CationSuppressor],
            Category->"Physical Properties",
            Abstract->True
        },
        FactoryRecommendedVoltage->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Volt],
            Units->Volt,
            Description->"The voltage determined during factory testing to cover the full range of possible operating conditions of the suppressor.",
            Category->"Physical Properties",
            Abstract->True
        },
        MinCurrent->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Milli*Ampere],
            Units->Milliampere,
            Description->"The lowest electrical current compatible with the suppressor.",
            Category->"Physical Properties"
        },
        MaxCurrent->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Milli*Ampere],
            Units->Milliampere,
            Description->"The highest electrical current compatible with the suppressor without overheating.",
            Category -> "Physical Properties"
        },
        MinVoltage->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Volt],
            Units->Volt,
            Description->"The lowest electrical potential compatible with the suppressor.",
            Category->"Physical Properties"
        },
        MaxVoltage->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Volt],
            Units->Volt,
            Description->"The highest electrical potential compatible with the suppressor.",
            Category->"Physical Properties"
        },
        MinFlowRate->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Milli Liter/Minute],
            Units->Milli Liter/Minute,
            Description->"The lowest flow rate compatible with the suppressor.",
            Category->"Physical Properties"
        },
        MaxFlowRate->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterP[0*Milli Liter/Minute],
            Units->Milli Liter/Minute,
            Description->"The lowest flow rate compatible with the Buffer generator.",
            Category->"Physical Properties"
        },
        MaxPressure->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*PSI],
            Units->PSI,
            Description->"The highest pressure level that can be applied to the cartridge.",
            Category->"Physical Properties"
        },
        SuppressorSpecificFactor->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0],
            Description->"Factory determined factor for calculating optimal suppressor current. This factor varies with the different type of suppressors.",
            Category->"Physical Properties"
        }
    }
}];
