(* ::Package:: *)

DefineObjectType[Object[Part, Suppressor], {
    Description->"A part in Ion Chromatography instrument that reduces the conductivity signal contributed by the buffer.",
    CreatePrivileges->None,
    Cache->Session,
    Fields->{

        AnalysisChannels->{
            Format->Single,
            Class->Expression,
            Pattern:>AnalysisChannelP,
            Description->"The analysis channel compatible with the type of Buffer generated by the cartridge. For example, an Buffer generator with strong base is typically used for anion channel.",
            Category->"Physical Properties",
            Abstract->True
        },
        Instrument->{
            Format->Multiple,
            Class->Link,
            Pattern:>_Link,
            Description->"The Ion Chromatography instrument that is compatible with this model of the Buffer generator.",
            Relation->Object[Instrument, IonChromatography][AnionSuppressor]|Object[Instrument, IonChromatography][CationSuppressor],
            Category->"Physical Properties",
            Abstract->True
        },
        FactoryRecommendedVoltage->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Volt],
            Units->Volt,
            Description->"The voltage determined during factory testing to cover the full range of possible operating conditions of the suppressor.",
            Category->"Physical Properties",
            Abstract->True
        },
        MinCurrent->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Milli*Ampere],
            Units->Milliampere,
            Description->"The lowest electrical current compatible with the suppressor.",
            Category->"Physical Properties"
        },
        MaxCurrent->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Milli*Ampere],
            Units->Milliampere,
            Description->"The highest electrical current compatible with the suppressor without overheating.",
            Category->"Physical Properties"
        },
        MinVoltage->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Volt],
            Units->Volt,
            Description->"The lowest electrical potential compatible with the suppressor.",
            Category->"Physical Properties"
        },
        MaxVoltage->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Volt],
            Units->Volt,
            Description->"The highest electrical potential compatible with the suppressor.",
            Category->"Physical Properties"
        },
        MinFlowRate->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*Milli Liter/Minute],
            Units->Milli Liter/Minute,
            Description->"The lowest flow rate compatible with the Buffer generator.",
            Category->"Physical Properties"
        },
        MaxFlowRate->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterP[0*Milli Liter/Minute],
            Units->Milli Liter/Minute,
            Description->"The lowest flow rate compatible with the Buffer generator.",
            Category->"Physical Properties"
        },
        MaxPressure->{
            Format->Single,
            Class->Real,
            Pattern:>GreaterEqualP[0*PSI],
            Units->PSI,
            Description->"The highest pressure level that can be applied to the cartridge.",
            Category->"Physical Properties"
        }
    }
}];
