(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2024 Emerald Cloud Lab, Inc.*)


(* ::Subsection:: *)
(*Object[Data, QuantifyCells]*)



DefineObjectType[Object[Data, QuantifyCells], {
	Description -> "Measurements of the cell concentration in the input cell samples with various methods. The methods that are currently supported include measuring the absorbance at 600 nm (OD600) of the 'Samples' with AbsorbanceIntensity measurement and measuring the turbidity of the 'Samples' with Nephelometry measurement.",
	CreatePrivileges -> None,
	Cache -> Session,
	Fields -> {
		(* --- General --- *)
		Methods -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> CellQuantificationMethodP,
			Description -> "The experimental instrumentation used to measure the cell concentration in the input cell samples. Instrumentation options include: 1) Absorbance, where the absorbance (at the provided Wavelength) of the cell sample is measured using a spectrophotometer or plate reader and then converts to QuantificationUnit using the AbsorbanceStandardCurve or AbsorbanceStandardCoefficient; 2) Nephelometry, where the scattered light attenuation of the cell sample at 653 nm is measured using a nephelometer and then converts to QuantificationUnit using the NephelometryStandardCurve or NephelometryStandardCoefficient. Note that the order of methods dictates the order of operations when the protocol is executed in the lab.",
			Category -> "General",
			Abstract -> True
		},
		Instruments -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				(* AbsorbanceIntensity *)
				Model[Instrument, PlateReader], Object[Instrument, PlateReader],
				Model[Instrument, Spectrophotometer], Object[Instrument, Spectrophotometer],
				(* Nephelometry *)
				Model[Instrument, Nephelometer], Object[Instrument, Nephelometer]
			],
			Description -> "For each member of Methods, the instrument used to measure the absorbance (at the provided Wavelength) or nephelometry (scattered light attenuation) for the input cell samples.",
			Category -> "General",
			IndexMatching -> Methods
		},
		(* --- Data --- *)
		Absorbances -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> UnitsP[AbsorbanceUnit],
			Units -> AbsorbanceUnit,
			Description -> "For each member of AbsorbanceData, the absorbance measured at the wavelength, with the blank absorbance subtracted (if available).",
			Category -> "Experimental Results",
			IndexMatching -> AbsorbanceData
		},
		AbsorbanceData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data, AbsorbanceIntensity],
			Description -> "Any absorbance data that was generated by the input cell samples or the aliquots from the input cell samples.",
			Category -> "Experimental Results"
		},
		Turbidities -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> UnitsP[0 * RelativeNephelometricUnit],
			Units -> RelativeNephelometricUnit,
			Description -> "For each member of NephelometryData, the turbidity as measured by the nephelometer, with the blank or empty turbidity measurement subtracted (if available).",
			IndexMatching -> NephelometryData,
			Category -> "Experimental Results"
		},
		NephelometryData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data, Nephelometry],
			Description -> "Any nephelometry data that was generated by the input cell samples or the aliquots from the input cell samples.",
			Category -> "Experimental Results"
		},
		(* --- Analysis & Reports --- *)
		QuantificationUnit -> {
			Format -> Single,
			Class -> VariableUnit,
			Pattern :> UnitsP[EmeraldCell / Milliliter] | UnitsP[OD600],
			Units -> None,
			Description -> "The preferred unit of cell concentration to update the composition of the input sample after the quantification measurement. If the specified unit cannot be directly measured with the specified quantification Methods, StandardCurve or StandardCoefficient will be used to convert the raw experimental result. If the StandardCurve or StandardCoefficient information is neither provided nor available from the input samples' cell compositions, the unit that is directly measured with the specified quantification Methods will be used to update the composition. The final concentration used to update the composition is the mean value of any raw experimental results and any converted values from the raw experimental result in the unit of QuantificationUnit. If the QuantificationUnit is neither available from direct measurements nor convertible from any quantification measurements, the composition is updated with the directly measurable units from the quantification measurements specified in Methods. The directly measurable units for {Absorbance, Nephelometry} are {OD600, RelativeNephelometricUnit} respectively.",
			Category -> "Analysis & Reports"
		},
		AbsorbanceStandardCurve -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Analysis, StandardCurve],
			Description -> "The standard curve used to convert between the raw experimental result in the unit of {OD600, AbsorbanceUnit} to the specified QuantificationUnit.",
			Category -> "Analysis & Reports"
		},
		AbsorbanceStandardCoefficient -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0],
			Description -> "The factor used to multiply the raw experimental result in the unit of {OD600, AbsorbanceUnit} to the specified QuantificationUnit assuming linear relationship.",
			Category -> "Analysis & Reports"
		},
		NephelometryStandardCurve -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Analysis, StandardCurve],
			Description -> "The standard curve used to convert between the raw experimental result in the unit of {RelativeNephelometricUnit} to the specified QuantificationUnit.",
			Category -> "Analysis & Reports"
		},
		NephelometryStandardCoefficient -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0],
			Description -> "The factor used to multiply the raw experimental result in the unit of {RelativeNephelometricUnit} to the specified QuantificationUnit assuming linear relationship.",
			Category -> "Analysis & Reports"
		},
		Concentration -> {
			Format -> Single,
			Class -> VariableUnit,
			Pattern :> UnitsP[EmeraldCell / Milliliter] | UnitsP[OD600],
			Units -> None,
			Description -> "The concentration of the sample in the source sample, i.e. the original un-diluted sample, calculated by the raw experimental result and any applicable Absorbance/NephelometryStandardCurve, Absorbance/NephelometryStandardCoefficient.",
			Category -> "Analysis & Reports",
			Abstract -> True
		}
	}
}];


