(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Data, RamanSpectroscopy], {
  Description -> "The data generated from a Raman Spectroscopy experiment showing the Raman scattering spectrum and optical images as a function of position within each sample and averaged over all measured positions.",
  CreatePrivileges -> None,
  Cache -> Session,
  Fields -> {
    RamanSpectra -> {
      Format -> Multiple,
      Class -> QuantityArray,
      Pattern :> QuantityCoordinatesP[{1/Centimeter,ArbitraryUnit}],
      Units -> {1/Centimeter, ArbitraryUnit},
      Description -> "A list of the baseline corrected Raman spectra corresponding to measurements performed at a point of the SamplingPattern, in the form: {\"Wavenumber\", \"Intensity\"}.",
      Category -> "Experimental Results"
    },
    AverageRamanSpectrum -> {
      Format -> Single,
      Class -> QuantityArray,
      Pattern :> QuantityCoordinatesP[{1/Centimeter,ArbitraryUnit}],
      Units -> {1/Centimeter, ArbitraryUnit},
      Description -> "The Raman spectrum generated by averaging over all elements in RamanSpectra, in the form: {\"Wavenumber\", \"Intensity\"}.",
      Category -> "Experimental Results"
    },
    BackgroundRamanSpectrum -> {
      Format -> Single,
      Class -> QuantityArray,
      Pattern :> QuantityCoordinatesP[{1/Centimeter,ArbitraryUnit}],
      Units -> {1/Centimeter, ArbitraryUnit},
      Description -> "The Raman spectrum of the vessel material used as a background for all elements of RamanSpectra and AverageRamanSpectrum.",
      Category -> "Experimental Results"
    },
    OpticalImages -> {
      Format -> Multiple,
      Class -> Link,
      Pattern :> _Link,
      Relation -> Object[EmeraldCloudFile],
      Description -> "The light microscopy images collected of the well.",
      Category -> "Experimental Results"
    },
    UnblankedRamanSpectra -> {
      Format -> Multiple,
      Class -> QuantityArray,
      Pattern :> QuantityCoordinatesP[{1/Centimeter,ArbitraryUnit}],
      Units -> {1/Centimeter, ArbitraryUnit},
      Description -> "The raw data corresponding to each measurement at a point of the SamplingPattern, in the form: {\"Wavenumber\", \"Intensity\"}.",
      Category -> "Data Processing"
    },

    (* -- POSITION INFO -- *)

    WellCenterPosition -> {
      Format -> Single,
      Class ->{Real, Real, Real},
      Pattern :> {GreaterP[0 Micrometer], GreaterP[0 Micrometer], GreaterP[0 Micrometer]},
      Units -> {Micrometer, Micrometer, Micrometer},
      Headers -> {"X coordinate","Y coordinate","Z coordinate"},
      Description -> "The absolute position of the well center referenced to the home position of the sample stage.",
      Category -> "General"
    },
    (*This is index matched to RamanSpectra but due to the way it displays in inspect, it is enforced in VOQ*)
    MeasurementPositions -> {
      Format -> Multiple,
      Class -> {Real, Real,Real},
      Pattern :> {RangeP[-100000 Micrometer, 100000 Micrometer], RangeP[-100000 Micrometer, 100000 Micrometer], RangeP[-100000 Micrometer, 100000 Micrometer]},
      Units -> {Micrometer, Micrometer, Micrometer},
      Headers -> {"X coordinate","Y coordinate","Z coordinate"},
      Description -> "For each member of RamanSpectra, the coordinates at which each data set was recorded, referenced to the center position of the well.",
      Category -> "General"
    },

    (* -- Method INFO -- *)
    DetectorExposure ->{
      Format -> Single,
      Class -> Real,
      Pattern:> GreaterP[0 Millisecond],
      Units -> Millisecond,
      Description -> "The amount of time scattering response is summed by the CCD detector during each measurement.",
      Category -> "General"
    },
    LaserPowerPercentage ->{
      Format -> Single,
      Class -> Real,
      Pattern :> RangeP[1 Percent, 100 Percent],
      Units -> Percent,
      Description -> "The power setting of the laser during this measurement as percentage of the maximum power.",
      Category -> "General"
    },
    Objective -> {
      Format -> Single,
      Class -> Integer,
      Pattern:> Alternatives[0,2,4,10,20],
      Description -> "The magnification factor of the objective used for this measurement. 0 indicates that FloodLight mode was used instead of an objective.",
      Category -> "General"
    },
    SpotSize -> {
      Format -> Single,
      Class -> Real,
      Pattern:>GreaterP[0 Micrometer],
      Units -> Micrometer,
      Description ->"The diameter of the area in which the beam is focused as it encounters the sample.",
      Category -> "General"
    },

    (* -- IMAGING -- *)
    LedBrightness ->{
      Format -> Single,
      Class -> Real,
      Pattern :> GreaterEqualP[0 Percent],
      Units -> Percent,
      Description -> "The LED brightness used to illuminate the sample for optical imaging.",
      Category -> "General"
    },
    CameraExposure ->{
      Format -> Single,
      Class -> Real,
      Pattern:>GreaterP[0 Millisecond],
      Units -> Millisecond,
      Description -> "The time over which the image is summed for the camera used for optical imaging.",
      Category -> "General"
    },

    (* -- CALIBRATION -- *)
    CalibrationScore -> {
      Format -> Single,
      Class -> Real,
      Pattern:>GreaterP[0],
      Units -> None,
      Description -> "The calibration score generated by measurement of an internal PMMA standard. The score ranges form 0 to 1, where 1 indicates a perfect match between calibration and reference spectra.",
      Category -> "General"
    }
  }
}];