

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Data, LuminescenceKinetics], {
	Description->"Luminescence measurements of a sample monitored over a period of time to study reaction trajectories.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {
		(* -- Method Information -- *)
		EmissionWavelengths -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterP[0*Meter*Nano],
			Units -> Meter Nano,
			Description -> "The wavelengths at which luminescence emitted from the samples is measured.",
			Category -> "General",
			Abstract -> True
		},
		DualEmissionWavelengths -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterP[0*Meter*Nano],
			Units -> Meter Nano,
			Description -> "The wavelength at which luminescence emitted from the sample is measured with the secondary detector (simultaneous to the measurement at the emission wavelength done by the primary detector).",
			Category -> "General",
			Abstract -> True
		},
		Gains -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Volt],
			Units -> Volt,
			Description -> "For each member of EmissionWavelengths, the voltage set on the PMT (photomultiplier tube) detector to amplify the detected signal during the emission scan.",
			IndexMatching -> EmissionWavelengths,
			Category -> "General"
		},
		DualEmissionGains -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Volt],
			Units -> Volt,
			Description -> "For each member of DualEmissionWavelengths, the voltage set on the PMT (photomultiplier tube) detector to amplify the detected signal during the emission scan.",
			IndexMatching -> DualEmissionWavelengths,
			Category -> "General"
		},
		IntegrationTime -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Minute],
			Units -> Second,
			Description -> "The amount of time over which luminescence measurements is integrated.",
			Category -> "General"
		},
		ReadOrder -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> ReadOrderP,
			Description -> "Indicates if this data was generated by running the reaction in isolation by recording each well one at a time in serial or was run along with the other wells in parallel.",
			Category -> "General"
		},
		FocalHeight -> {
			Format -> Single,
			Class -> Real,
			Pattern :> DistanceP,
			Units -> Meter Milli,
			Description -> "The distance from the bottom of the plate carrier to the focal point.",
			Category -> "General"
		},
		ReadLocation -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> ReadLocationP,
			Description -> "The position of the optic used to measure luminescence (above the plate or one below the plate).",
			Category -> "General"
		},
		PositioningDelay -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Second],
			Units -> Second,
			Description -> "The amount of time the system waits before taking measurements in order to allow for the sample to settle after it has moved into the measurement position.",
			Category -> "General"
		},
		DetectionInterval -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Second],
			Units -> Second,
			Description -> "The time interval at which readings were taken during the assay.",
			Category -> "General"
		},
		NominalTemperature -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Kelvin],
			Units -> Celsius,
			Description -> "The desired temperature of the sample chamber during the experimental run.",
			Category -> "General"
		},
		NominalOxygenLevel -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0*Percent],
			Units -> Percent,
			Description -> "The target oxygen level in the atmosphere inside the instrument set by the protocol.",
			Category -> "General",
			Abstract -> True
		},
		NominalCarbonDioxideLevel -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0*Percent],
			Units -> Percent,
			Description -> "The target carbon dioxide level in the atmosphere inside the instrument set by the protocol.",
			Category -> "General",
			Abstract -> True
		},
		Well -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> WellP,
			Description -> "The plate well of the sample at the time of its measurement.",
			Category -> "General",
			Abstract -> True
		},
		InjectionSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Sample][Data],
			Description -> "The samples that were injected into the well.",
			Category -> "General"
		},
		InjectionTimes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Second],
			Units -> Second,
			Description -> "For each member of InjectionSamples, the time at which the sample was added to the well.",
			IndexMatching -> InjectionSamples,
			Category -> "General"
		},
		InjectionVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Liter*Micro],
			Units -> Liter Micro,
			Description -> "For each member of InjectionSamples, the volume of the samples injected into the well.",
			IndexMatching -> InjectionSamples,
			Category -> "General"
		},
		InjectionFlowRates -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[(0*(Liter*Micro))/Second],
			Units -> (Liter Micro)/Second,
			Description ->"For each member of InjectionSamples, the flow rate at which the sample was added to the well.",
			IndexMatching -> InjectionSamples,
			Category -> "General"
		},
		(* -- Experimental Results -- *)
		EmissionTrajectories -> {
			Format -> Multiple,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Second,RLU}],
			Units -> {Second, RLU},
			Description -> "Luminescence readings recorded at the specified emission wavelengths as a function of time.",
			Category -> "Experimental Results"
		},
		DualEmissionTrajectories -> {
			Format -> Multiple,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Second,RLU}],
			Units -> {Second, RLU},
			Description -> "Luminescence readings recorded at the specified dual emission wavelengths as a function of time.",
			Category -> "Experimental Results"
		},
		Temperature -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Second,Celsius}],
			Units -> {Second, Celsius},
			Description -> "Temperature readings taken in the sample chamber, for the trajectories recorded.",
			Category -> "Experimental Results"
		},
		OxygenLevel -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Second,Percent}],
			Units -> {Second, Percent},
			Description -> "Oxygen level readings taken in the sample chamber, for the trajectories recorded.",
			Category -> "Experimental Results"
		},
		CarbonDioxideLevel -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Second,Percent}],
			Units -> {Second, Percent},
			Description -> "Carbon dioxide level readings taken in the sample chamber, for the trajectories recorded.",
			Category -> "Experimental Results"
		},
		DetectorRangeExceeded -> {
			Format -> Single,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates if any of the recorded intensities maxed out the instrument's detector.",
			Category -> "Experimental Results"
		},
		InvalidValuesExcluded -> {
			Format -> Single,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates if any of the recorded intensities are below 0 RFU and have been deleted from the final result.",
			Category -> "Experimental Results"
		},
		(* -- Analysis & Reports -- *)
		RateFittingAnalyses -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Analysis][Reference],
			Description -> "The data objects used to create a standard curve relating luminescence to concentration for this object.",
			Category -> "Analysis & Reports"
		}
	}
}];
