

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Data, RefractiveIndex], {
	Description -> "Data collected from the refractive index measurement.",
	CreatePrivileges -> None,
	Cache -> Session,
	Fields -> {
		MethodFiles -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[EmeraldCloudFile],
			Description -> "The file containing the method files used to run the instrument.",
			Category -> "General"
		},
		Temperature -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> DistributionP[]|GreaterP[0 Celsius],
			Description -> "The temperature at which the refractive index of a sample is measured.",
			Category -> "General"
		},
		RefractiveIndexReadingMode -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> RefractiveIndexReadingModeP,
			Description -> "Refractive index reading mode.",
			Category -> "General"
		},
		Calibrant -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link|Null,
			Relation -> Alternatives[Object[Sample],Model[Sample]],
			Description -> "Calibrant used for calibration measurement.",
			Category -> "General"
		},
		CalibrationTemperature -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Celsius]| Null,
			Description :> "Temperature in which refractive index of calibrant is measured.",
			Category -> "General"
		},
		CalibrantRefractiveIndex -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0]|Null,
			Description -> "Refractive index value from calibrant model or provided value.",
			Category -> "General"
		},
		MeasuredCalibrantRefractiveIndex -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0]|Null,
			Description -> "Refractive index of calibrant that measured by the refractometer.",
			Category -> "General"
		},
		RefractiveIndex -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> DistributionP[]|GreaterP[1],
			Description -> "The measured refractive index of a sample. If NumberOfReads is greater than 1, average value of refractive indexes from multiple measurements.",
			Category -> "Experimental Results"
		},
		RefractiveIndexTrajectory -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> {{GreaterEqualP[0 Second], GreaterP[1]}..}|Null,
			Description -> "The collection of measured refractive index of a sample in kinetic experiment.",
			Category -> "Experimental Results"
		},
		RefractiveIndexTemperatureProfile -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> {{GreaterP[0 Celsius], GreaterP[1]}..}|Null,
			Description -> "The measured refractive index of a sample in temperature scan experiment.",
			Category -> "Experimental Results"
		},
		DataFiles -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[EmeraldCloudFile],
			Description -> "The file containing the raw unprocessed data generated by the instrument.",
			Category -> "Experimental Results"
		}
	}
}];
