(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Data, AbsorbanceSpectroscopy], {
	Description->"Measurements of absorbance spectra for a range of wavelengths generated by the plate readers or UV/Vis Spectrophotometers.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {

		NominalTemperature -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Celsius],
			Units -> Celsius,
			Description -> "Indicates the target temperature the samples are held at prior to and during data acquisition within the instrument.",
			Category -> "General",
			Abstract -> True
		},
		SpectralBandwidth ->{
			Format->Single,
			Class->Real,
			Pattern:>RangeP[0.5 Nanometer,5 Nanometer],
			Units->Nanometer,
			Description->"When using the Cuvette Method, indicates the physical size of the slit from which light passes out from the monochromator. The narrower the bandwidth, the greater the resolution in measurements.",
			Category->"Absorbance Measurement"
		},
		MinWavelength -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0*Meter],
			Units -> Meter Nano,
			Description -> "The minimum wavelength at which absorbance data was acquired.",
			Category -> "Absorbance Measurement"
		},
		MaxWavelength -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0*Meter],
			Units -> Meter Nano,
			Description -> "The maximum wavelength at which absorbance data was acquired.",
			Category -> "Absorbance Measurement"
		},
		PositioningDelay -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Second],
			Units -> Second,
			Description -> "The delay time after the instrument moved to a well position before it began taking readings.",
			Category -> "General"
		},
		NumberOfReadings -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterP[0, 1],
			Units -> None,
			Description -> "The number of readings taken and averaged to generate the spectrum for the sample.",
			Category -> "General"
		},
		PlateModel -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Container, Plate],
				Model[Container, MicrofluidicChip],
				Model[Container, Cuvette]
			],
			Description -> "The model of the plate/microfluidic chip/cuvette containing the samples used in the experiment.",
			Category -> "General"
		},
		CuvetteModel -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Container, Cuvette],
			Description -> "The model of the cuvette containing the sample(s) and through which the light beam is passed during the absorbance measurement.",
			Category -> "General"
		},
		CuvetteNumber -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterP[0, 1],
			Units -> None,
			Description -> "The position of the sample's cuvette inside the heatblock of the spectrophotometer instrument during absorbance measurement.",
			Category -> "General"
		},
		SampleVolume -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterP[0 * Microliter],
			Units -> Microliter,
			Description -> "For each member of SamplesIn, the amount of liquid of each sample within its container used in this assay.",
			Category -> "General",
			IndexMatching -> SamplesIn
		},
		AcquisitionMixRate -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 RPM],
			Units -> RPM,
			Description -> "Indicates if the rate at which the samples within the cuvette should be mixed with a stir bar during data acquisition.",
			Category -> "Absorbance Measurement"
		},
		NominalAcquisitionMixRate -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 RPM],
			Units -> RPM,
			Description -> "Indicates the target/set rate at which the samples within the cuvette should be mixed with a stir bar during data acquisition.",
			Category -> "Absorbance Measurement"
		},
		ActualAcquisitionMixRate -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 RPM],
			Units -> RPM,
			Description -> "Indicates the absolute/exact rate at which the samples within the cuvette attained during data acquisition.",
			Category -> "Absorbance Measurement"
		},
		BufferModel -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample, StockSolution],
				Model[Sample]
			],
			Description -> "The buffer used in the assay.",
			Category -> "General"
		},
		StirringError -> {
			Format -> Single,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates if stable stirring was not achieved within the cuvette after MaxStirAttempts during the setup of the assay.",
			Category -> "Absorbance Measurement"
		},
		Well -> {
			Format -> Single,
			Class -> String,
			Pattern :> WellP,
			Description -> "The well number from which the spectrum was recorded.",
			Category -> "General",
			Abstract -> True
		},
		InjectionSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Sample][Data],
			Description -> "The samples that were injected into the well.",
			Category -> "General"
		},
		InjectionTimes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Second],
			Units -> Second,
			Description -> "For each member of InjectionSamples, the time at which the sample was added to the well.",
			IndexMatching -> InjectionSamples,
			Category -> "General"
		},
		InjectionVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Liter*Micro],
			Units -> Liter Micro,
			Description -> "For each member of InjectionSamples, the volume of the samples injected into the well.",
			IndexMatching -> InjectionSamples,
			Category -> "General"
		},
		InjectionFlowRates -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[(0*(Liter*Micro))/Second],
			Units -> (Liter Micro)/Second,
			Description ->"For each member of InjectionSamples, the flow rate at which the sample was added to the well.",
			IndexMatching -> InjectionSamples,
			Category -> "General"
		},
		RawAbsorbanceDataFile -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[EmeraldCloudFile],
			Description -> "The file containing the raw unprocessed data generated by the instrument without any smoothing.",
			Category -> "General"
		},
		AbsorbanceSpectrum -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Nanometer,AbsorbanceUnit}],
			Units -> {Meter Nano, AbsorbanceUnit},
			Description -> "The absorbance spectrum in the form: {wavelength, absorbance}, with the blank spectra subtracted (if available).",
			Category -> "Experimental Results"
		},
		RawAbsorbanceSpectrum -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Nanometer,AbsorbanceUnit}],
			Units -> {Meter Nano, AbsorbanceUnit},
			Description -> "The absorbance measured at the wavelength, with the blank absorbance subtracted (if available).",
			Category -> "Data Processing"
		},
		Transmittance -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Nanometer,Percent}],
			Units -> {Meter Nano, Percent},
			Description -> "The percent Transmittance in the form: {wavelength, %}, calculated from the absorbance spectrum of the sample after reference blank subtraction (if available).",
			Category -> "Experimental Results"
		},
		Temperature -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Nanometer,Celsius}],
			Units -> {Meter Nano, Celsius},
			Description -> "The temperature in the instrument's sample compartment at each wavelength as it was recorded.",
			Category -> "Experimental Results"
		},
		UnblankedAbsorbanceSpectrum -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Nanometer,AbsorbanceUnit}],
			Units -> {Meter Nano, AbsorbanceUnit},
			Description -> "The raw, unblanked absorbance spectrum in the form: {wavelength, unblanked absorbance}.",
			Category -> "Data Processing",
			Abstract -> True
		},
		DataType -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> AbsorbanceSpectroscopyDataTypeP,
			Description -> "Whether this data represents an empty plate, blank, or analyte absorbance reading.",
			Category -> "Data Processing"
		},
		EmptySpectrum -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Data, AbsorbanceSpectroscopy][BlankSpectrum],
				Object[Data, AbsorbanceSpectroscopy][AnalyteSpectra],
				Object[Data, AbsorbanceSpectroscopy][AnalyteSpectrum]
			],
			Description -> "The absorbance data from the same well as this data but with nothing in it.",
			Category -> "Experimental Results"
		},
		BlankSpectrum -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Data, AbsorbanceSpectroscopy][EmptySpectrum],
				Object[Data, AbsorbanceSpectroscopy][AnalyteSpectrum],
				Object[Data, AbsorbanceSpectroscopy][AnalyteSpectra]
			],
			Description -> "A blank absorbance spectra which includes absorbance from the buffer and container but without any analyte present.",
			Category -> "Experimental Results"
		},
		AnalyteSpectrum -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Data, AbsorbanceSpectroscopy][BlankSpectrum],
				Object[Data, AbsorbanceSpectroscopy][EmptySpectrum]
			],
			Description -> "The absorbance data from the same well as this data but with sample in it.",
			Category -> "Experimental Results"
		},
		AnalyteSpectra -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Data, AbsorbanceSpectroscopy][BlankSpectrum],
				Object[Data, AbsorbanceSpectroscopy][EmptySpectrum]
			],
			Description -> "Any absorbance data which use this data as a blank spectra to subtract baseline signal due to the buffer or container rather than the analyte.",
			Category -> "Experimental Results"
		},
		Analyte -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> IdentityModelTypeP,
			Description -> "The substance whose concentration is measured in this data.",
			Category -> "Analysis & Reports"
		},
		AbsorbanceSpectrumPeaksSource -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Analysis][Reference],
			Description -> "A running log of all peak picking conducted on the blanked spectrum.",
			Category -> "Analysis & Reports"
		},
		Concentration -> {
			Format -> Single,
			Class -> Real,
			Pattern :> _?ConcentrationQ,
			Units -> Micromolar,
			Description -> "The concentration of the sample in the source plate, i.e. the original un-diluted sample.",
			Category -> "Analysis & Reports",
			Abstract -> True
		},
		MassConcentration -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[(0*Gram)/Liter],
			Units -> Gram/Liter,
			Description -> "The most recently calculated mass of the constituent(s) divided by the volume of the mixture.",
			Category -> "Physical Properties"
		},
		DilutedConcentration -> {
			Format -> Single,
			Class -> Real,
			Pattern :> _?ConcentrationQ,
			Units -> Micromolar,
			Description -> "The calculated concentration of the sample in the read plate after the sample has been diluted to be within range of the sensors.",
			Category -> "Analysis & Reports"
		},
		DilutedMassConcentration -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[(0*Gram)/Liter],
			Units -> Gram/Liter,
			Description -> "The calculated mass concentration of the sample in the read plate after the sample has been diluted to be within range of the sensors.",
			Category -> "Analysis & Reports"
		},
		PathLength -> {
			Format -> Single,
			Class -> Real,
			Pattern :> _?DistanceQ,
			Units -> Meter Milli,
			Description -> "The distance that the path of light from the plate reader had to travel to traverse through the sample in the plate.",
			Category -> "Analysis & Reports"
		},
		PathLengthMethod -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> PathLengthMethodP,
			Description -> "The method by which the path length from the plate reader to the sample in the read plate was determined.",
			Category -> "Analysis & Reports"
		},
		SingleCuvetteRead -> {
			Format -> Single,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates that this absorbance data was created using data obtained from only a single microfluidic chip cuvette, when multiple cuvettes should have been read. This may indicate that the data in this read is less accurate than normal.",
			Category -> "Analysis & Reports"
		},
		QuantificationAnalyses -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Analysis, AbsorbanceQuantification][AbsorbanceSpectraEmpty],
				Object[Analysis, AbsorbanceQuantification][AbsorbanceSpectraBlank],
				Object[Analysis, AbsorbanceQuantification][AbsorbanceSpectra],
				Object[Analysis][Reference]
			],
			Description -> "Quantification of a sample using Beer-Lambert's law that use this absorbance spectrum as source data.",
			Category -> "Analysis & Reports"
		},
		SmoothingAnalyses -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Analysis][Reference],
			Description -> "Smoothing analysis performed on this data.",
			Category -> "Analysis & Reports"
		}
	}
}];
