

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Data,MeltingPoint],{
	Description->"Measurements of temperature vs visible light transmittance accompanied by videos of the melting process measured and recorded by a melting point apparatus.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		(*===General===*)
		AssaySample -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Sample][Data]],
			Description -> "The sample (aliquots of SamplesIn) that this assay is performed on.",
			Category -> "General"
		},
		(*===Method Information===*)
		NumberOfReplicates->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterP[0,1],
			Description->"Number of capillaries that were packed with the same input sample and were analyzed in this experiment. Null indicates 1 capillary.",
			Category->"Method Information"
		},
		SealCapillary->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the capillary is closed at the top end by polymer clay after being packed with the input sample.",
			Category->"Method Information"
		},
		StartTemperature->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 Kelvin],
			Units->Celsius,
			Description->"The initial temperature of the chamber that holds the capillaries before sweeping the temperature to MaxTemperature.",
			Category->"Method Information"
		},
		EquilibrationTime->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 Second],
			Units->Second,
			Description->"The amount of time that the sample is equilibrated at MinTemperature before starting temperature ramp.",
			Category->"Method Information"
		},
		EndTemperature->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 Kelvin],
			Units->Celsius,
			Description->"The final temperature to conclude the temperature sweep of the chamber that holds sample capillary.",
			Category->"Method Information"
		},
		TemperatureRampRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 Celsius/Minute],
			Units->Celsius/Minute,
			Description->"The rate at which the temperature is swept from MinTemperature to MaxTemperature. Slower TemperatureRampRate results in higher precision in melting point measurements.",
			Category->"Method Information"
		},
		Position->{
			Format->Single,
			Class->String,
			Pattern:>LocationPositionP,
			Description->"The position of the capillary in the capillary slot of the melting point apparatus.",
			Category->"Method Information"
		},
		(*===Experimental Results===*)
		MeltingCurve->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityArrayP[{{Celsius,Percent}..}],
			Units->{Celsius,Percent},
			Description->"The measured transmittance as a function of temperature during the melting point measurement process.	The measured transmittance is the percentage of the transmitted light intensity at any time point of the measurement relative to the transmitted light intensity when the sample is fully-melted.",
			Category->"Experimental Results",
			Abstract->True
		},
		(*--Data Processing--**)
		MeltingCurveFile->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"An exported CSV file(s) containing the raw unprocessed digital transmittance data from positions A1, A2, and A3 (left to right) generated by the instrument.",
			Category->"Experimental Results"
		},
		CapillaryVideoFile->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"The file containing the recorded video of the melting point capillaries from positions A1, A2, and A3 (left to right) recorded by the instrument.",
			Category->"Experimental Results"
		},
		TransmissionVideoFile->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"The file containing the transmission (amount of light passed through the capillary) video of the melting point capillaries from positions A1, A2, and A3 (left to right) recorded by the instrument.",
			Category->"Experimental Results"
		},

		(*Analysis fields*)
		MeltingAnalyses->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[Analysis][Reference],
			Description->"Melting point analysis performed on this data.",
			Category->"Analysis & Reports"
		},
		ThermodynamicMeltingTemperature->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0*Kelvin],
			Units->Celsius,
			Description->"The temperature measured at MeltingPointCriterion and corrected for the difference between the temperature of the furnace and the capillary. MeltingPointCriterion is either MeniscusPoint determined by MeniscusPointThreshold or ClearPoint determined by ClearPointThreshold. MeniscusPointThreshold is a transmission percent which determines the meniscus point and is defaulted at 40%. ClearPointThreshold is a transmission-time slope which determines the clear point and is defaulted at 0.4%/s.",
			Category->"Analysis & Reports"
		}
	}
}];
