(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Data,Osmolality],{
	Description->"Osmolality of a solution as determined by an osmometer.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		(*Method Information*)
		DataType->{
			Format->Single,
			Class->Expression,
			Pattern:>Alternatives[Standard,Analyte],
			Description->"Indicates if this data represents a control sample of known osmolality or an analyte sample.",
			Category->"Experimental Results"
		},
		MeasurementMethod->{
			Format->Single,
			Class->Expression,
			Pattern:>OsmolalityMethodP,
			Description->"The experimental technique or principle used to determine the osmolality of the samples.",
			Category->"General"
		},
		NumberOfReadings->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[0,1],
			Description->"The number of osmolality readings to perform on the same sample once loaded into the instrument.",
			Category->"General"
		},
		SampleVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 Microliter],
			Units->Microliter,
			Description->"The volume of sample solution that is loaded into the osmometer and used for the measurement of osmolality.",
			Category->"General"
		},
		StandardData->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[Data,Osmolality][SampleData],
			Description->"The osmolality data for reference sample(s), with known osmolality, associated with this sample data.",
			Category->"General"
		},
		SampleData->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[Data,Osmolality][StandardData],
			Description->"The osmolality data for unknown sample(s) associated with this standard data.",
			Category->"General"
		},
		DateAcquired->{
			Format->Multiple,
			Class->Date,
			Pattern:>_?DateObjectQ,
			Description->"The dates on which the readings were acquired.",
			Category->"Organizational Information"
		},
		(*Calibration*)
		Calibrants->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Sample],Model[Sample]],
			Description->"The solutions of known osmolality used by the instrument to determine the conversion from raw measurement to osmolality.",
			Category->"Calibration"
		},
		CalibrantOsmolalities->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterEqualP[0 Milli Mole/Kilogram],
			Units->Milli Mole/Kilogram,
			Description->"For each member of Calibrants, the osmolality of the solution used by the instrument to determine the conversion from raw measurement to osmolality.",
			Category->"Calibration",
			IndexMatching->Calibrants
		},
		(*Experimental Results*)
		Osmolality->{
			Format->Single,
			Class->Distribution,
			Pattern:>DistributionP[Milli Mole/Kilogram],
			Units->Milli Mole/Kilogram,
			Description->"The empirical distribution of osmolality measurements of the sample solution, as measured by the selected osmolality measurement method, under the stated conditions.",
			Category->"Experimental Results"
		},
		RawDataFile->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"The file containing the raw unprocessed data generated by the instrument, in proprietary format.",
			Category->"Experimental Results"
		},
		VideoFile->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"A video recording of this measurement being performed on the instrument in the lab.",
			Category->"Experimental Results"
		},
		InitialInstrumentContaminationLevel->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[0],
			Units->None,
			Description->"The instrument thermocouple contamination level as measured by the instrument at the beginning of the protocol, when the calibration is performed. For the Vapro 5600 this is measured when the 100 mmol/kg standard is run.",
			Category->"Experimental Results"
		},
		PostRunInstrumentContaminationLevel->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[0],
			Units->None,
			Description->"The instrument thermocouple contamination level as measured by the instrument at the end of the protocol, after sample measurement. For the Vapro 5600 this is measured when a 100 mmol/kg standard is run.",
			Category->"Experimental Results"
		},
		Temperature->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{None,Celsius}],
			Units->{None,Celsius},
			Description->"The ambient temperature around the instrument during the measurement period.",
			Category->"Experimental Results"
		},
		RelativeHumidity->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{None,Percent}],
			Units->{None,Percent},
			Description->"The ambient relative humidity around the instrument during the measurement period.",
			Category->"Experimental Results"
		}
	}
}]
