(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Data,DynamicFoamAnalysis],{
	Description->"The data generated from a Dynamic Foam Analysis experiment, which provides information on the foamability, foam stability, liquid content, drainage, and bubble distribution of foam.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		(*Method Information*)
		DetectionMethod->{
			Format->Single,
			Class->Expression,
			Pattern:>{FoamDetectionMethodP..},
			Description->"The type of foam detection method(s) that was used during the experiment. The foam detection methods are the Height Method (default method for the Dynamic Foam Analyzer), Liquid Conductivity Method, and Imaging Method. The Height Method provides information on foamability and foam height, the Liquid Conductivity Method provides information on the liquid content and drainage dynamics of foam, and then Imaging Method provides data on the size and distribution of foam bubbles.",
			Category -> "General"
		},
		SampleVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 Milliliter],
			Units->Milliliter,
			Description->"The volume of initial liquid sample solution that was used for the dynamic foam analysis experiment.",
			Category -> "General"
		},
		AdditiveSampleMass -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Gram],
			Units -> Gram,
			Description -> "The mass of initial solid sample that was used for the dynamic foam analysis experiment.",
			Category -> "General"
		},
		AdditiveSamplesIn -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Sample][Data],
			Description -> "The additive samples that were mixed with SamplesIn to generate this data.",
			Category -> "General"
		},
		AgitationTime->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0*Second],
			Units->Minute,
			Description->"The amount of time that the liquid sample was agitated to generate foam.",
			Category -> "General"
		},
		DecayTime->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0*Second],
			Units->Minute,
			Description->"The amount of time that the foam was allowed to decay in the experiment, during which experimental measurements were taken.",
			Category -> "General"
		},
		Wavelength->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 Nanometer],
			Units->Nanometer,
			Description->"The wavelength that was used to illuminate the sample column during the course of the experiment.",
			Category->"Instrument Specifications"
		},
		FieldOfView->{
			Format->Single,
			Class->Integer,
			Pattern:>Alternatives[85 Millimeter^2,140 Millimeter^2,285 Millimeter^2],
			Units->Millimeter^2,
			Description->"The field of view used by the Foam Structure Module in the experiment.",
			Category -> "General"
		},
		CameraHeight->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0*Millimeter],
			Units->Millimeter,
			Description->"The height at which the camera used by the Foam Structure Module was positioned during the experiment.",
			Category->"Instrument Specifications"
		},

		(*Experimental Results*)
		RawDataFiles->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"The csv files containing the raw unprocessed data generated by the instrument, as extracted from the spreadsheet generated by the instrument software.",
			Category->"Experimental Results"
		},
		RawVideoFile->{
			Format->Single,
			Class->{
				Time->Date,
				VideoFile->Link
			},
			Pattern:>{
				Time->_?DateObjectQ,
				VideoFile->_Link
			},
			Relation->{
				Time->Null,
				VideoFile->Object[EmeraldCloudFile]
			},
			Headers->{
				Time->"Time",
				VideoFile->"Video File"
			},
			Description->"The file containing the raw unprocessed video data generated by the instrument, in proprietary format.",
			Category->"Experimental Results"
		},
		FoamHeight->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Millimeter}],
			Units->{Second,Millimeter},
			Description->"The foam height results, measured over time, in the form of {Time (seconds), Foam height (millimeter)}.",
			Category->"Experimental Results"
		},
		LiquidHeight->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Millimeter}],
			Units->{Second,Millimeter},
			Description->"The liquid height results, measured over time, in the form of {Time (seconds), Liquid height (millimeter)}.",
			Category->"Experimental Results"
		},
		TotalFoamLiquidHeight->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Millimeter}],
			Units->{Second,Millimeter},
			Description->"The combined foam and liquid height results, measured over time, in the form of {Time (seconds), Total foam and liquid height (millimeter)}.",
			Category->"Experimental Results"
		},
		FoamVolume->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Milliliter}],
			Units->{Second,Milliliter},
			Description->"The foam volume results, measured over time, in the form of {Time (seconds), Foam volume (milliliter)}.",
			Category->"Experimental Results"
		},
		LiquidVolume->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Milliliter}],
			Units->{Second,Milliliter},
			Description->"The liquid volume results, measured over time, in the form of {Time (seconds), Liquid volume (milliliter)}.",
			Category->"Experimental Results"
		},
		TotalFoamLiquidVolume->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Milliliter}],
			Units->{Second,Milliliter},
			Description->"The combined foam and liquid volume results, measured over time, in the form of {Time (seconds), Total volume (milliliter)}.",
			Category->"Experimental Results"
		},
		FoamVolumeStability->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Percent}],
			Units->{Second,Percent},
			Description->"The foam volume stability results, measured over time, in the form of {Time (seconds), Foam volume stability (%)}. The foam volume stability refers to the percentage of the foam volume remaining with respect to the maximum foam volume after foaming has stopped.",
			Category->"Experimental Results"
		},
		FoamLiquidStability->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Percent}],
			Units->{Second,Percent},
			Description->"The foam liquid stability results, measured over time, in the form of {Time (seconds), Foam liquid stability (%)}. The foam liquid stability refers to the percentage of the liquid volume remaining in the foam with respect to the maximum liquid volume after foaming has stopped.",
			Category->"Experimental Results"
		},
		FoamTemperature->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Celsius}],
			Units->{Second,Celsius},
			Description->"The foam temperature results, measured over time, in the form of {Time (seconds), Temperature (Celsius)}.",
			Category->"Experimental Results"
		},
		LiquidContentSensor1->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Percent}],
			Units->{Second,Percent},
			Description->"The liquid content results for Sensor 1 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 1 (%)}.",
			Category->"Experimental Results"
		},
		LiquidContentSensor2->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Percent}],
			Units->{Second,Percent},
			Description->"The liquid content results for Sensor 2 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 2 (%)}.",
			Category->"Experimental Results"
		},
		LiquidContentSensor3->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Percent}],
			Units->{Second,Percent},
			Description->"The liquid content results for Sensor 3 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 3 (%)}.",
			Category->"Experimental Results"
		},
		LiquidContentSensor4->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Percent}],
			Units->{Second,Percent},
			Description->"The liquid content results for Sensor 4 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 4 (%)}.",
			Category->"Experimental Results"
		},
		LiquidContentSensor5->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Percent}],
			Units->{Second,Percent},
			Description->"The liquid content results for Sensor 5 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 5 (%)}.",
			Category->"Experimental Results"
		},
		LiquidContentSensor6->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Percent}],
			Units->{Second,Percent},
			Description->"The liquid content results for Sensor 6 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 6 (%)}.",
			Category->"Experimental Results"
		},
		LiquidContentSensor7->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Percent}],
			Units->{Second,Percent},
			Description->"The liquid content results for Sensor 7 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 7 (%)}.",
			Category->"Experimental Results"
		},
		ResistanceReferenceSensor->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Ohm}],
			Units->{Second,Ohm},
			Description->"The resistance results for the reference sensor from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Reference sensor (Ohm)}.",
			Category->"Experimental Results"
		},
		ResistanceSensor1->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Ohm}],
			Units->{Second,Ohm},
			Description->"The resistance results for Sensor 1 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 1 (Ohm)}.",
			Category->"Experimental Results"
		},
		ResistanceSensor2->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Ohm}],
			Units->{Second,Ohm},
			Description->"The resistance results for Sensor 2 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 2 (Ohm)}.",
			Category->"Experimental Results"
		},
		ResistanceSensor3->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Ohm}],
			Units->{Second,Ohm},
			Description->"The resistance results for Sensor 3 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 3 (Ohm)}.",
			Category->"Experimental Results"
		},
		ResistanceSensor4->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Ohm}],
			Units->{Second,Ohm},
			Description->"The resistance results for Sensor 4 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 4 (Ohm)}.",
			Category->"Experimental Results"
		},
		ResistanceSensor5->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Ohm}],
			Units->{Second,Ohm},
			Description->"The resistance results for Sensor 5 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 5 (Ohm)}.",
			Category->"Experimental Results"
		},
		ResistanceSensor6->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Ohm}],
			Units->{Second,Ohm},
			Description->"The resistance results for Sensor 6 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 6 (Ohm)}.",
			Category->"Experimental Results"
		},
		ResistanceSensor7->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Ohm}],
			Units->{Second,Ohm},
			Description->"The resistance results for Sensor 7 from the LiquidConductivityMethod of detection, measured over time, in the form of {Time (seconds), Sensor 7 (Ohm)}.",
			Category->"Experimental Results"
		},
		BubbleCount->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Millimeter^-2}],
			Units->{Second,Millimeter^-2},
			Description->"The bubble count results from the ImagingMethod of detection, measured over time, in the form of {Time (second), Bubble count (per millimeter^2)}.",
			Category->"Experimental Results"
		},
		MeanBubbleArea->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Micrometer^2}],
			Units->{Second,Micrometer^2},
			Description->"The mean bubble area results from the ImagingMethod of detection, measured over time, in the form of {Time (second), Mean bubble area (micrometer^2)}.",
			Category->"Experimental Results"
		},
		StandardDeviationBubbleArea->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Micrometer^2}],
			Units->{Second,Micrometer^2},
			Description->"The standard deviation bubble area results from the ImagingMethod of detection, measured over time, in the form of {Time (second), Standard deviation of bubble areas (micrometer^2)}.",
			Category->"Experimental Results"
		},
		AverageBubbleRadius->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Micrometer}],
			Units->{Second,Micrometer},
			Description->"The average bubble radius results from the ImagingMethod of detection, measured over time, in the form of {Time (second), Average bubble radius (micrometer)}.",
			Category->"Experimental Results"
		},
		MeanSquareBubbleRadius->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Micrometer}],
			Units->{Second,Micrometer},
			Description->"The mean square bubble radius results from the ImagingMethod of detection, measured over time, in the form of {Time (second), Mean square bubble radius (micrometer)}.",
			Category->"Experimental Results"
		},
		BubbleSauterMeanRadius->{
			Format->Single,
			Class->QuantityArray,
			Pattern:>QuantityCoordinatesP[{Second,Micrometer}],
			Units->{Second,Micrometer},
			Description->"The bubble sauter mean radius results from the ImagingMethod of detection, measured over time, in the form of {Time (second), Sauter mean radius (micrometer)}.",
			Category->"Experimental Results"
		},
		FoamHeightParameters->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				TimeP,
				VolumeP,
				VolumeP,
				VolumeP,
				_?NumberQ,
				_?NumberQ,
				TimeP,
				TemperatureP
			},
			Units->{
				Second,
				Milliliter,
				Milliliter,
				Milliliter,
				None,
				None,
				Second,
				Celsius
			},
			Headers->{
				"Maximum foam height time (Tmax)",
				"Maximum foam volume",
				"Liquid volume in foam at Tmax",
				"Total volume at Tmax",
				"Ratio of liquid volume in foam at Tmax to maximum foam volume",
				"Ratio of maximum foam volume to maximum liquid foam volume",
				"Head retention value: time difference between drainage half life time and 75% drainage time",
				"Mean temperature"
			},
			Description->"The foam height parameter results that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		FoamVolumeStabilityTimes->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				TimeP,
				TimeP,
				TimeP,
				TimeP
			},
			Units->{
				Second,
				Second,
				Second,
				Second
			},
			Headers->{
				"Foam half life time: time at which foam volume stability is 50% of initial value",
				"25% Drainage time: time at which the foam liquid stability has reduced to 75% of its initial value",
				"Drainage half life time: time at which the foam liquid stability has reduced to 50% of its initial value",
				"75% Drainage time: time at which the foam liquid stability has reduced to 25% of its initial value"
			},
			Description->"The foam height parameter results that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		FoamStructureParameters->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				_Real,
				_Real,
				_Real,
				_Real,
				_Real
			},
			Units->{
				Second,
				Millimeter^-2,
				Second,
				Second,
				Millimeter^-2
			},
			Headers->{
				"Foam stabilization time",
				"Initial bubble count per millimeter squared",
				"Bubble count half life time",
				"Time at end of first foaming phase",
				"Final bubble count per millimeter squared"
			},
			Description->"The foam structure parameter results that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		BubbleSizeParameters->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				_Real,
				_Real,
				_Real,
				_Real,
				_Real,
				_Real
			},
			Units->{
				Micrometer^2,
				Micrometer,
				Micrometer,
				Micrometer^2,
				Micrometer,
				Micrometer
			},
			Headers->{
				"Initial mean bubble area",
				"Initial average bubble radius",
				"Initial Sauter mean radius",
				"Final mean bubble area",
				"Final average bubble radius",
				"Final Sauter mean radius"
			},
			Description->"The bubble size parameter results that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		LiquidConductivityParametersSensor1->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				_Real,
				_Real,
				_Real,
				_Real,
				_Real
			},
			Units->{
				Percent,
				Second,
				Second,
				Second,
				Second
			},
			Headers->{
				"Maximum liquid content",
				"Maximum liquid content time",
				"75% liquid content time",
				"50% liquid content time",
				"25% liquid content time"
			},
			Description->"The liquid conductivity parameter results for sensor 1 that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		LiquidConductivityParametersSensor2->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				_Real,
				_Real,
				_Real,
				_Real,
				_Real
			},
			Units->{
				Percent,
				Second,
				Second,
				Second,
				Second
			},
			Headers->{
				"Maximum liquid content",
				"Maximum liquid content time",
				"75% liquid content time",
				"50% liquid content time",
				"25% liquid content time"
			},
			Description->"The liquid conductivity parameter results for sensor 1 that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		LiquidConductivityParametersSensor3->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				_Real,
				_Real,
				_Real,
				_Real,
				_Real
			},
			Units->{
				Percent,
				Second,
				Second,
				Second,
				Second
			},
			Headers->{
				"Maximum liquid content",
				"Maximum liquid content time",
				"75% liquid content time",
				"50% liquid content time",
				"25% liquid content time"
			},
			Description->"The liquid conductivity parameter results for sensor 1 that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		LiquidConductivityParametersSensor4->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				_Real,
				_Real,
				_Real,
				_Real,
				_Real
			},
			Units->{
				Percent,
				Second,
				Second,
				Second,
				Second
			},
			Headers->{
				"Maximum liquid content",
				"Maximum liquid content time",
				"75% liquid content time",
				"50% liquid content time",
				"25% liquid content time"
			},
			Description->"The liquid conductivity parameter results for sensor 1 that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		LiquidConductivityParametersSensor5->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				_Real,
				_Real,
				_Real,
				_Real,
				_Real
			},
			Units->{
				Percent,
				Second,
				Second,
				Second,
				Second
			},
			Headers->{
				"Maximum liquid content",
				"Maximum liquid content time",
				"75% liquid content time",
				"50% liquid content time",
				"25% liquid content time"
			},
			Description->"The liquid conductivity parameter results for sensor 1 that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		LiquidConductivityParametersSensor6->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				_Real,
				_Real,
				_Real,
				_Real,
				_Real
			},
			Units->{
				Percent,
				Second,
				Second,
				Second,
				Second
			},
			Headers->{
				"Maximum liquid content",
				"Maximum liquid content time",
				"75% liquid content time",
				"50% liquid content time",
				"25% liquid content time"
			},
			Description->"The liquid conductivity parameter results for sensor 1 that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		LiquidConductivityParametersSensor7->{
			Format->Single,
			Class->{
				Real,
				Real,
				Real,
				Real,
				Real
			},
			Pattern:>{
				_Real,
				_Real,
				_Real,
				_Real,
				_Real
			},
			Units->{
				Percent,
				Second,
				Second,
				Second,
				Second
			},
			Headers->{
				"Maximum liquid content",
				"Maximum liquid content time",
				"75% liquid content time",
				"50% liquid content time",
				"25% liquid content time"
			},
			Description->"The liquid conductivity parameter results for sensor 1 that are calculated from the foam height data, as processed by the dynamic foam analyzer instrument software.",
			Category->"Experimental Results"
		},
		ConvertedVideoFile->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"The ZIP file containing each frame of raw video data generated by the instrument, where each frame is a PNG or TIFF image file.",
			Category->"Analysis & Reports"
		},
		BubbleRadiusAnalyses->{
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Analysis][Reference],
			Description -> "A list of bubble radius analyses conducted on the ConvertedVideoFile with foam structure data in this object.",
			Category -> "Analysis & Reports"
		}
	}
}];
