

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Data, AlphaScreen], {
	Description->"AlphaScreen measurement of the samples that contained analytes with acceptor and donor AlphaScreen beads. Upon laser excitation at 680nm to the donor AlphaScreen beads, singlet Oxygen was produced and diffused to the acceptor AlphaScreen beads only when the two beads were in close proximity. The acceptor AlphaScreen beads reacted with the singlet Oxygen and emitted light signal at 570nm which was captured by a detector in plate reader.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {
		(*General*)
		PreparedPlate -> {
			Format -> Single,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates if the SamplesIn were from a prepared plate. The prepared plate contained the analytes, acceptor and donor AlphaScreen beads that were excited by AlphaScreen laser for luminescent AlphaScreen measurement in a plate reader. If the 'PreparedPlate' was False, the samples that contained all the components were transferred to the 'AssayPlate' for AlphaScreen measurement.",
			Category -> "General"
		},
		(*Optics Optimization*)
		OpticsOptimizationTemplate -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Protocol,AlphaScreen],
			Description -> "The previous protocol that contained the optimized gain and focal height values for the AlphaScreen measurement. The gain and focal height values from the previous protocol were taken and used in the current protocol with no further optimization.",
			Category -> "Optics Optimization"
		},
		(*Optics*)
		ReadTemperature -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Celsius],
			Units -> Celsius,
			Description -> "The temperature at which the measurement was taken in the plate reader.",
			Category -> "General"
		},
		NominalOxygenLevel -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0*Percent],
			Units -> Percent,
			Description -> "The target oxygen level in the atmosphere inside the instrument set by the protocol.",
			Category -> "General",
			Abstract -> True
		},
		NominalCarbonDioxideLevel -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0*Percent],
			Units -> Percent,
			Description -> "The target carbon dioxide level in the atmosphere inside the instrument set by the protocol.",
			Category -> "General",
			Abstract -> True
		},
		Gain -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Microvolt],
			Units -> Microvolt,
			Description -> "The gain which was applied to the signal reaching the primary detector photomultiplier tube (PMT).",
			Category -> "General"
		},
		FocalHeight -> {
			Format -> Single,
			Class -> Real,
			Pattern :> DistanceP,
			Units -> Millimeter,
			Description -> "The distance from the focal point to the lens that collected the light to the primary detector photomultiplier tube (PMT).",
			Category -> "General"
		},
		SettlingTime -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Second],
			Units -> Second,
			Description -> "The time between the movement of the plate and the beginning of the measurement. It reduces potential vibration of the samples in plate due to the stop and go motion of the plate carrier.",
			Category -> "General"
		},
		ExcitationTime -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Second],
			Units -> Second,
			Description -> "The time that the samples were excited by the light source and the singlet Oxygen was generated.",
			Category -> "General"
		},
		DelayTime -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Second],
			Units -> Second,
			Description -> "The time between end of excitation and start of the emission signal integration. It allows the singlet Oxygen to react with the acceptor beads and reduces potential auto-fluorescent noise generated by biomolecular components.",
			Category -> "General"
		},
		IntegrationTime -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Second],
			Units -> Second,
			Description -> "The amount of time for which the emission signal was integrated. The signal is added, rather than averaged over time. For example, if the interaction time is doubled, the signal is expected to be doubled.",
			Category -> "General"
		},
		ExcitationWavelength -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Nanometer],
			Units -> Nanometer,
			Description -> "The excitation wavelength determined by the AlphaScreen laser. The AlphaScreen laser excites the AlphaScreen donor beads to generate singlet Oxygen.",
			Category -> "Optics",
			Abstract -> True
		},
		EmissionWavelength -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Nanometer],
			Units -> Nanometer,
			Description -> "The emission wavelength selected by the optical filter. The emitted light from the AlphaScreen acceptor beads is captured by the primary detector photomultiplier tube (PMT).",
			Category -> "Optics",
			Abstract -> True
		},
		RetainCover -> {
			Format -> Single,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates if the plate seal or lid on the assay container was left on during reads to decrease evaporation.",
			Category -> "Optics"
		},
		ReadLocation -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> ReadLocationP,
			Description -> "The side of the microplate from which the readings were taken.",
			Category -> "Optics"
		},
		Well -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> WellP,
			Description -> "The plate well of the sample at the time of measurement.",
			Category -> "General",
			Abstract -> True
		},
		Intensity -> {
			Format -> Single,
			Class -> Real,
			Pattern :> UnitsP[RLU],
			Units -> RLU,
			Description -> "The measured luminescent intensity value in the well. The luminescent signal was generated from the acceptor AlphaScreen beads which reacted with singlet Oxygen generated from the donor AlphaScreen beads.",
			Category -> "Experimental Results",
			Abstract -> True
		},
		DetectorRangeExceeded -> {
			Format -> Single,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates if any of the recorded intensities maxed out the instrument's detector.",
			Category -> "Experimental Results"
		},
		InvalidValuesExcluded -> {
			Format -> Single,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates if any of the recorded intensities are below 0 RFU and have been deleted from the final result.",
			Category -> "Experimental Results"
		},
		OxygenLevel -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0 * Percent],
			Units -> Percent,
			Description -> "The average oxygen level inside the sample chamber during spectrum acquisition.",
			Category -> "Experimental Results"
		},
		CarbonDioxideLevel -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0 * Percent],
			Units -> Percent,
			Description -> "The average carbon dioxide level inside the sample chamber during spectrum acquisition.",
			Category -> "Experimental Results"
		}
	}
}];
