(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2025 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Data,Dissolution],{
	Description -> "Measurements of the media temperature and the rotation rates of the agitator for a given sample in the dissolution protocol.",
	CreatePrivileges -> None,
	Cache -> Session,
	Fields -> {
		DissolutionVessel -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Container,Vessel,Dissolution],
			Description -> "The vessel that was used to dissolve the sample in the medium.",
			Category -> "General"
		},
		InstrumentPosition -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> LocationPositionP,
			Description -> "The position of the instrument in which the vessel was installed in the dissolution apparatus.",
			Category -> "General"
		},
		Shaft -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Container,DissolutionShaft],
			Description -> "The shaft that was used to dissolve the sample.",
			Category -> "General"
		},
		Agitator -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Item,Agitator],
			Description -> "The agitator that was used to dissolve the sample.",
			Category -> "General"
		},
		Basket -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Container,Basket],
			Description -> "The basket that was used to dissolve the sample.",
			Category -> "General"
		},
		Sinker -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Item,Sinker],
			Description -> "The sinker that was used to dissolve the sample.",
			Category -> "General"
		},
		DosageDispensingUnit -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Container,DosageDispensingUnit],
			Description -> "The implement used in the experiment to deliver the dosage to the dissolution media at the beginning of the experiment.",
			Category -> "General"
		},
		Temperature -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Second,Celsius}],
			Units -> {Second,Celsius},
			Description -> "Temperature readings taken in the dissolution vessel over the course of the experiment.",
			Category -> "General"
		},
		RotationRate -> {
			Format -> Single,
			Class -> QuantityArray,
			Pattern :> QuantityCoordinatesP[{Second,RPM}],
			Units -> {Second,RPM},
			Description -> "Rotation rate readings taken in the dissolution vessel over the course of the experiment.",
			Category -> "General"
		},
		SamplingTimes -> {
			Format -> Multiple,
			Class -> Real,
			Units -> Minute,
			Pattern :> GreaterEqualP[0 Minute],
			Description -> "The time points at which aliquots of the dissolution medium were taken.",
			Category -> "General"
		},
		ReportFilePDF -> {
			Format -> Single,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The path to the PDF report file generated by the dissolution apparatus.",
			Category -> "General"
		}
	}
}];