(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


(* ::Subsection:: *)
(*PlotFluorescenceThermodynamics*)


DefineTests[PlotFluorescenceThermodynamics,
	{
		Example[{Basic,"Plot the data from a FluorescenceThermodynamics object:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"]],
			_?Core`Private`ValidLegendedQ
		],
		Test["Given a packet:",
			PlotFluorescenceThermodynamics[Download[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"]]],
			_?Core`Private`ValidLegendedQ
		],
		Example[{Basic,"Plot FluorescenceThermodynamics object in a link:"},
			PlotFluorescenceThermodynamics[Link[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Protocol]],
			_?Core`Private`ValidLegendedQ
		],
		Example[{Basic,"Plot FluorescenceThermodynamics data objects linked to a given FluorescenceThermodynamics protocol object:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:lYq9jRzXBmvA"][Protocol]],
			SlideView[{ValidGraphicsP[] ..}]
		],
		Test[
			"Plot only the cooling curve data:",
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],PrimaryData->CoolingCurve],
			_?ValidGraphicsQ
		],
		Test[
			"Plot only the melting curve data:",
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],PrimaryData->MeltingCurve],
			_?ValidGraphicsQ
		],
		Example[
			{Options,IncludeReplicates,"When replicates are present in the data object, they are included by default:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:lYq9jRzXBmvA"]],
			_?Core`Private`ValidLegendedQ
		],
		Example[
			{Options,IncludeReplicates,"Don't show replicates:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:lYq9jRzXBmvA"],IncludeReplicates->False],
			_?Core`Private`ValidLegendedQ
		],
		Example[
			{Options,PrimaryData,"Plot only the cooling curve:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],PrimaryData->CoolingCurve],
			_?ValidGraphicsQ
		],
		Example[
			{Attributes,"Listable","Plot several sets of Object[Data,FluorescenceThermodynamics] objects:"},
			PlotFluorescenceThermodynamics[{{Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"], Object[Data, FluorescenceThermodynamics, "id:3em6Zv9NqwzM"], Object[Data, FluorescenceThermodynamics, "id:wqW9BP4YrpvO"], Object[Data, FluorescenceThermodynamics, "id:lYq9jRzXlbVl"]}, {Object[Data, FluorescenceThermodynamics, "id:GmzlKjY5e8xE"], Object[Data, FluorescenceThermodynamics, "id:dORYzZn0XPVE"], Object[Data, FluorescenceThermodynamics, "id:Y0lXejGK3RLx"], Object[Data, FluorescenceThermodynamics, "id:3em6Zv9NqVX8"]}}],
			{_?Core`Private`ValidLegendedQ..}
		],
		Example[
			{Options,Map,"Plot each set of melting and cooling curves in separate plots by mapping over the list:"},
			PlotFluorescenceThermodynamics[{{Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"], Object[Data, FluorescenceThermodynamics, "id:3em6Zv9NqwzM"], Object[Data, FluorescenceThermodynamics, "id:wqW9BP4YrpvO"], Object[Data, FluorescenceThermodynamics, "id:lYq9jRzXlbVl"]}, {Object[Data, FluorescenceThermodynamics, "id:GmzlKjY5e8xE"], Object[Data, FluorescenceThermodynamics, "id:dORYzZn0XPVE"], Object[Data, FluorescenceThermodynamics, "id:Y0lXejGK3RLx"], Object[Data, FluorescenceThermodynamics, "id:3em6Zv9NqVX8"]}},Map->True],
			{{_?Core`Private`ValidLegendedQ..}..}
		],
		Example[
			{Options,PlotLabel,"Give a unique plot label instead of using the option names generated by default:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],PlotLabel->"Melting and Cooling Curves"],
			_?Core`Private`ValidLegendedQ
		],
		
		Example[
			{Options,Zoomable,"Toggle the interactive zoom feature:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Zoomable->False],
			g_/;ValidGraphicsQ[g]&&Length@Cases[g,ZoomableP,-1]==0
		],

		Example[
			{Options,ArrowheadSize,"Specify the size of the directional markers:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],ArrowheadSize->.02],
			_?ValidGraphicsQ
		],
				
		Example[
			{Options,OptionFunctions,"Remove the directional markers:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],OptionFunctions->{}],
			_?ValidGraphicsQ
		],
		
		Example[
			{Options,Fractions,"Overlay fractions on the cooling and melting curves:"},
			PlotFluorescenceThermodynamics[
				Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],
				Fractions->Table[{(55+5x) Celsius,(60+5x) Celsius,"A"<>ToString@x},{x,1,5}]
			],
			_?ValidGraphicsQ
		],

		Example[
			{Options,TargetUnits,"Specify the desired units:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],TargetUnits->{Fahrenheit,RFU}],
			_?ValidGraphicsQ
		],

		Example[
			{Options,Legend,"Hide the labels for each curve:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Legend->None],
			_?ValidGraphicsQ
		],

		Example[
			{Options,LegendPlacement,"Specify where the labels for each curve are displayed:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],LegendPlacement->Right],
			_?ValidGraphicsQ
		],
		
		Example[
			{Options,Boxes,"Use swatch boxes instead of lines in the legend:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Boxes->True],
			_?ValidGraphicsQ
		],
		
		Example[
			{Options,FrameLabel,"Specify the text displayed on each axis:"},
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],FrameLabel->{"Temperature","Fluorescence"}],
			_?ValidGraphicsQ
		],
			
		(* Output tests *)
		Test[
			"Setting Output to Result returns the plot:",
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Output->Result],
			_?ValidGraphicsQ,
			TimeConstraint->120
		],
		Test[
			"Setting Output to Preview returns the plot:",
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Output->Preview],
			_?ValidGraphicsQ,
			TimeConstraint->120
		],
		Test[
			"Setting Output to Options returns the resolved options:",
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Output->Options],
			ops_/;MatchQ[ops,OptionsPattern[PlotFluorescenceThermodynamics]],
			TimeConstraint->120
		],
		Test[
			"Setting Output to Tests returns a list of tests:",
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Output->Tests],
			{(_EmeraldTest|_Example)...},
			TimeConstraint->120
		],
		Test[
			"Setting Output to {Result,Options} returns the plot along with all resolved options for data object input:",
			PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Output->{Result,Options}],
			output_List/;MatchQ[First@output,_?ValidGraphicsQ]&&MatchQ[Last@output,OptionsPattern[PlotFluorescenceThermodynamics]]
		],
		Test[
			"Setting Output to Options returns all of the defined options:",
			Sort@Keys@PlotFluorescenceThermodynamics[Object[Data, FluorescenceThermodynamics, "id:jLq9jXY4oG0w"],Output->Options],
			Sort@Keys@SafeOptions@PlotFluorescenceThermodynamics,
			TimeConstraint->120
		]
	}
];
