

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Model[Maintenance, CalibrateThermocycler],{
	Description->"Definition of a set of parameters for a maintenance protocol that calibrates a thermocycler.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		CalibrationPlates -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Container, Plate],
			Description -> "Indicates the plate(s) used to calibrate the target thermocycler.",
			Category -> "General",
			Abstract -> True
		},
		BackgroundCalibrationPlate -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Container, Plate],
			Description -> "Indicates the Background calibration plate model used to calibrate the target thermocycler.",
			Category -> "General",
			Abstract -> True
		},
		ROICalibrationPlate -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Container, Plate],
			Description -> "Indicates the ROI calibration plate model used to calibrate the target thermocycler.",
			Category -> "General",
			Abstract -> True
		},
		DyeCalibrationPlates -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Container, Plate],
			Description -> "Indicates the dye calibration plate models used to calibrate the target thermocycler.",
			Category -> "General",
			Abstract -> True
		},
		NormalizationCalibrationPlates -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Container, Plate],
			Description -> "Indicates the normalization calibration plate models used to calibrate the target thermocycler.",
			Category -> "General",
			Abstract -> True
		},
		CalibrationPlateSampleRules -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> ObjectP[Model[Container, Plate]] -> ObjectP[Model[Sample]],
			Description -> "The samples that should be uploaded to each calibration plate so that it can be used in Incubate and Calibrate protocols.",
			Category -> "General",
			Abstract ->True
		},
		CalibrationReportTypes -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> CalibrationReportTypeP,
			Description -> "Types of calibration files that are generated by the instrument software.",
			Category -> "General",
			Abstract -> True
		},
		CalibrationTypes -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> qPCRCalibrationTypeP,
			Description -> "For each member of CalibrationReportTypes, the type of qPCR calibration performed by this maintenance that generates that file type.",
			Category -> "General",
			IndexMatching -> CalibrationReportTypes,
			Abstract -> True
		}
	}
}];