

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Model[Maintenance, CalibrateThermocycler],{
	Description->"Definition of a set of parameters for a maintenance protocol that calibrates a thermocycler.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		CalibrationPlates -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Container, Plate],
			Description -> "Indicates the plate(s) used to calibrate the target thermocycler.",
			Category -> "General",
			Abstract -> True
		},
		CalibrationReportTypes -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> CalibrationReportTypeP,
			Description -> "Types of calibration files that are generated by the instrument software.",
			Category -> "General",
			Abstract -> True
		}
	}
}];