(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Model[Maintenance,CalibratePlateReader],{
	Description->"Definition of a set of parameters for a maintenance protocol that calibrates the plate reader.",
	CreatePrivileges -> None,
	Cache -> Session,
	Fields -> {
		CalibrationPlate -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Container, Rack],
				Model[Container, Plate]
			],
			Description -> "Indicates the plate used to calibrate the target plate reader.",
			Category -> "General",
			Abstract -> True
		},
		CalibrationReportTypes -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> CalibrationReportTypeP,
			Description -> "Types of calibration files that are generated by the instrument software.",
			Category -> "General",
			Abstract -> True
		}
	}
}];