(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


(* ::Subsection:: *)
(*PlotCyclicVoltammetry*)


DefineUsage[PlotCyclicVoltammetry,
	{
		BasicDefinitions->{
			{
				Definition->{"PlotCyclicVoltammetry[dataObject]","plot"},
				Description->"plots the cyclic voltammetry data stored in 'dataObject'.",
				Inputs:>{
					{
						InputName->"dataObject",
						Description->"A data object generated by ExperimentCyclicVoltammetry.",
						Widget->Widget[
							Type->Object,
							Pattern:>ObjectP[Object[Data,CyclicVoltammetry]]
						],
						Expandable->False
					}
				},
				Outputs:>{
					{
						OutputName->"plot",
						Description->"Graphical representation of the data collected during a ExperimentCyclicVoltammetry protocol, specifically for the data stored in the 'dataObject'.",
						Pattern:>ValidGraphicsP[]
					}
				}
			},
			{
				Definition->{"PlotCyclicVoltammetry[protocolObject]","plots"},
				Description->"plots the cyclic voltammetry data sets stored in a CyclicVoltammetry 'protocolObject'.",
				Inputs:>{
					{
						InputName->"protocolObject",
						Description->"Protocol object from a completed ExperimentCyclicVoltammetry.",
						Widget->Widget[
							Type->Object,
							Pattern:>ObjectP[Object[Protocol,CyclicVoltammetry]]
						],
						Expandable->False
					}
				},
				Outputs:>{
					{
						OutputName->"plots",
						Description->"Graphical representation of the data collected during the ExperimentCyclicVoltammetry protocol.",
						Pattern:>ValidGraphicsP[]
					}
				}
			}
		},
		MoreInformation->{
			"More information for cyclic voltammetry plot function."
		},
		SeeAlso->{
			"ExperimentCyclicVoltammetry",
			"ExperimentCyclicVoltammetryOptions",
			"ValidExperimentCyclicVoltammetryQ",
			"PlotObject"
		},
		Author->{"scicomp", "brad", "qijue.wang"},
		Preview->True
	}
];