DefineUsage[LabelPeaks,
    {
        BasicDefinitions ->{
            {(*OVERLOAD 1*)
                Definition -> {"LabelPeaks[analysis]", "analysis"},
                Description -> "opens a graphical interface to interactively assign chemical components to peaks identified in 'analysis'.",
                Inputs:>{
                    {
                        {
                            InputName->"analysis",
                            Description->"An Object[Analysis, Peaks] whose data that will be displayed for interactive labeling.",
                            Widget->Widget[Type->Object,Pattern:>ObjectP[Object[Analysis, Peaks]]]
                        }
                    }
                },
                Outputs:>{
                    {
                        OutputName -> "analysis",
                        Description -> "An updated Object[Analysis, Peaks] wherein new labels are saved in PeakLabel and PeakAssignment fields.",
                        Pattern :> ObjectP[Object[Analysis, Peaks]]
                    }
                }
            }
            ,{(*OVERLOAD 2*)
                Definition -> {"LabelPeaks[data]", "analysis"},
                Description -> "opens an interface for peaks most recently analyzed in 'data'.",
                Inputs:>{
                    {
                        {
                            InputName->"data",
                            Description->"An Object[Data] containing analyzed data that will be displayed for interactive labeling.",
                            Widget->Widget[Type->Object,Pattern:>ObjectP[Object[Data]]]
                        }
                    }
                },
                Outputs:>{
                    {
                        OutputName -> "analysis",
                        Description -> "An updated Object[Analysis, Peaks] wherein new labels are saved in PeakLabel and PeakAssignment fields.",
                        Pattern :> ObjectP[Object[Analysis, Peaks]]
                    }
                }
            }
        },
        MoreInformation ->
            {
                "LabelPeaks constructs the interface by overlaying interactive labels on top of the graph generated by PlotObject. The list of chemicals shown in the context menu are drawn from the SamplesIn Composition field of the linked Reference of Object[Analysis].",
                "LabelPeaks[Data, ReferenceField->Field] opens an interface for the most recent peaks analysis contained in Data[Field].",
                "Chemicals picked from the context menu will be saved in PeakLabel as a String with the corresponding linked Model[Molecule] in PeakAssignment.",
                "Other Model[Molecule] objects in Constellation can be assigned to the peaks by selecting Other... in the context menu, and providing an ID or Name.",
                "Custom labels will be saved as a String to PeakLabel and as Null in PeakLabel.",
                "Accept labels updates the PeakLabel and PeakAssignment fields of Analysis with the chosen values, and returns the updated Analysis.  LabelPeaks does not create new objects in Constellation.",
                "Cancel returns Analysis without modification.",
                "LabelPeaks blocks the kernel while the graphical interface is open.  All further evaluations will be queued until the interface is closed either by pressing Accept labels or Cancel, or by Aborting the current evaluation."
            },
        SeeAlso ->
            {"AnalyzePeaks"}
        ,
        Author -> {
            "hiren.patel"
        },
        Preview->False
    }];
