(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2025 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Protocol,Dissolution],{
	Description->"A protocol for capturing the visual information and taking samples of a oral solid dosage being dissolved in a liquid media at a controlled temperature. The experiment is often used to determine the dissolution rate of a given formulation.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		(* --- General Category --- *)
		Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Instrument,DissolutionApparatus],
				Model[Instrument,DissolutionApparatus]
			],
			Description -> "The instrument stirs the input sample (oral solid dosage) in a temperature-controlled medium, taking aliquots and capturing images of the dissolution vessels at specified time points.",
			Category -> "General",
			Abstract -> True
		},
		DissolutionVessels->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Container,Vessel,Dissolution],Model[Container,Vessel,Dissolution]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the vessel used to dissolve the oral solid dosage.",
			Category->"General"
		},

		(* --- Medium Category --- *)
		Media->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[
				Object[Sample],
				Model[Sample]
			],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the buffer used to dissolve oral solid dosage. This is often chosed to mimic a biologically relevant environment.",
			Category->"Medium"
		},
		MediaVolumes->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Milliliter],
			Units->Milliliter,
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the volume of the medium used to dissolve the oral solid dosage and from which the aliquots are taken throughout the experiment.",
			Category->"Medium"
		},
		MediaTemperatures->{
			Format->Multiple,
			Class->Real,
			Units->Celsius,
			Pattern:>GreaterEqualP[0 Kelvin],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the nominal temperature of the media the instrument seeks to maintain for each vessel by using the heating jacket around the dissolution vessel. The recording of the temperature of the media during the experiment can be found in the Temperature field in the Data objects generated by the protocol.",
			Category->"Medium"
		},

		(* --- Mixing Category --- *)
		Shafts->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item,DissolutionShaft],Object[Item,DissolutionShaft]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the mixing implement used to transfer the rotational energy from the motor to the Affector that is performing the mixing of the dissolution medium.",
			Category->"Mixing"
		},
		ShaftAffectors->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item,ShaftAffector],Object[Item,ShaftAffector]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the implement used to transfer the rotational energy from the shaft to the dissolution medium.",
			Category->"Mixing"
		},
		Baskets->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item],Object[Item]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the basket attachment used to house the sample while rotating.",
			Category->"Mixing"
		},
		Paddles->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item,ShaftAffector],Object[Item,ShaftAffector]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the paddle attachment used for height calibration of the shaft position in the dissolution vessel.",
			Category->"Mixing"
		},
		HeightCheckTool->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item],Object[Item]],
			Description->"The tool used to calibrate the height of the shaft in the dissolution vessel.",
			Category->"Mixing"
		},
		DosageDispencingUnits->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item],Object[Item]],
			Description->"The tool used to dispense the oral solid dosage into the dissolution vessel.",
			Category->"Mixing",
			Developer->True
		},
		MixingStrategy->{
			Format->Single,
			Class->Expression,
			Pattern:>Alternatives[Basket,Paddle],
			Description->"The mixing strategy used to mix the dissolution medium.",
			Category->"Mixing"
		},
		MixRates->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterP[0 * RPM],
			Units->RPM,
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the frequency at which the shaft is rotated during the experiment.",
			Category->"Mixing"
		},
		MixTimes->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			IndexMatching->SamplesIn,
			Pattern:>GreaterEqualP[0 Minute],
			Description->"For each member of SamplesIn, the duration of time the oral solid dosage is mixed during which the sampling occurs at the specified SamplingTime intervals. After the intial mixing period is completed, the optional InfinityMixing is performed at a higher rotation rate to achieve the final saturation point.",
			Category->"Mixing"
		},
		Sinkers->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,Sinker],Model[Item,Sinker]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the weighted enclosure used to keep the oral solid dosage below the surface of the media during the experiment to facilitate proper mixing.",
			Category->"Mixing"
		},

		(* --- InfinityMixing Category --- *)
		InfinityMix->{
			Format->Multiple,
			Class->Boolean,
			Pattern:>BooleanP,
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, indicates if additional mixing at higher rotational speed is performed at the end of the MixTime. The Infinity Mixing period is used to achieve the final saturation point.",
			Category->"Infinity Mixing"
		},
		InfinityMixRates->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterP[0 * RPM],
			Units->RPM,
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the frequency of rotation used by the dissolution instrument at the end of the experiment to achieve final dissolution condition. This is typically set to a higher value than the MixRate to achieve the final saturation point.",
			Category->"Infinity Mixing"
		},
		InfinityMixTimes->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			Pattern:>GreaterEqualP[0 Minute],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the duration of time for which the oral solid dosage will be mixed at InfinityMixRate after MixTime to achieve the final saturation point.",
			Category->"Infinity Mixing"
		},

		(* --- Sampling Category --- *)
		SamplingTimes->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			Pattern:>GreaterEqualP[0 Minute],
			Description->"The list of the time points at which aliquots of the dissolution medium are taken.",
			Category->"Sampling"
		},
		SamplingVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the aliquot taken from the dissolution media at each SamplingTimes time point.",
			Category->"Sampling"
		},
		(*TODO: chat with Steven how to split this field into an Expression vs Link field so we can search through links for properties of the storage condition; add to style guide/make shared fields for this*)
		SamplesOutStorageCondition->{
			Format->Single,
			Class -> Expression,
			Pattern :> Alternatives[LinkP[Model[StorageCondition]], SampleStorageTypeP, Desiccated, VacuumDesiccated, RefrigeratorDesiccated, Disposal],
			Description->"The non-default condition under which the created aliquotes are stored after the protocol is completed.",
			Category->"Sampling"
		},
		ReplacementMedium->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[
				Object[Sample],
				Model[Sample]
			],
			Description->"The medium used to replace the liquid from the dissolution vessel removed for sampling each time an aliquot is taken.",
			Category->"Sampling"
		},
		(*TODO: update the option to match here*)
		SamplingPrimeVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the liquid from the dissolution vessel used to flush the sampling lines in the autosampler at each sampling time point prior to dispensing SamplesOut.",
			Category->"Sampling"
		},
		(*TODO: stopped here in review*)
		SamplingMediumRecycle->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the buffer removed for sample flushing is returned from the lines back to the dissolution vessel. Refer to the instrument diagram of the liquid flow path during the instrument operation for more details.",
			Category->"Sampling"
		},
		NumberOfSamplingWashCycles->{ (*I am not super clear what this is, but it is an instrument option in the method*)
			Format->Single,
			Class->Integer,
			Pattern:>GreaterP[0,1],
			Description->"Indicate the number of times the system wash cycle is performed between each sampling timepoint.",
			Category->"Sampling"
		},
		SamplingFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed of the syringes at which the sample medium is aliquoted.",
			Category->"Sampling"
		},
		SamplingFlushFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed of the syringes at which the flush medium is pulled.",
			Category->"Sampling"
		},
		SamplingFlushVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the medium from the dissolution vessel used to flush the sampling lines at each sampling time point.",
			Category->"Sampling"
		},
		Sampling->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if samples of the dissolution media should be taken during the experiment. These samples are commonly used to determine the amount of the sample that was dissolved in the medium at a given time point.",
			Category->"Sampling"
		},
		NumberOfSamples->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"Indicates the number of aliquots taken from the dissolution medium during the experiment.",
			Category->"Sampling"
		},
		NumberOfSamplingFlushes->{
			Format->Multiple,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"Indicate the number of times the sampling lines should be cleaned prior to sampling.",
			Category->"Sampling"
		},

		(* --- Sampling Filtration Category --- *)
		NumberOfFilterUses->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"The number of times the AutosamplerFilter is used before being replaced with a new one.",
			Category->"Sampling Filtration"
		},
		FilterSamples->{
			Format->Single,
			Class->Expression,
			Pattern:>Alternatives[InLineFiltration,AutosamplerFiltration,DualFiltration,None],
			Description->"Indicates if the sample of the dissolution media is filtered when transferring to the ContainerOut. When the samples are removed from the dissolution vessel, they are optionally filtered by an InLineFilter prior to entering the autosampler. Addditionally, the samples are optionally filtered by an AutosamplerFilter prior to the liquid being dispenced into the ContainerOut. The AutosamplerFilter is optionally changed for each aliquot while the InLineFilter is used for the duration of the experiment. Refer to the instrument diagram of the liquid flow path during the instrument operation for more details.",
			Category->"Sampling Filtration"
		},
		AutosamplerFilters->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,Filter],Model[Item,Filter]],
			Description->"The filter disks used to filter the aliquots of samples that are taken from the dissolution medium at the specified time points before the sample is dispenced into the ContainerOut. This filter is applied after the InLineFilter and is optinally changed between each aliquot.",
			Category->"Sampling Filtration"
		},
		InLineFilters->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,Filter],Model[Item,Filter]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the filter that is used to remove impurities from the samples right after they are removed from the dissolution vessel and prior to the liquid entering the autosampler for optinal secondary filtration.",
			Category->"Sampling Filtration"
		},

		(*degas*)
		Degas->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the dissolution medium should be degassed by bubbling Helium prior to the experiment.",
			Category->"Degas"
		},
		DegasTime->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Minute],
			Units->Minute,
			Description->"The duration of time the dissolution medium is degassed by bubbling Helium prior to the experiment.",
			Category->"Degas"
		},
		HeliumStartPressure -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data,Pressure],
			Description -> "The pressure at which the helium starts to bubble into the dissolution medium.",
			Category -> "Degas"
		},

		(* developer fields for movement in the procedure*)
		SinkerLoadingTuples -> {
			Format -> Multiple,
			Class -> {Link, Link},
			Pattern :> {_Link, _Link},
			Relation -> {Object[Sample], Object[Item,Sinker]},
			Description -> "A list of tuples with samples that will be placed into the sinkers for the experiment.",
			Category -> "Placements",
			Developer -> True,
			Headers -> {"Object to Place", "Destination Sinker"}
		},
		SampleLoadingTuples -> {
			Format -> Multiple,
			Class -> {Link, Link},
			Pattern :> {_Link, _Link},
			Relation -> { Object[Sample] | Object[Item,Sinker] , Object[Item]},
			Description -> "A list of tuples with samples (or sinkers containing samples) that will be placed into the dosage dispencing unit.",
			Category -> "Placements",
			Developer -> True,
			Headers -> {"Object to Place", "Destination Object"}
		},
		ContainerPlacements -> {
			Format -> Multiple,
			Class -> {Link, Link, String},
			Pattern :> {_Link, _Link, LocationPositionP},
			Relation -> {Object[Container,Vessel,Dissolution], Object[Instrument,DissolutionApparatus], Null},
			Description -> "A list of placements used to place the dissolution vessel into the instrument.",
			Category -> "Placements",
			Developer -> True,
			Headers -> {"Object to Place", "Destination Object","Destination Position"}
		},

		(*misc procedure fields*)
		RunTime -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Minute],
			Units -> Minute,
			Description -> "The estimated time for completion of the mixing part of the protocol.",
			Category -> "General",
			Developer -> True
		}
	}
}];