(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Protocol, AbsorbanceQuantification], {
	Description->"A protocol for quantifying the concentration of oligomers using absorbance measurements, Beer-Lambert's law and the compounds extinction coefficient.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {

		Buffer -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Object[Sample]
			],
			Description -> "Buffer that is used to dissolve the sample and maintain pH.",
			Category -> "Buffer Preparation"
		},
		Annealing -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> BooleanP,
			Description -> "Indicates if the source plate(s) is heated to 85\[Degree] Celsius and cooled down to room temperature before quantification.",
			Category -> "Sample Preparation",
			Abstract -> True
		},
		Dilution -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0],
			Units -> None,
			Description -> "The factor by which the samples are diluted prior to quantification. It is mathematically expressed as the final volume divided by the initial sample volume.",
			Category -> "Sample Preparation"
		},
		BufferVolume -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Micro*Liter],
			Units -> Liter Micro,
			Description -> "The volume of buffer added to each well in the read plate. If concentrated buffer is being used, this volume will be combined with buffer diluent to produce the final buffer.",
			Category -> "Sample Preparation"
		},
		QuantificationPrepNumberOfMixes -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterP[0],
			Units -> None,
			Description -> "The number of aspirate and dispense cycles repeated to mix the source and read plates.",
			Category -> "Sample Preparation"
		},
		QuantificationPrepMixVolume -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0*Micro*Liter],
			Units -> Liter Micro,
			Description -> "The volume the pipettor uses to successively aspirate and dispense the sample in the read plate, so as to thoroughly agitate and mix it.",
			Category -> "Sample Preparation"
		},
		MixSourceVolume -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Micro*Liter],
			Units -> Liter Micro,
			Description -> "The volume the pipettor uses to successively aspirate and dispense the sample in the source plate, so as to thoroughly agitate and mix it.",
			Category -> "Sample Preparation"
		},
		HeatBlock -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Instrument],
				Model[Instrument]
			],
			Description -> "The heat block used for annealing prior to the absorbance quantification measurements.",
			Category -> "Sample Preparation"
		},
		LiquidHandler -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Instrument],
				Model[Instrument]
			],
			Description -> "The liquid handler used to set up this absorbance quantification protocol.",
			Category -> "Sample Preparation"
		},
		QuantificationPrepThermalIncubation -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Protocol,IncubateOld],
			Description -> "The protocol(s) used for annealing of samples prior to quantification.",
			Category -> "Sample Preparation"
		},
		QuantificationPrepMixing -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Protocol,Incubate],Object[Protocol,ManualSamplePreparation]],
			Description -> "The protocol(s) used for mixing of samples prior to quantification.",
			Category -> "Sample Preparation"
		},
		QuantificationPrepCentrifugation -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Protocol,Centrifuge],
			Description -> "The protocol(s) used for centrifugation of samples prior to quantification.",
			Category -> "Sample Preparation"
		},
		AnnealingTimeEstimate -> {
			Format -> Single,
			Class -> Real,
			Pattern :> TimeP,
			Units -> Minute,
			Description -> "The amount of time sample annealing is expected to take.",
			Category -> "Sample Preparation"
		},
		DilutionPlates -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container]
			],
			Description -> "The plates into which input samples are transferred for dilution prior to quantification.",
			Category -> "Sample Preparation"
		},
		DilutionSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Sample],
			Description -> "The samples generated by this protocol to dilute the input samples prior to quantification.",
			Category -> "Absorbance Measurement"
		},
		QuantificationPlacements -> {
			Format -> Multiple,
			Class -> {Link, Expression},
			Pattern :> {_Link, {LocationPositionP..}},
			Relation -> {Object[Container], Null},
			Description -> "A list of deck placements directing proper positioning of labware on the liquid handler deck for the Absorbance Quantification method.",
			Category -> "Sample Preparation",
			Headers -> {"Object to Place", "Placement Tree"}
		},
		PipetteTips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Sample], (* TODO: Remove Object[Sample] here after item migration *)
				Model[Sample],
				Object[Item],
				Model[Item]
			],
			Description -> "Pipette tips used for the protocol.",
			Category -> "Sample Preparation"
		},
		TotalVolume -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterEqualP[0*Micro*Liter],
			Units -> Liter Micro,
			Description -> "The total volume in each well of the read plate prior to the absorbance measurement. This volume consists of the buffer, buffer diluent and sample.",
			Category -> "Absorbance Measurement"
		},
		QuantificationTimeEstimate -> {
			Format -> Single,
			Class -> Real,
			Pattern :> TimeP,
			Units -> Minute,
			Description -> "The amount of time quantification is expected to take.",
			Category -> "Absorbance Measurement",
			Developer -> True
		},
		PlateReader -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Instrument],
				Model[Instrument]
			],
			Description -> "The plate reader instrument used during this absorbance quantification protocol.",
			Category -> "Absorbance Measurement"
		},
		QuantificationPlates -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container]
			],
			Description -> "The plates into which input samples are transferred for quantification.",
			Category -> "Absorbance Measurement"
		},
		QuantificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Sample],
			Description -> "The samples generated by this protocol whose absorbance is measured to quantify the input samples.",
			Category -> "Absorbance Measurement"
		},
		SaveQuantificationPlates -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> BooleanP,
			Description -> "Specifies whether the quantification plate(s) will be saved for later use when the protocol is complete.",
			Category -> "Absorbance Measurement"
		},
		AbsorbanceQuantificationProgram -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Program][Protocol],
			Description -> "The program containing detailed instructions for a robotic liquid handler to dilute and quantify the input samples.",
			Category -> "Absorbance Measurement"
		},
		ProgramKey -> {
			Format -> Single,
			Class -> String,
			Pattern :> _String,
			Description -> "Specifies the program key that will define the file name for the data output in the plate reader.",
			Category -> "Absorbance Measurement",
			Developer -> True
		},
		VolumeData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data][Protocol],
			Description -> "The measured volume of the source plate after the end of the protocol.",
			Category -> "Experimental Results",
			Abstract -> True
		},
		EmptyPlateAbsorbance -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data][Protocol],
			Description -> "The absorbance data collected from the empty read plate(s).",
			Category -> "Experimental Results"
		},
		BufferAbsorbance -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data][Protocol],
			Description -> "The absorbance data collected from the read plate(s) with buffer alone.",
			Category -> "Experimental Results"
		},
		QuantificationAnalyses -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Analysis,AbsorbanceQuantification][Protocol],
			Description -> "Analyses performed to determine the concentration of samples in this protocol.",
			Category -> "Analysis & Reports"
		},
		Wavelength -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Nanometer],
			Units -> Nanometer,
			Description -> "The wavelength at which quantification analysis is performed.",
			Category -> "Analysis & Reports"
		},
		SettingsFilePaths -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The file paths for the executable files that set the measurement parameters and run the experiment.",
			Category -> "General",
			Developer -> True
		},
		AssayPlatePlacements -> {
			Format -> Multiple,
			Class -> {Link, Expression},
			Pattern :> {_Link, {LocationPositionP..}},
			Relation -> {Object[Container], Null},
			Description -> "A list of placements used to move assay plates into the plate reader.",
			Headers -> {"Object to Place", "Placement Tree"},
			Category -> "Placements",
			Developer -> True
		}
	}
}];
