(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Protocol, MeasureDissolvedOxygen], {
	Description->"A protocol for measuring the dissolved oxygen of a sample by means of a probe based meter.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {
		Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Instrument,DissolvedOxygenMeter],
				Object[Instrument,DissolvedOxygenMeter]
			],
			Description -> "The instrument used in this protocol to measure the conductivity of the sample.",
			Category -> "General",
			Abstract -> True
		},
		NumberOfReadings -> {
			Format -> Multiple,
			Class -> Integer,
			Pattern :> RangeP[1,10],
			Description ->"For each member of SamplesIn, the number of times the dissolved oxygen of each aliquot or sample is read.",
			Category -> "General",
			IndexMatching -> SamplesIn,
			Abstract -> True
		},
		Stir -> {
			Format -> Multiple,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description ->"For each member of SamplesIn, indicates if the stir paddle attached to the meter is turned on for the measurement.",
			Category -> "General",
			IndexMatching -> SamplesIn,
			Abstract -> True
		},
		DataFilePaths -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The file paths of the data file generated at the conclusion of the experiment.",
			Category -> "General",
			Developer -> True
		},
		CalibrationFilePath -> {
			Format -> Single,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The file path of the calibration file generated before meaasuring the samples.",
			Category -> "General",
			Developer -> True
		},
		(* --- Calibration --- *)
		OxygenSaturatedCalibrant->{
			Format->Single,
			Class->Link,
			Pattern:>ObjectP[{Object[Sample],Model[Sample]}],
			Relation->Object[Sample]|Model[Sample],
			Description->"The solution used to as th 100% saturated point during calibration.",
			Category->"Calibration"
		},
		ZeroOxygenCalibrant->{
			Format->Single,
			Class->Link,
			Pattern:>ObjectP[{Object[Sample],Model[Sample]}],
			Relation->Object[Sample]|Model[Sample],
			Description->"The solution used to as th 100% saturated point during calibration.",
			Category->"Calibration"
		},
		(* --- Experimental Results --- *)
		DissolvedOxygen -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> (DistributionP[Percent]|DistributionP[Milligram/Liter]),
			Description->"For each member of SamplesIn, the measured dissolved oxygen of the sample.",
			IndexMatching->SamplesIn,
			Category->"Experimental Results"
		},
		DataFile->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"The file containing the raw unprocessed data generated by the instrument.",
			Category -> "General"
		},
		(* --- Cleaning --- *)
		WasteBeaker->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[Container,Vessel]|Model[Container,Vessel],
			Description->"A vessel that will be used to catch any residual water that comes off the probe as it is washed between measurements.",
			Developer->True,
			Category->"Cleaning"
		}
	}
}];
