(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2025 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Protocol,Dissolution],{
	Description->"A protocol for capturing the visual information and taking samples of an oral solid dosage being dissolved in liquid media at a controlled temperature. The experiment is often used to determine the dissolution rate of a given formulation.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		(* --- General Category --- *)
		Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Instrument,DissolutionApparatus],
				Model[Instrument,DissolutionApparatus]
			],
			Description -> "The instrument stirs the input sample (oral solid dosage) in a temperature-controlled medium, taking aliquots and capturing images of the dissolution vessels at specified time points.",
			Category -> "General",
			Abstract -> True
		},
		DissolutionVessels->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Container,Vessel,Dissolution],Model[Container,Vessel,Dissolution]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the vessel used to dissolve the oral solid dosage.",
			Category->"General"
		},

		(* --- Medium Category --- *)
		Media->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[
				Object[Sample],
				Model[Sample]
			],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the buffer used to dissolve oral solid dosage. This is often chosed to mimic a biologically relevant environment.",
			Category->"Medium"
		},
		MediaVolumes->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Milliliter],
			Units->Milliliter,
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the volume of the medium used to dissolve the oral solid dosage.",
			Category->"Medium"
		},
		MediaTemperatures->{
			Format->Multiple,
			Class->Real,
			Units->Celsius,
			Pattern:>GreaterEqualP[0 Kelvin],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the nominal temperature of the media the instrument seeks to maintain for each vessel by using the heating jacket around the dissolution vessel. The recording of the temperature of the media during the experiment can be found in the Temperature field in the Data objects generated by the protocol.",
			Category->"Medium"
		},

		(* --- Mixing Category --- *)
		Shafts->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Container,DissolutionShaft],Object[Container,DissolutionShaft]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the mixing implement used to transfer the rotational energy from the motor to the Affector that is performing the mixing of the dissolution medium.",
			Category->"Mixing"
		},
		Agitators->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item,Agitator],Object[Item,Agitator]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the implement used to transfer the rotational energy from the shaft to the dissolution medium.",
			Category->"Mixing"
		},
		Baskets->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Container,Basket],Object[Container,Basket]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the basket attachment used to house the sample while rotating.",
			Category->"Mixing"
		},
		Paddles->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item,Agitator],Object[Item,Agitator]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the paddle attachment used for height calibration of the shaft position in the dissolution vessel.",
			Category->"Mixing"
		},
		HeightCheckTool->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item],Object[Item]],
			Description->"The tool used to calibrate the height of the shaft in the dissolution vessel.",
			Category->"Mixing"
		},
		DosageDispensingUnits->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[Container,DosageDispensingUnit],
			Description->"For each member of SamplesIn, the tool used to dispense the oral solid dosage into the dissolution vessel.",
			IndexMatching->SamplesIn,
			Category->"Mixing",
			Developer->True
		},
		MixingStrategy->{
			Format->Single,
			Class->Expression,
			Pattern:>DissolutionStrategyP,
			Description->"The type of the mixing implement used to agitate the dissolution medium during the experiment.",
			Category->"Mixing"
		},
		MixRates->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterP[0 * RPM],
			Units->RPM,
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the frequency at which the shaft is rotated during the experiment.",
			Category->"Mixing"
		},
		MixTimes->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			IndexMatching->SamplesIn,
			Pattern:>GreaterEqualP[0 Minute],
			Description->"For each member of SamplesIn, the duration of time the oral solid dosage is mixed during which the sampling occurs at the specified SamplingTime intervals. After the intial mixing period is completed, the optional InfinityMixing is performed at a higher rotation rate to achieve the final saturation point.",
			Category->"Mixing"
		},
		Sinkers->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Container,Sinker],Model[Container,Sinker]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the weighted enclosure used to keep the oral solid dosage below the surface of the media during the experiment to facilitate proper mixing.",
			Category->"Mixing"
		},

		(* --- InfinityMixing Category --- *)
		InfinityMix->{
			Format->Multiple,
			Class->Boolean,
			Pattern:>BooleanP,
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, indicates if additional mixing at higher rotational speed is performed at the end of the MixTime. The Infinity Mixing period is used to achieve the final saturation point.",
			Category->"Infinity Mixing"
		},
		InfinityMixRates->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterP[0 * RPM],
			Units->RPM,
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the frequency of rotation used by the dissolution instrument at the end of the experiment to achieve final dissolution condition. This is typically set to a higher value than the MixRate to achieve the final saturation point.",
			Category->"Infinity Mixing"
		},
		InfinityMixTimes->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			Pattern:>GreaterEqualP[0 Minute],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the duration of time for which the oral solid dosage will be mixed at InfinityMixRate after MixTime to achieve the final saturation point.",
			Category->"Infinity Mixing"
		},

		(* --- Sampling Category --- *)
		Sampling->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if samples of the dissolution media should be taken during the experiment. These samples are commonly used to determine the amount of the sample that was dissolved in the medium at a given time point.",
			Category->"Sampling"
		},
		NumberOfAliquots->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"Indicates the number of aliquots taken from the dissolution medium during the experiment.",
			Category->"Sampling"
		},
		SamplingTimes->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			Pattern:>GreaterEqualP[0 Minute],
			Description->"The list of the time points after the oral solid dosage is added to the liquid media at which aliquots of the dissolution medium are taken.",
			Category->"Sampling"
		},
		SamplingVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the aliquot taken from the dissolution media at each SamplingTimes time point.",
			Category->"Sampling"
		},
		(*Using this format we can not search through links on this field, but it should be fine as it is nto an expected use case and is more user-friendly than having 2 separate fields for expressions and links*)
		SamplesOutStorageCondition->{
			Format->Single,
			Class -> Expression,
			Pattern :> Alternatives[LinkP[Model[StorageCondition]], SampleStorageTypeP, Desiccated, VacuumDesiccated, RefrigeratorDesiccated, Disposal],
			Description->"The non-default condition under which the created aliquotes are stored after the protocol is completed.",
			Category->"Sampling"
		},
		ReplacementMedium->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[
				Object[Sample],
				Model[Sample]
			],
			Description->"The medium used to replace the liquid from the dissolution vessel removed for sampling each time an aliquot is taken in order to maintain constant volume of the media in the vessel.",
			Category->"Sampling"
		},
		SamplingPrimeVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the liquid from the dissolution vessel used to flush the sampling lines in the autosampler at each sampling time point prior to dispensing SamplesOut.",
			Category->"Sampling"
		},
		(*TODO: stopped here in review*)
		RecycleSamplingMedium->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the buffer removed for sample flushing is returned from the lines back to the dissolution vessel. Refer to the instrument diagram of the liquid flow path during the instrument operation for more details.",
			Category->"Sampling"
		},
		NumberOfSamplingWashCycles->{ (*I am not super clear what this is, but it is an instrument option in the method*)
			Format->Single,
			Class->Integer,
			Pattern:>GreaterP[0,1],
			Description->"Indicates the number of times the system wash cycle is performed between each sampling timepoint.",
			Category->"Sampling"
		},
		CollectionFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed at which the medium is aspirated during the experiment.",
			Category->"Sampling"
		},
		DispenseFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed at which the medium is dispensed during the experiment.",
			Category->"Sampling"
		},
		VesselReturnFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed at which the medium is returned to the dissolution vessel.",
			Category->"Sampling"
		},
		SamplingFlushVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the medium from the dissolution vessel used to flush the sampling lines at each sampling time point.",
			Category->"Sampling"
		},
		NumberOfSamplingFlushes->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"Indicate the number of times the sampling lines should be cleaned prior to sampling.",
			Category->"Sampling"
		},

		(* --- Sampling Filtration Category --- *)
		FilterSamples->{
			Format->Multiple,
			Class->Expression,
			Pattern:>DissolutionFiltrationTypeP,
			Description->"Indicates the types of filtration applied to the dissolution media samples during transfer to ContainerOut. Accepts a list of filtration types that are applied in sequence. CannulaTipFiltration: filters during sample transfer through cannula tip. InLineFiltration: filters immediately after removal from vessel before entering autosampler. AutosamplerFiltration: filters before dispensing into ContainerOut (changed between aliquots). Multiple types can be specified as a list (e.g., {InLineFiltration, AutosamplerFiltration}).",
			Category->"Sampling Filtration"
		},
		AutosamplerFilters->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,Filter],Model[Item,Filter]],
			Description->"The filter disks used to filter the aliquots of samples that are taken from the dissolution medium at the specified time points before the sample is dispenced into the ContainerOut. This filter is applied after the InLineFilter and is optinally changed between each aliquot.",
			Category->"Sampling Filtration"
		},
		NumberOfFilterUses->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"The number of times the AutosamplerFilter is used before being replaced with a new one.",
			Category->"Sampling Filtration"
		},
		InLineFilters->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,Filter],Model[Item,Filter]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the filter that is used to remove impurities from the samples right after they are removed from the dissolution vessel and prior to the liquid entering the autosampler for optinal secondary filtration.",
			Category->"Sampling Filtration"
		},
		CannulaTipFilters->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,Filter],Model[Item,Filter]],
			Description->"The filters attached to cannula tips used to filter samples during transfer from the dissolution vessel to the collection container.",
			Category->"Sampling Filtration"
		},
		CannulaTipFilterMaterial->{
			Format->Single,
			Class->Expression,
			Pattern:>FilterMembraneMaterialP,
			Description->"The material of the cannula tip filters used during sample transfer.",
			Category->"Sampling Filtration"
		},
		CannulaTipFilterPoreSize->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Micron],
			Units->Micron,
			Description->"The pore size of the cannula tip filters used during sample transfer.",
			Category->"Sampling Filtration"
		},
		Cannulas->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item,Cannula],Object[Item,Cannula]],
			IndexMatching->SamplesIn,
			Description->"For each member of SamplesIn, the cannula used to sample media during the dissolution experiment.",
			Category->"Sampling Filtration"
		},

		(*degas*)
		Degas->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the dissolution medium should be degassed by bubbling Helium prior to the experiment.",
			Category->"Degas"
		},
		DegasTime->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Minute],
			Units->Minute,
			Description->"The duration of time the dissolution medium is degassed by bubbling Helium prior to the experiment.",
			Category->"Degas"
		},
		HeliumStartPressure -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data,Pressure],
			Description -> "The pressure at which the helium is being pumped into the dissolution medium.",
			Category -> "Degas"
		},

		(* developer fields for movement in the procedure*)
		SampleLoadingTuples -> {
			Format -> Multiple,
			Class -> {
				Sample -> Link,
				Destination -> Link,
				DosageDispensingUnit -> Link,
				Cap -> Link
			},
			Pattern :> {
				Sample -> _Link,
				Destination -> _Link,
				DosageDispensingUnit -> _Link,
				Cap -> _Link
			},
			Relation -> {
				Sample -> Object[Sample],
				Destination -> (Object[Container,Sinker] | Object[Container,Basket]),
				DosageDispensingUnit -> Object[Container,DosageDispensingUnit],
				Cap -> Object[Item, Cap]
			},
			Description -> "A list of tuples with samples that will be placed into the sinkers (optionally), or directly into Dosage Dispencing Unit, and the cap where the DDU is being placed in for the experiment. When Baskets are used, the sample is placed into the basket and the basket is then attached to the basket holder (Affector).",
			Category -> "Placements",
			Developer -> True
		},
		ContainerPlacements -> {
			Format -> Multiple,
			Class -> {Link, Link, String},
			Pattern :> {_Link, _Link, LocationPositionP},
			Relation -> {Object[Container,Vessel,Dissolution], Object[Instrument,DissolutionApparatus], Null},
			Description -> "A list of placements used to place the dissolution vessel into the instrument.",
			Category -> "Placements",
			Developer -> True,
			Headers -> {"Object to Place", "Destination Object","Destination Position"}
		},
		AutosamplerFilterPlacements -> {
			Format -> Multiple,
			Class -> {Link, Link, String},
			Pattern :> {_Link, _Link, LocationPositionP},
			Relation -> {Object[Item,Filter], Object[Instrument,DissolutionApparatus], Null},
			Description -> "A list of placements used to place the autosampler filter into the instrument.",
			Category -> "Placements",
			Developer -> True,
			Headers -> {"Object to Place", "Destination Object","Destination Position"}
		},
		InLineFilterPlacements -> {
			Format -> Multiple,
			Class -> {Link, Link, String},
			Pattern :> {_Link, _Link, LocationPositionP},
			Relation -> {Object[Item,Filter], Object[Instrument,DissolutionApparatus], Null},
			Description -> "A list of placements used to place the in line filter into the instrument.",
			Category -> "Placements",
			Developer -> True,
			Headers -> {"Object to Place", "Destination Object","Destination Position"}
		},
		CannulaTipFilterPlacements -> {
			Format -> Multiple,
			Class -> {Link, Link},
			Pattern :> {_Link, _Link},
			Relation -> {Object[Item,Filter], Object[Item,Cannula]},
			Description -> "A list of placements used to place the cannula tip filter into the instrument.",
			Category -> "Placements",
			Developer -> True,
			Headers -> {"Object to Place", "Destination Object"}
		},
		(*misc procedure fields*)
		RunTime -> {
			Format -> Single,
			Class -> Real,
			Pattern :> GreaterP[0 Minute],
			Units -> Minute,
			Description -> "The estimated time for completion of the mixing part of the protocol.",
			Category -> "General",
			Developer -> True
		},
		Method -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Method, Dissolution],
			Description -> "The method  containing the run parameters used for the experiment.",
			Category -> "General",
			Developer -> True
		},
		MethodUpdates -> {
			Format -> Multiple,
			Class -> {
				Item -> Expression,
				Contents -> Expression
			},
			Pattern :> {
				Item -> _String,
				Contents -> Alternatives[BooleanP, _String, GreaterP[0]]
			},
			Description -> "A list of method updates to be applied to the method file to match the protocol specifications.",
			Category -> "General",
			Developer -> True
		},
		PaddlesHeightCorrect -> {
			Format -> Multiple,
			Class -> Boolean,
			Pattern :> BooleanP,
			Description -> "Indicates if the paddle height was seen to be correct.",
			Category -> "Mixing",
			Developer -> True
		},
		DissolutionVesselCaps -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Item,Cap],
			Description -> "The covers that we are using on the vessels throughout the experiment.",
			Category -> "Mixing",
			Developer -> True
		},
		DissolutionMethodCopyScriptPath -> {
			Format -> Single,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The path to the script that copies the method files to the Z drive.",
			Category -> "General",
			Developer -> True
		},
		RecordingConfigurationFilePath -> {
			Format -> Single,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The path to the recording configuration file (json with a text extension).",
			Category -> "General",
			Developer -> True
		},
		CondenserFilePath -> {
			Format -> Single,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The path to the directory where the experiment data is exported to.",
			Category -> "General",
			Developer -> True
		},
		SamplingTimesStrings -> {
			Format -> Multiple,
			Class -> String,
			Pattern :> _String,
			Description -> "The list of the time points after the oral solid dosage is added to the liquid media at which aliquots of the dissolution medium are taken. Form in which we will be displaying this in Engine to the operator.",
			Category -> "Sampling",
			Developer -> True
		},
		VesselRackPlacements -> {
			Format -> Multiple,
			Class -> {Link,Link,Expression},
			Pattern :> {_Link,_Link,LocationPositionP},
			Relation -> {(Object[Container]|Model[Container]),(Object[Container]|Model[Container]),Null},
			Description -> "List of placements of vials into autosampler rack.",
			Category -> "Placements",
			Developer -> True,
			Headers -> {"Object to Place","Destination Object","Destination Position"}
		},
		ProtocolKey -> {
			Format -> Single,
			Class -> String,
			Pattern :> _String,
			Description -> "The key of the protocol. Used for naming of the protocol in the software.",
			Category -> "General",
			Developer -> True
		},
		SampleReservoirs -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Container,Vessel],Model[Container,Vessel]],
			Description -> "The containers that are used to store the individial tablets during the experiment.",
			Category -> "General",
			Developer -> True
		},
		SampleAmounts -> {
			Format -> Multiple,
			Class -> Integer,
			Pattern :> GreaterP[0,1],
			Description -> "The amounts of the samples that are being weighed and transported around the lab. It is quite sad that we need this field, but there is no other way to put in amount to the Transfer subprotocol we will genearate.",
			Category -> "General",
			Developer -> True
		},
		WasteContainer -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container]
			],
			Description -> "The container used to collect waste during cleaning of the gas lines.",
			Category -> "General",
			Developer -> True
		},
		SecondaryWasteContainer -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container]
			],
			Description -> "The container used to collect waste during cleaning of the cannulas at the end of the protocol.",
			Category -> "General",
			Developer -> True
		},
		CannulaConnections -> {
			Format -> Multiple,
			Class -> {Link, String, Link, String},
			Pattern :> {_Link, ConnectorNameP, _Link, ConnectorNameP},
			Relation -> {Object[Instrument], Null, Object[Item,Cannula], Null},
			Description -> "The connection information for the cannulas to the isntrument. This is used to install the new cannulas used in the experiment.",
			Headers -> {"Instrument", "Instrument Port", "Cannula", "Cannula Port"},
			Category -> "General",
			Developer -> True
		},
		CannulaDisconnections -> {
			Format -> Multiple,
			Class -> {Link, String, Link, String},
			Pattern :> {_Link, ConnectorNameP, _Link, ConnectorNameP},
			Relation -> {Object[Instrument], Null, Object[Item,Cannula], Null},
			Description -> "The disconnection information for the cannulas from the isntrument. This is used to remove the cannulas from the instrument that were installed prior to this experiment.",
			Headers -> {"Instrument", "Instrument Port", "Cannula", "Cannula Port"},
			Category -> "General",
			Developer -> True
		},
		ReplacementCannulas -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Item,Cannula],
			Description -> "The cannulas that are being installed on the instrument. If we are using less than 6 positions on the instrument in the protocol, this field will have all 6 cannulas regardless since we want to have identical cannulas in all positions.",
			Category -> "General",
			Developer -> True
		}
	}
}];