(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Protocol,Vapro5600Training],{
	Description->"A protocol object for measuring the osmolality of a sample solution.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		Instrument->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Instrument,Osmometer],Model[Instrument,Osmometer]],
			Description->"The instrument used to measure the osmolality of a sample.",
			Category->"General"
		},
		Sample->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Sample],Model[Sample]],
			Description->"The solution that the operator will measure the osmolality of.",
			Category->"General"
		},
		SampleVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 Microliter],
			Units->Microliter,
			Description->"The volume of solution to be pipetted into the instrument.",
			Category->"General"
		},
		Repeatability->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 Milli Mole/Kilogram],
			Units->Milli Mole/Kilogram,
			Description->"The maximum threshold for the operator's repeatability on the most recent measurements to be graded as a pass.",
			Category->"General"
		},
		RepeatabilityNumberOfMeasurements->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[2,1],
			Description->"The number of most recent readings from which the repeatability will be calculated.",
			Category->"General"
		},
		MaxNumberOfMeasurements->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[2,1],
			Description->"The maximum total number of measurements that will be performed in this protocol before aborting.",
			Category->"General"
		},
		CurrentRepeatability->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 Milli Mole/Kilogram],
			Units->Milli Mole/Kilogram,
			Description->"The standard deviation of measurements within the current assessment period.",
			Category->"General"
		},
		AttemptNumber->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"The number of measurements that have been taken on the sample, including the current sample.",
			Category->"General",
			Developer->True
		},
		Pipette->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Instrument],Model[Instrument]],
			Description->"The pipette used to measure out and transfer the sample solution into the instrument.",
			Category->"General"
		},
		PipetteTips->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item],Object[Item]],
			Description->"The pipette tip used with the pipette to transfer sample solution into the instrument.",
			Category->"General"
		},
		InoculationPapers->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Object[Item,InoculationPaper],Model[Item,InoculationPaper]],
			Description->"The paper that is saturated with sample solution on sample loading and holds the solution during measurement.",
			Category->"General"
		},
		Tweezers->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[Model[Item],Object[Item]],
			Description->"The tweezers used to load the sample paper into the sample holder.",
			Category->"General"
		},
		(*Experiment Results*)
		DataFiles->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"The processed experiment data generated by the osmometer instrument.",
			Category->"Experimental Results"
		},
		RawDataFiles->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"The raw experiment data generated by the osmometer instrument, in proprietary format.",
			Category->"Experimental Results",
			Developer->True
		},
		DataFilePath->{
			Format->Multiple,
			Class->String,
			Pattern:>FilePathP,
			Description->"The file path of the folder containing the data files generated at the conclusion of the experiment.",
			Category->"Experimental Results",
			Developer->True
		},
		FileNames->{
			Format->Multiple,
			Class->String,
			Pattern:>_String,
			Description->"The name to use for the datafiles when generated by the instrument.",
			Category->"Experimental Results",
			Developer->True
		},
		FileName->{
			Format->Single,
			Class->String,
			Pattern:>_String,
			Description->"The name to use when saving the data for the current measurement.",
			Category->"Experimental Results",
			Developer->True
		},
		Passing->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the repeatability of the last measurements (RepeatabilityNumberOfMeasurements) is better than the specified threshold (Repeatability).",
			Category->"Experimental Results",
			Developer->True
		}
	}
}];