(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Model[Instrument,LiquidHandler,AcousticLiquidHandler],{
	Description->"The model for an acoustic liquid handler instrument designed for transferring liquid samples by using acoustic energy.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{

		(* ---------- Instrument Specifications ---------- *)
		CouplingFluid->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Model[Sample],
			Description->"The type of coupling fluid used by the acoustic liquid handler to allow sound waves to travel between the transducer and the source plate.",
			Category->"Instrument Specifications",
			Abstract->True
		},
		MinCouplingFluidVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0*Liter],
			Units->Liter*Milli,
			Description->"The minimum volume of the coupling fluid in the reservoir required by the acoustic liquid handler to dispense the samples accurately.",
			Category->"Instrument Specifications"
		},
		Chiller -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Model[Part,Chiller][Instrument],
			Description -> "The model of chiller is used to cool this model of acoustic liquid handler.",
			Category -> "Instrument Specifications"
		},
		(* ---------- Compatibility ---------- *)
		MinPlateHeight->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0*Meter],
			Units->Meter,
			Description->"The minimum plate height of the destination plate that is supported by the acoustic liquid handler.",
			Category->"Compatibility"
		},

		MaxPlateHeight->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0*Meter],
			Units->Meter,
			Description->"The maximum plate height of the destination plate that is supported by the acoustic liquid handler.",
			Category->"Compatibility"
		},

		MaxFlangeHeight->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0*Meter],
			Units->Meter,
			Description->"The maximum height of the flange surrounding the destination plate bottom that is supported by the destination plate grabber on the acoustic liquid handler.",
			Category->"Compatibility"
		},

		(* ---------- Operating Limits ---------- *)
		DropletTransferResolution->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0*Liter],
			Units->Liter*Nano,
			Description->"The lowest volume that the acoustic liquid handler can transfer based on the droplet size generated by acoustic ejection.",
			Category->"Operating Limits",
			Abstract->True
		},
		MinHumidity->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0*Percent],
			Units->Percent,
			Description->"The minimum relative humidity at which the acoustic liquid handler can perform the sample transfer.",
			Category->"Operating Limits"
		},
		MaxHumidity->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0*Percent],
			Units->Percent,
			Description->"The maximum relative humidity at which the acoustic liquid handler can perform the sample transfer.",
			Category->"Operating Limits"
		},

		(* labware definition *)
		DefaultLabwareDefinitionFilePath -> {
			Format -> Single,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The file path of the folder containing the labware definition file which contains the plate's parameters.",
			Category -> "General",
			Developer -> True
		}
	}
}];
