(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Instrument, Diffractometer], {
	Description -> "A diffractometer instrument that analyzes the structure of a material from the scattering of radiation.",
	CreatePrivileges -> None,
	Cache -> Download,
	Fields -> {
		Chiller -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Part,Chiller][Instrument],
				Object[Instrument,HeatExchanger][IntegratedInstrument]
			],
			Description -> "The recirculating water chiller used to cool this diffractometer .",
			Category -> "Instrument Specifications"
		},
		RadiationType -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], RadiationType]],
			Pattern :> DiffractionRadiationTypeP,
			Description -> "The type of radiation used by this instrument to irradiate the samples to and obtain a diffraction pattern.",
			Category -> "Instrument Specifications"
		},
		AnodeMaterial -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], AnodeMaterial]],
			Pattern :> MetalP,
			Description -> "The material of which the anode that generates the radiation is made.",
			Category -> "Instrument Specifications"
		},
		Wavelength -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], Wavelength]],
			Pattern :> GreaterP[0*Angstrom],
			Description -> "The wavelength of the radiation generated by this instrument.",
			Category -> "Instrument Specifications"
		},
		DiffractionDetector -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], DiffractionDetector]],
			Pattern :> OpticalDetectorP,
			Description -> "The type of detector available to measure the diffraction pattern.",
			Category -> "Instrument Specifications"
		},
		DetectorPixelSize -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], DetectorPixelSize]],
			Pattern :> GreaterEqualP[0*Micrometer],
			Description -> "The size of each pixel on the detector.",
			Category -> "Instrument Specifications"
		},
		DetectorDimensions -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], DetectorDimensions]],
			Pattern :> {GreaterEqualP[0*Millimeter], GreaterEqualP[0*Millimeter]},
			Headers -> {"Detector Width", "Detector Height"},
			Description -> "Dimensions of the active detector's surface for this instrument.",
			Category -> "Instrument Specifications"
		},
		ExperimentTypes -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], ExperimentTypes]],
			Pattern :> {XRDExperimentTypeP..},
			Description -> "Indicates the types of x-ray experiments that may be performed on this experiment.",
			Category -> "Instrument Specifications"
		},

		(* --- Operating Limits --- *)
		MinTheta -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], MinTheta]],
			Pattern :> GreaterEqualP[-180*AngularDegree],
			Description -> "The minimum theta scattering angle that can be measured by this instrument.",
			Category -> "Operating Limits"
		},
		MaxTheta -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], MaxTheta]],
			Pattern :> GreaterEqualP[-180*AngularDegree],
			Description -> "The maximum theta scattering angle that can be measured by this instrument.",
			Category -> "Operating Limits"
		},
		MinDetectorDistance -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], MinDetectorDistance]],
			Pattern :> GreaterEqualP[0*Millimeter],
			Description -> "The minimum distance the detector can be from the sample.",
			Category -> "Operating Limits"
		},
		MaxDetectorDistance -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], MaxDetectorDistance]],
			Pattern :> GreaterEqualP[0*Millimeter],
			Description -> "The maximum distance the detector can be from the sample.",
			Category -> "Operating Limits"
		},
		MaxBeamPower -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], MaxBeamPower]],
			Pattern :> GreaterEqualP[0*Watt],
			Description -> "The maximum power this instrument uses to generate the diffracting radiation.",
			Category -> "Operating Limits"
		},
		MaxVoltage -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], MaxVoltage]],
			Pattern :> GreaterEqualP[0*Volt],
			Description -> "The maximum voltage this instrument uses to generate the diffracting radiation.",
			Category -> "Operating Limits"
		},
		MaxCurrent -> {
			Format -> Computable,
			Expression :> SafeEvaluate[{Field[Model]}, Download[Field[Model], MaxCurrent]],
			Pattern :> GreaterEqualP[0*Ampere],
			Description -> "The maximum current this instrument uses to generate the diffracting radiation.",
			Category -> "Operating Limits"
		}
	}
}];
