(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Instrument,LiquidHandler,AcousticLiquidHandler],{
	Description->"An acoustic liquid handler instrument designed for transferring liquid samples by using acoutstic energy.",
	CreatePrivileges->None,
	Cache->Download,
	Fields->{

		(* ---------- Instrument Specifications ---------- *)

		CouplingFluid->{
			Format->Computable,
			Expression:>SafeEvaluate[{Field[Model]},Download[Field[Model],CouplingFluid]],
			Pattern:>ObjectReferenceP[Model[Sample]],
			Description->"The type of coupling fluid used by the acoustic liquid handler to allow sound waves to travel between the transducer and the source plate.",
			Category->"Instrument Specifications",
			Abstract->True
		},
		MinCouplingFluidVolume->{
			Format->Computable,
			Expression:>SafeEvaluate[{Field[Model]},Download[Field[Model],MinCouplingFluidVolume]],
			Pattern:>GreaterP[0*Liter],
			Description->"The minimum volume of the coupling fluid in the reservoir required by the acoustic liquid handler to dispense the samples accurately.",
			Category->"Instrument Specifications"
		},
		Chiller -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Part,Chiller][Instrument],
			Description -> "The chiller used to maintain the temperature of this acoustic liquid handler.",
			Category -> "Instrument Specifications"
		},
		(* ---------- Compatibility ---------- *)

		MinPlateHeight->{
			Format->Computable,
			Expression:>SafeEvaluate[{Field[Model]},Download[Field[Model],MinPlateHeight]],
			Pattern:>GreaterP[0*Meter],
			Description->"The minimum plate height of the destination plate that is supported by the acoustic liquid handler.",
			Category->"Compatibility"
		},

		MaxPlateHeight->{
			Format->Computable,
			Expression:>SafeEvaluate[{Field[Model]},Download[Field[Model],MaxPlateHeight]],
			Pattern:>GreaterP[0*Meter],
			Description->"The maximum plate height of the destination plate that is supported by the acoustic liquid handler.",
			Category->"Compatibility"
		},

		MaxFlangeHeight->{
			Format->Computable,
			Expression:>SafeEvaluate[{Field[Model]},Download[Field[Model],MaxFlangeHeight]],
			Pattern:>GreaterP[0*Meter],
			Description->"The maximum height of the flange surrounding the destination plate bottom that is supported by the acoustic liquid handler.",
			Category->"Compatibility"
		},

		(* ---------- Operating Limits ---------- *)

		DropletTransferResolution->{
			Format->Computable,
			Expression:>SafeEvaluate[{Field[Model]},Download[Field[Model],DropletTransferResolution]],
			Pattern:>GreaterP[0*Liter],
			Description->"The lowest volume that the acoustic liquid handler can transfer based on the droplet size generated by acoustic ejection.",
			Category->"Operating Limits",
			Abstract->True
		},
		MinHumidity->{
			Format->Computable,
			Expression:>SafeEvaluate[{Field[Model]},Download[Field[Model],MinHumidity]],
			Pattern:>GreaterP[0*Percent],
			Description->"The minimum relative humidity at which the acoutstic liquid handler can perform the sample transfer.",
			Category->"Operating Limits"
		},
		MaxHumidity->{
			Format->Computable,
			Expression:>SafeEvaluate[{Field[Model]},Download[Field[Model],MaxHumidity]],
			Pattern:>GreaterP[0*Percent],
			Description->"The maximum relative humidity at which the acoutstic liquid handler can perform the sample transfer.",
			Category->"Operating Limits"
		},

		(* labware definition *)
		LabwareDefinitionFilePath -> {
			Format -> Single,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The file path of the folder containing the labware definition file which contains the plate's parameters.",
			Category -> "General",
			Developer -> True
		}
	}
}];
