(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Analysis], {
	Description->"An analysis performed on a scientific data set.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {

		Name -> {
			Format -> Single,
			Class -> String,
			Pattern :> _String,
			Description -> "A unique name for this analysis.",
			Category -> "Organizational Information",
			Abstract -> True
		},
		Author -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[User],
			Description -> "The person who ran the analysis.",
			Category -> "Organizational Information"
		},
		DeveloperObject -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> BooleanP,
			Description -> "Indicates that this object is being used for test purposes only and is not supported by standard SLL features.",
			Category -> "Organizational Information",
			Developer -> True
		},
		UnresolvedOptions -> {
			Format -> Single,
			Class -> Compressed,
			Pattern :> {_Rule...},
			Units -> None,
			Description -> "The initial options entered into the analysis function that generated this object, along with the default values for any unspecified options.",
			Category -> "General"
		},
		ResolvedOptions -> {
			Format -> Single,
			Class -> Compressed,
			Pattern :> {_Rule...},
			Units -> None,
			Description -> "The final options used by the analysis function, after automatic options have been determined from the input and unresolved options.",
			Category -> "General"
		},
		Reference -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Qualification,PipettingLinearity][FittingAnalysis],
				Object[Data, AbsorbanceSpectroscopy][AbsorbanceSpectrumPeaksSource],
				Object[Data, AbsorbanceSpectroscopy][QuantificationAnalyses],
				Object[Data, AbsorbanceSpectroscopy][SmoothingAnalyses],
				Object[Data, AbsorbanceIntensity][QuantificationAnalyses],
				Object[Data, AgaroseGelElectrophoresis][SampleElectropherogramPeaksAnalyses],
				Object[Data, AgaroseGelElectrophoresis][MarkerElectropherogramPeaksAnalyses],
				Object[Data, AgaroseGelElectrophoresis][PostSelectionPeaksAnalyses],
				Object[Data, AgaroseGelElectrophoresis][SmoothingAnalyses],
				Object[Data, Appearance, Colonies][ColonyAnalysis],
				Object[Data, Appearance, Colonies][ImageExposureAnalyses],
				Object[Data, MeltingCurve][MeltingAnalyses],
				Object[Data, MeltingCurve][FluorescenceSpectraAnalyses],
				Object[Data, MeltingCurve][AggregationAnalyses],
				Object[Data, MeltingCurve][ThermalShiftAnalyses],
				Object[Data, BioLayerInterferometry][QuantitationAnalysis],
				Object[Data, BioLayerInterferometry][KineticsAnalysis],
				Object[Data, BioLayerInterferometry][BinningAnalysis],
				Object[Data, BioLayerInterferometry][DetectionLimitAnalysis],
				Object[Data, CapillaryGelElectrophoresisSDS][LadderAnalyses],
				Object[Data, CapillaryGelElectrophoresisSDS][SmoothingAnalyses],
				Object[Data, CapillaryGelElectrophoresisSDS][PeaksAnalyses],
				Object[Data, CapillaryGelElectrophoresisSDS][RelativeMigrationPeaksAnalyses],
				Object[Data, CapillaryGelElectrophoresisSDS][FitAnalyses],
				Object[Data, CapillaryIsoelectricFocusing][SmoothingAnalyses],
				Object[Data, CapillaryIsoelectricFocusing][PeaksAnalyses],
				Object[Data, CapillaryIsoelectricFocusing][FitAnalyses],
				Object[Data, Chromatography][StandardAnalyses],
				Object[Data, Chromatography][FractionPickingAnalysis],
				Object[Data, Chromatography][ConductancePeaksAnalyses],
				Object[Data, Chromatography][AbsorbancePeaksAnalyses],
				Object[Data, Chromatography][SecondaryAbsorbancePeaksAnalyses],
				Object[Data, Chromatography][Absorbance3DPeaksAnalyses],
				Object[Data, Chromatography][FluorescencePeaksAnalyses],
				Object[Data, Chromatography][SecondaryFluorescencePeaksAnalyses],
				Object[Data, Chromatography][TertiaryFluorescencePeaksAnalyses],
				Object[Data, Chromatography][QuaternaryFluorescencePeaksAnalyses],
				Object[Data, Chromatography][ScatteringPeaksAnalyses],
				Object[Data, Chromatography][FIDResponsePeaksAnalyses],
				Object[Data, Chromatography][ChargePeaksAnalyses],
				Object[Data, Chromatography][SmoothingAnalyses],
				Object[Data, Chromatography][pHPeaksAnalyses],
				Object[Data, Chromatography][RefractiveIndexPeaksAnalysis],
				Object[Data, Chromatography][MultiAngleLightScatteringAnalyses],
				Object[Data, Chromatography][DynamicLightScatteringAnalyses],
				Object[Data, ChromatographyMassSpectra][IonAbundance3DPeaksAnalyses],
				Object[Data, ChromatographyMassSpectra][IonAbundancePeaksAnalyses],
				Object[Data, ChromatographyMassSpectra][MassSpectrumPeaksAnalyses],
				Object[Data, ChromatographyMassSpectra][AbsorbancePeaksAnalyses],
				Object[Data, ChromatographyMassSpectra][Absorbance3DPeaksAnalyses],
				Object[Data, ChromatographyMassSpectra][DownsamplingAnalyses],
				Object[Data, ChromatographyMassSpectra][SmoothingAnalyses],
				Object[Data, CircularDichroism][SmoothingAnalyses],
				Object[Data, CircularDichroism][StructureQuantificationAnalyses],
				Object[Data, ContactAngle][AdvancingContactAngleFitAnalyses],
				Object[Data, ContactAngle][RecedingContactAngleFitAnalyses],
				Object[Data, DifferentialScanningCalorimetry][HeatingCurvePeaksAnalyses],
				Object[Data, DifferentialScanningCalorimetry][SmoothingAnalyses],
				Object[Data, DNASequencing][SequenceAnalyses],
				Object[Data, DynamicFoamAnalysis][BubbleRadiusAnalyses],
				Object[Data, FlowCytometry][FlowCytometryAnalyses],
				Object[Data, FluorescenceKinetics][RateFittingAnalyses],
				Object[Data, FluorescencePolarizationKinetics][RateFittingAnalyses],
				Object[Data, LuminescenceKinetics][RateFittingAnalyses],
				Object[Data, FluorescenceSpectroscopy][EmissionSpectrumPeaksAnalyses],
				Object[Data, FluorescenceSpectroscopy][ExcitationSpectrumPeaksAnalyses],
				Object[Data, FluorescenceSpectroscopy][SmoothingAnalyses],
				Object[Data, FragmentAnalysis][PeaksAnalyses],
				Object[Data, ICPMS][MassSpectrumPeaksAnalyses],
				Object[Data, LuminescenceSpectroscopy][PeaksAnalyses],
				Object[Data, LuminescenceSpectroscopy][SmoothingAnalyses],
				Object[Data, MeltingCurve][InitialIntensityPeaksAnalyses],
				Object[Data, MeltingCurve][FinalIntensityPeaksAnalyses],
				Object[Data, MeltingCurve][InitialMassPeaksAnalyses],
				Object[Data, MeltingCurve][FinalMassPeaksAnalyses],
				Object[Data, MeltingCurve][DynamicLightScatteringAnalyses],
				Object[Data, FluorescenceThermodynamics][MeltingAnalyses],
				Object[Data, MassSpectrometry][MassSpectrumPeaksAnalyses],
				Object[Data, MassSpectrometry][SmoothingAnalyses],
				Object[Data, MeltingPoint][MeltingAnalyses],
				Object[Data, Microscope][AdjustmentAnalyses],
				Object[Data, Microscope][CellCountAnalyses],
				Object[Data, Microscope][MicroscopeOverlay],
				Object[Data, ImageCells][CellCountAnalyses],
				Object[Data, ImageCells][MicroscopeOverlay],
				Object[Data, Nephelometry][QuantificationAnalyses],
				Object[Data, NMR][NMRSpectrumPeaksAnalyses],
				Object[Data, NMR][SmoothingAnalyses],
				Object[Data, NMR2D][NMRSpectrumPeaksAnalyses],
				Object[Data, PAGE][ImageExposureAnalyses],
				Object[Data, PAGE][LanePeaksAnalyses],
				Object[Data, PAGE][LadderAnalyses],
				Object[Data, PAGE][SmoothingAnalyses],
				Object[Data, qPCR][QuantificationCycleAnalyses],
				Object[Data, qPCR][MeltingPointAnalyses],
				Object[Data, TotalProteinDetection][FitSourceSpectra],
				Object[Data, TotalProteinDetection][MassSpectrumPeaksAnalyses],
				Object[Data, TotalProteinDetection][LadderAnalyses],
				Object[Data, TLC][LanePeaksAnalyses],
				Object[Data, TLC][SmoothingAnalyses],
				Object[Data, Volume][QuantificationAnalyses],
				Object[Data, Western][FitSourceSpectra],
				Object[Data, Western][MassSpectrumPeaksAnalyses],
				Object[Data, Western][LadderAnalyses],
				Object[Data, Western][SmoothingAnalyses],
				Object[Analysis, MeltingPoint][TopBaseline],
				Object[Analysis, MeltingPoint][BottomBaseline],
				Object[Analysis, MeltingPoint][Thermodynamics],
				Object[Analysis, QuantificationCycle][CopyNumberAnalyses],
				Object[Analysis, QuantificationCycle][StandardCurveAnalyses],
				Object[Analysis, Composition][StandardCurveFitAnalyses],
				Object[Analysis, Ladder][StandardFit],
				Object[Analysis, Thermodynamics][Fit],
				Object[Analysis, Fit][ParallelLineAnalyses],
				Object[Analysis, Colonies][ColonyGrowthAnalysis],
				Object[Data, XRayDiffraction][StructureAnalyses],
				Object[Data, XRayDiffraction][DiffractionPeaksAnalyses],
				Object[Data, XRayDiffraction][SmoothingAnalyses],
				Object[Data, IRSpectroscopy][AbsorbanceSpectrumPeaksSource],
				Object[Data, IRSpectroscopy][SmoothingAnalyses],
				Object[Protocol, FlowCytometry][CompensationMatrixAnalyses],
				Object[Protocol, TotalProteinQuantification][QuantificationAnalyses],
				Object[Protocol, CoulterCount][SystemSuitabilityAnalyses],
				Object[Protocol, CoulterCount][RepeatedSystemSuitabilityAnalyses],
				Object[Data, CoulterCount][DiameterPeaksAnalyses],
				Object[Data,CircularDichroism][CircularDichroismPeaksAnalysis],
				Object[Data,DynamicLightScattering][MassDistributionAnalyses],
				Object[Data,DynamicLightScattering][IntensityDistributionAnalyses],
				Object[Data,DynamicLightScattering][NumberDistributionAnalyses],
				Object[Data,DynamicLightScattering][DynamicLightScatteringAnalyses],
				Object[DesignOfExperiment][DesignOfExperimentAnalyses],
				Object[Protocol, ThermalShift][DynamicLightScatteringLoadingAnalyses],
				Object[Protocol, DynamicLightScattering][DynamicLightScatteringLoadingAnalyses],
				Object[Data, DifferentialScanningCalorimetry][Analyses],
				Object[Data,WettedLength][FitAnalyses],
        Object[Data, MeltingPoint][MeltingAnalyses],
				Object[Data, ChromatographyMassSpectra],
				Object[Data, MassSpectrometry],
				Object[Protocol, LCMS],
				Object[Protocol, MassSpectrometry],
				Object[Protocol, MassSpectrometry][CalibrationSmoothingAnalyses],
				Object[Protocol, MassSpectrometry][CalibrationPeakAnalyses]
			],
			Description -> "The objects containing the source data used in this analysis.",
			Category -> "General",
			Abstract -> True
		},
		ReferenceField -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> ECL`FieldP[Output->Short],
			Description -> "The field in the Reference object containing the source data.",
			Category -> "General",
			Abstract -> True
		},
		LegacyID -> {
			Format -> Single,
			Class -> String,
			Pattern :> _String,
			Description -> "The SLL2 ID for this Object, if it was migrated from the old data store.",
			Category -> "Migration Support",
			Developer -> True
		}
	}
}];
