(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Analysis,CriticalMicelleConcentration], {
	Description->"Analysis of the data from a surface tension measurement conducted on surfactant samples at varying concentrations.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {
		SamplesIn -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Sample],
			Description -> "The samples for which the critical micelle concentration is being quantified.",
			Category -> "General"
		},
		AliquotSamples->{
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Sample],
			Description -> "For each member of SamplesIn, the samples (SamplesIn or diluted samples) which had their surface tensions measured.",
			IndexMatching->SamplesIn,
			Category -> "General"
		},
		DilutionFactors->{
			Format->Multiple,
			Class->Real,
			Pattern:>RangeP[0,1],
			IndexMatching-> AliquotSamples,
			Description-> "For each member of AliquotSamples, a measure of the portion of the AssaySample that is comprised of the SampleIn. For example, an DilutionFactor of 0.02 indicates that the SampleIn was diluted 50-fold to create the AliquotSample.",
			Category -> "General"
		},
		TargetMolecules->{
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> IdentityModelTypeP,
			Description -> "The target molecule for which the AliquotSamples concentration was calculated.",
			Category -> "General"
		},
		Concentrations-> {
			Format -> Multiple,
			Class -> VariableUnit,
			Pattern :> (GreaterEqualP[0 Molar]| GreaterEqualP[0 Gram/Liter]|GreaterEqualP[0 MassPercent]|GreaterEqualP[0 Percent]),
			Units->None,
			Description -> "For each member of the dilution curve, the concentrations of the sample that were measured.",
			Category -> "General"
		},
		AssayData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Data, SurfaceTension][CriticalMicelleConcentrationAnalyses]
			],
			Description -> "Any primary data generated by the input data or protocol.",
			Category -> "Experimental Results"
		},
		SurfaceTensions->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterEqualP[0*Milli Newton/ Meter],
			Units->Milli Newton/ Meter,
			Description->"For each member of AliquotSamples, the surface tension values measured by ExperimentMeasureSurfaceTension.",
			IndexMatching->AliquotSamples,
			Category -> "Experimental Results"
		},
		Temperatures -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterP[0*Kelvin],
			Units -> Celsius,
			Description -> "For each member of AliquotSamples, the temperatures (as measured inside the instrument) at which the measurements were acquired.",
			IndexMatching->AliquotSamples,
			Category -> "Experimental Results"
		},
		SurfacePressures-> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[-100 Milli Newton/Meter],
			Units -> Milli Newton/Meter,
			Description -> "For each member of AliquotSamples, the decrease in surface pressures measured.",
			Category -> "Analysis & Reports",
			Abstract -> True
		},
		PreMicellarFit -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Analysis,Fit][PredictedValues],
			Description -> "Function used to fit surface tension data points at concentrations below the critical micelle concentration.",
			Category -> "Analysis & Reports"
		},
		PostMicellarFit -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Analysis,Fit][PredictedValues],
			Description -> "Function used to fit surface tension data points at concentrations above the critical micelle concentration.",
			Category -> "Analysis & Reports"
		},
		CriticalMicelleConcentration->{
			Format -> Single,
			Class -> VariableUnit,
			Pattern :> (GreaterP[0*Molar]|GreaterP[0 Gram/Liter]|RangeP[0 Percent,100 Percent]|RangeP[0 MassPercent, 100 MassPercent]),
			Units->None,
			Description-> "The concentration of surfactants above which micelles form and all additional surfactants added to the system go to micelles. This is the concentration where increasing the concentration of the sample stops decreasing the surface tension.",
			Category->"Analysis & Reports"
		},
		ApparentPartitioningCoefficient->{
			Format -> Single,
			Class -> VariableUnit,
			Pattern :> (GreaterP[0/Molar]|GreaterP[0 Liter/Gram]|GreaterP[0 /Percent]|GreaterP[0 /MassPercent]),
			Units->None,
			Description-> "An apparent partitioning coefficient used to quantify partitioning the air-water interface. This is the inverse of the concentration where increasing the concentration of the sample starts decreasing the surface tension.",
			Category->"Analysis & Reports"
		},
		SurfaceExcessConcentration->{
			Format->Single,
			Class->Real,
			Pattern :> GreaterP[0*Mole/Meter^2],
			Units->Mole/Meter^2,
			Description-> "The amount of surfactant adsorbed at the air water interface per surface area. This is calculated by taking the negative of the slope of the concentration dependent region of a surface tension vs. log of concentration graph divided by the temperature the measurement was taken at and the ideal gas constant.",
			Category->"Analysis & Reports"
		},
		CrossSectionalArea->{
			Format->Single,
			Class->Real,
			Pattern :> GreaterP[0*Meter^2],
			Units->Meter^2,
			Description-> "The area of the surfactant molecule at the surface. This is calculated by taking the inverse of the SurfaceExcessConcentration and the Avogadro constant.",
			Category->"Analysis & Reports"
		},
		MaxSurfacePressure->{
			Format->Single,
			Class->Real,
			Pattern :> GreaterEqualP[-100 Milli Newton/Meter],
			Units->Milli Newton/Meter,
			Description-> "The largest surface pressure of the dilutions. This is also the difference between the surface tension of the diluent and the surface tension of the most concentrated dilution.",
			Category->"Analysis & Reports"
		}
	}
}];
