(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

(* CustomerMetrics generated Daily eg. from DateObject[{2024,06,01,00,00,00}] to DateObject[{2024,06,01,23,59,59}] via a ManifoldJob and keeps track of customer metrics information *)
DefineObjectType[Object[Report, CustomerMetrics], {
	Description->"A report of the different metrics for usage by a financing team of the ECL system at a given time interval. This information is then used in generating summary figures that are sent to target recipients for review or additional analysis.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {
		FinancingTeam -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Team, Financing][CustomerMetrics],
			Description -> "The team to which this report belongs which provide tracking of metrics for usage of the ECL system at a given time interval.",
			Category -> "Team Information"
		},
		StartDate -> {
			Format -> Single,
			Class -> Date,
			Pattern :> _?DateObjectQ,
			Description -> "The start date of the date range over which customer metrics is gathered and stored.",
			Category -> "Organizational Information"
		},
		EndDate -> {
			Format -> Single,
			Class -> Date,
			Pattern :> _?DateObjectQ,
			Description -> "The end date of the date range over which customer metrics is gathered and stored.",
			Category -> "Organizational Information"
		},
		
		(*Protocol Metrics*)
		ProtocolLog -> {
			Format -> Multiple,
			Class -> {Date, Link, Expression, Date, Date, Date, Real, Link,Expression},
			Pattern :> {_?DateObjectQ, _Link, Alternatives[ParentProtocol,Subprotocol], _?DateObjectQ, _?DateObjectQ, _?DateObjectQ, GreaterEqualP[0 Hour], _Link,_?TypeQ},
			Relation -> {Null, Object[Protocol], Null, Null, Null, Null, Null, Object[User],Null},
			Units -> {None, None, None, None, None, None, Hour, None,None},
			Headers -> {"Date", "Protocol", "Protocol Classification", "Date Enqueued", "Date Started","Date Completed","Queue Time", "User","Protocol Type"},
			Description -> "A log of parent protocols and subprotocols completed within the period between StartDate and EndDate over which the customer metrics is gathered and stored.",
			Category -> "Protocol Metrics"
		},
		DataLog -> {
			Format -> Multiple,
			Class -> {Date, Link, Link, Expression, Date, Link,Expression},
			Pattern :> {_?DateObjectQ, _Link, _Link, Alternatives[ParentProtocol,Subprotocol], _?DateObjectQ, _Link,_?TypeQ},
			Relation -> {Null, Object[Data], Object[Protocol], Null, Null, Object[User],Null},
			Headers -> {"Date", "Data", "Protocol", "Protocol Classification", "Date Created", "User","Data Type"},
			Description -> "A log of data generated by the completed parent protocols and subprotocols within the period between the StartDate and the EndDate over which the customer metrics is gathered and stored.",
			Category -> "Protocol Metrics"
		},
		SamplesLog -> {
			Format -> Multiple,
			Class -> {Date, Link, Link, Expression, Link},
			Pattern :> {_?DateObjectQ, _Link, _Link, Alternatives[ParentProtocol,Subprotocol], _Link},
			Relation -> {Null, Object[Sample], Object[Protocol], Null, Object[User]},
			Headers -> {"Date", "Sample", "Protocol", "Protocol Classification", "User"},
			Description -> "A log of samples processed or generated by the completed parent protocols and subprotocols within the period between the StartDate and the EndDate over which the customer metrics is gathered and stored.",
			Category -> "Protocol Metrics"
		},
		ProtocolSummaryLog -> {
			Format -> Multiple,
			Class -> {Date, Integer, Integer, Integer, Integer, Integer, Integer},
			Pattern :> {_?DateObjectQ, GreaterEqualP[0,1], GreaterEqualP[0,1], GreaterEqualP[0,1], GreaterEqualP[0,1], GreaterEqualP[0,1], GreaterEqualP[0,1]},
			Headers -> {"Date", "Parent Protocols", "Subprotocols", "Data Objects (Parent Protocols)", "Data Objects (Subprotocols)","Samples (Parent Protocols)", "Samples (Subprotocols)" },
			Description -> "A summary log of protocols completed, data generated and samples processed within the period between the StartDate and the EndDate over which the customer metrics is gathered and stored.",
			Category -> "Protocol Metrics"
		},
		
		QueueTimesSummary -> {
			Format -> Multiple,
			Class -> {Date, Integer, Integer, Integer, Integer},
			Pattern :> {_?DateObjectQ, GreaterEqualP[0,1], GreaterEqualP[0,1], GreaterEqualP[0,1], GreaterEqualP[0,1]},
			Headers -> {"Date", "Less than 5 Hours", "5 - 10 Hours", "10 - 24 Hours", "Greater Than 24 Hour"},
			Description -> "A daily log of number of protocols per queue time range within the period between the StartDate and the EndDate over which the customer metrics is gathered and stored.",
			Category -> "Protocol Metrics"
		},
		
		(*Thread Utilization Metrics*)
		TeamThreadUtilizationLog-> {
			Format -> Multiple,
			Class -> {Date, Integer, Integer},
			Pattern :> {_?DateObjectQ, GreaterEqualP[0,1], GreaterEqualP[0,1]},
			Headers -> {"Date", "Max Available Thread Count", "InUse Thread Count"},
			Description-> "A daily log of assigned maximum available threads and inuse threads within the period between the StartDate and the EndDate over which the customer metrics is gathered and stored.",
			Category -> "Thread Utilization Metrics"
		},
		
		UserThreadUtilizationLog-> {
			Format -> Multiple,
			Class -> {Date, Link,String, Integer},
			Pattern :> {_?DateObjectQ, _Link,_String, GreaterEqualP[0,1]},
			Relation-> {Null, Object[User],Null, Null},
			Headers -> {"Date", "User","User Name", "InUse Thread Count"},
			Description-> "A daily log of inuse threads per user within the period between the StartDate and the EndDate over which the customer metrics is gathered and stored.",
			Category -> "Thread Utilization Metrics"
		},
		
		(*User Activity Metrics*)
		UserHourLog-> {
			Format -> Multiple,
			Class -> {Date, Link,String, Real},
			Pattern :> {_?DateObjectQ, _Link,_String, GreaterEqualP[0 Hour]},
			Units -> {None, None, None,Hour},
			Relation-> {Null, Object[User],Null, Null},
			Headers -> {"Date", "User","User Name", "Hours of Activity"},
			Description-> "A daily log of users and corresponding hours of activity within the period between the StartDate and the EndDate over which the customer metrics is gathered and stored.",
			Category -> "User Activity Metrics"
		},
		UserUtilizationSummary-> {
			Format -> Multiple,
			Class -> {Date, Link,String, Integer, Integer, Integer,Integer, Integer, Integer, Real},
			Pattern :> {_?DateObjectQ, _Link,_String, GreaterEqualP[0,1], GreaterEqualP[0,1], GreaterEqualP[0,1],GreaterEqualP[0,1], GreaterEqualP[0,1], GreaterEqualP[0,1], GreaterEqualP[0 Hour]},
			Units -> {None, None, None,None, None, None,None, None,None, Hour},
			Relation-> {Null, Object[User],Null, Null, Null, Null,Null, Null, Null, Null},
			Headers -> {"Date", "User", "User Name", "Number of Parent Protocols", "Number of Data Objects (Parent Protocols)", "Number of Samples (Parent Protocols)","Number of Total Protocols", "Number of Total Data Objects", "Number of Total Samples", "Labor Hours" },
			Description-> "A daily log of users and generated work, including protocols completed, data gathered and samples processed, within the period between the StartDate and the EndDate over which the customer metrics is gathered and stored.",
			Category -> "User Activity Metrics"
		},
		
		(* Instruments *)
		InstrumentLog-> {
			Format -> Multiple,
			Class -> {Date, Link,Link, Link, Link, Real, Integer, Integer,Real,Expression},
			Pattern :> {_?DateObjectQ, _Link,_Link, _Link, _Link, GreaterEqualP[0 Hour], GreaterEqualP[0,1], GreaterEqualP[0,1],GreaterEqualP[0 USD],{GreaterEqualP[0 Meter]..}},
			Units -> {None, None, None,None, None, Hour, None, None,USD,None},
			Relation-> {Null, Object[Instrument], Model[Instrument],Object[Resource,Instrument], Object[Protocol], Null, Null, Null,Null,Null},
			Headers -> {"Date", "Instrument","Instrument Model", "Resource", "Root Protocol", "Time InUse", "Number Of Qualifications","Number of Maintenances","Purchase Cost","Dimensions" },
			Description-> "A log of instrument and relevant usage information per day within the date range over which the customer metrics is gathered and stored. Time InUse indicates the time instrument is in use for the particular instrument Resource of the individual log. Number of Qualifications and Number of Maintenances indicate the number performed to date of the Log Date.",
			Category -> "Instrument Usage Metrics"
		}
	}
}];
