(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


(* ::Subsection::Closed:: *)
(*PlotMeltingPoint*)


DefineUsage[PlotMeltingPoint,
	{
		BasicDefinitions -> {

	    {
	      Definition -> {"PlotMeltingPoint[meltingObject]", "plot"},
	      Description -> "plots the melting curve and melting temperature that is found in the melting point analysis 'meltingObject'.",
	      Inputs :> {
	        {
	          InputName -> "meltingObject",
	          Description -> "The analysis object which is the output of melting point analysis performed with AnalyzeMeltingPoint.",
	          Widget -> Widget[Type->Object, Pattern :> ObjectP[Object[Analysis,MeltingPoint]]]
	        }
	      },
	      Outputs :> {
	        {
						OutputName -> "plot",
						Description -> "Plot of melting curves and melting temperatures generated by melting point analysis.",
						Pattern :> ValidGraphicsP[]
					}
	      }
	    },

			{
				Definition -> {"PlotMeltingPoint[meltingObjects]", "plot"},
				Description -> "plots the melting curves and melting temperatures that are found in the melting point analyses 'meltingObjects'.",
				Inputs :> {
					{
						InputName -> "meltingObjects",
						Description -> "The analysis objects which is the output of melting point analysis performed with AnalyzeMeltingPoint.",
						Widget -> Adder[
							Widget[Type->Object,Pattern:>ObjectP[Object[Analysis,MeltingPoint]],PatternTooltip->"A single analysis object."]
						]
					}
				},
				Outputs :> {
					{
						OutputName -> "plot",
						Description -> "Plot of melting curves and melting temperatures generated by melting point analysis.",
						Pattern :> ValidGraphicsP[]
					}
				}
			}

		},

		SeeAlso -> {
	    "AnalyzeMeltingPoint",
	    "AnalyzeThermodynamics",
			"AnalyzeFit",
	    "PlotThermodynamics",
			"PlotFit"
		},
		Author -> {"dirk.schild", "amir.saadat", "brad", "jonathan", "catherine"},
		Sync->Automatic,
		Preview->True
	}
];