(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


(* ::Subsubsection:: *)
(*PlotDNASequencingAnalysis*)


DefineUsage[PlotDNASequencingAnalysis,
  {
    BasicDefinitions -> {
      {
        Definition -> {"PlotDNASequencingAnalysis[sequenceAnalysis]", "plot"},
        Description -> "plots identified bases and quality values from a DNA sequencing analysis alongside the electropherograms the analysis was conducted on.",
	 			Inputs :> {
	 				{
	 					InputName -> "sequenceAnalysis",
	 					Description -> "A DNA sequencing analysis object (generated by AnalyzeDNASequencing), packet, or link.",
	 					Widget -> Adder[
							Widget[Type->Object, Pattern:>ObjectP[Object[Analysis,DNASequencing]]]
						]
	 				}
	 			},
        Outputs :> {
          {
            OutputName -> "plot",
            Description -> "A plot showing electropherogram peaks, the bases assigned to them, and the quality values of the assignments.",
            Pattern :> ValidGraphicsP[]
          }
        }
      }
  	},
		MoreInformation->{
			"PlotDNASequencingAnalysis inherits options from EmeraldListLinePlot. Please see the documentation for EmeraldListLinePlot for more examples."
		},
    SeeAlso -> {
      "AnalyzeDNASequencing",
      "AnalyzeDNASequencingOptions",
			"EmeraldListLinePlot"
    },
    Author -> {"scicomp", "brad", "kevin.hou"},
		Preview->True
  }
];