(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


(* ::Subsubsection::Closed:: *)
(*PlotThermodynamics*)


DefineUsage[PlotThermodynamics,
{
	BasicDefinitions -> {

    {
      Definition -> {"PlotThermodynamics[thermoObject]", "vantHoffPlot"},
      Description -> "generates a van't Hoff plot using the points and fit generated by thermodynamics analysis in 'thermoObject'.",
      Inputs :> {
        {
          InputName -> "thermoObject",
          Description -> "The analysis object which is the output of thermodynamics analysis performed with AnalyzeThermodynamics.",
          Widget -> Widget[Type->Object, Pattern :> ObjectP[Object[Analysis,Thermodynamics]]]
        }
      },
      Outputs :> {
        {
					OutputName -> "vantHoffPlot",
					Description -> "Plot of the van't Hoff fit generated by thermodynamic analysis.",
					Pattern :> ValidGraphicsP[]
				}
      }
    },

		{
			Definition -> {"PlotThermodynamics[thermoObjects]", "vantHoffPlots"},
			Description -> "generates van't Hoff plots using the points and fit generated by thermodynamic analyses in 'thermoObjects'.",
			Inputs :> {
				{
					InputName -> "thermoObjects",
					Description -> "The analysis objects which is the output of smoothing analysis performed with AnalyzeThermodynamics.",
					Widget -> Adder[
						Widget[Type->Object,Pattern:>ObjectP[Object[Analysis,Thermodynamics]],PatternTooltip->"A single analysis object."]
					]
				}
			},
			Outputs :> {
				{
					OutputName -> "vantHoffPlots",
					Description -> "Plots of the van't Hoff fit generated by thermodynamic analyses.",
					Pattern :> ValidGraphicsP[]
				}
			}
		}

	},

	SeeAlso -> {
    "AnalyzeThermodynamics",
    "AnalyzeFit",
		"AnalyzeMeltingPoint",
    "PlotFit",
		"PlotMeltingPoint"
	},
	Author -> {
		"amir.saadat",
		"brad",
		"jonathan",
		"catherine"
	},
	Sync->Automatic,
	Preview->True
}];
