(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


(* ::Section:: *)
(*Source Code*)


(* ::Subsection:: *)
(*AdvancedAnalyzePeaks*)


(* ::Subsubsection:: *)
(*Options*)


Error::InvalidManualPeaks = "Option value `1` for ManualPeaks contains overlapping spans. Please ensure that none of the ranges in this option specification overlap.";

(* ---------------------- *)
(* --- DEFINE OPTIONS --- *)
(* ---------------------- *)



DefineOptions[AdvancedAnalyzePeaks,
	Options :> {
			{
				OptionName -> ReferenceField,
				Default -> Automatic,
				Description -> "Specify which field in data object will be analyzed for peaks.",
				AllowNull -> True,
				Category -> "General",
				Widget -> With[
					{
						referenceFieldP=Alternatives[
							(* 2D Fields *)
							AbsorbanceSpectrum,Chromatogram,SecondaryChromatogram,
							Absorbance,SecondaryAbsorbance,Conductance,Scattering,
							Fluorescence,SecondaryFluorescence,TertiaryFluorescence,QuaternaryFluorescence,
							Conductance,ConductivityFlowCellTemperature,pH,pHFlowCellTemperature,
							MultiAngleLightScattering22Degree,MultiAngleLightScattering28Degree,MultiAngleLightScattering32Degree,MultiAngleLightScattering38Degree,
							MultiAngleLightScattering44Degree,MultiAngleLightScattering50Degree,MultiAngleLightScattering57Degree,MultiAngleLightScattering64Degree,
							MultiAngleLightScattering72Degree,MultiAngleLightScattering81Degree,MultiAngleLightScattering90Degree,MultiAngleLightScattering99Degree,
							MultiAngleLightScattering108Degree,MultiAngleLightScattering117Degree,MultiAngleLightScattering126Degree,MultiAngleLightScattering134Degree,
							MultiAngleLightScattering141Degree,MultiAngleLightScattering147Degree,
							DynamicLightScattering,RefractiveIndex,ExcitationSpectrum,EmissionSpectrum,
							Intensity,MassSpectrum,NMRSpectrum,OptimalLaneImage,OptimalLaneIntensity,
							LowExposureLaneIntensity,MediumLowExposureLaneIntensity,MediumHighExposureLaneIntensity,HighExposureLaneIntensity,
							LowExposureLadderIntensity,MediumLowExposureLadderIntensity,MediumHighExposureLadderIntensity,HighExposureLadderIntensity,
							LowExposureGelImage,MediumLowExposureGelImage,MediumHighExposureGelImage,HighExposureGelImage,
							LowExposureGelImageFile,MediumLowExposureGelImageFile,MediumHighExposureGelImageFile,HighExposureGelImageFile,
							LaneImage,BlankedDiffractionPattern,SampleElectropherogram,MarkerElectropherogram,
							PostSelectionElectropherogram,HeatingCurves,MolarHeatingCurves,FIDResponse,Charge,
							InitialIntensityDistribution,InitialMassDistribution,FinalIntensityDistribution,FinalMassDistribution,
							AbsorbanceSpectrum,AbsorbanceDifferenceSpectrum,CircularDichroismAbsorbanceSpectrum,CircularDichroismSpectrum,
							UnblankedAbsorbanceSpectrum,UnblankedAbsorbanceDifferenceSpectrum,UnblankedCircularDichroismAbsorbanceSpectrum,
							IntensityDistribution,MassDistribution,IonAbundance,ProcessedUVAbsorbanceData,RelativeMigrationData,
							(* 3D Fields *)
							Absorbance3D,Chromatogram3D,IonAbundance3D
						]
					},
					Alternatives[
						Widget[Type->Enumeration,Pattern:>referenceFieldP],
						Adder[Widget[Type->Enumeration,Pattern:>referenceFieldP]]
					]
				]
			},
			{
				OptionName -> DataSetTransformationFunction,
				Default -> Null,
				Description -> "A pure function or quantity function which will be mapped over the resolved raw input data prior to peak-picking.",
				AllowNull -> True,
				Category -> "General",
				Widget -> Alternatives[
					"Scale"->Widget[Type->Enumeration,Pattern:>LogLinear|LinearLog|LogLog],
					"f[{x,y}]"->Widget[Type->Expression,Pattern:>_Function|_QuantityFunction,Size->Line,PatternTooltip->"A pure function of the form f[{x,y}]->{x2,y2}."],
					"f[x],g[y]"->{
						"X transform"->Alternatives[
							"Function"->Widget[Type->Expression,Pattern:>_Function|_QuantityFunction,Size->Line,PatternTooltip->"A pure function of the form f[x]->x2."],
							Widget[Type->Enumeration,Pattern:>Alternatives[None]]
						],
						"Y transform"->Alternatives[
							"Function"->Widget[Type->Expression,Pattern:>_Function|_QuantityFunction,Size->Line,PatternTooltip->"A pure function of the form f[y]->y2."],
							Widget[Type->Enumeration,Pattern:>Alternatives[None]]
						]
					}
				]
			},
			{
				OptionName -> Wavelength,
				Default -> Automatic,
				Description -> "Specify which slice of data to look at when working with 3D Chromatography data. Automatic will default to the minimum wavelength.",
				AllowNull -> True,
				Category -> "Data Slicing",
				Widget -> Widget[Type -> Quantity, Pattern :> GreaterEqualP[0 Nanometer, Nanometer], Units -> Alternatives[Nanometer]]
			},
			{
				OptionName -> Name,
				Default -> Null,
				Description -> "Name to be used for the Object[Analysis, Peaks] generated by this analysis.",
				AllowNull -> True,
				Category -> "General",
				Widget -> Widget[Type->String,Pattern:>_String, Size -> Line]
			},
		
			{
				OptionName -> DataSliceDimension,
				Default -> Automatic,
				Description -> "Specify which dimension(s) of 3+ dimensional input data should be held constant to produce two-dimensional slice(s) for peak-picking.",
				ResolutionDescription -> "Given 3+ dimensional input data, the default slice dimension(s) will be determined based on the input data type and the ReferenceField option. For 2D input data, this option defaults to Null.",
				AllowNull -> True,
				Category -> "Data Slicing",

				Widget -> Alternatives[
					Adder[Alternatives[Widget[Type->Enumeration, Pattern:>Alternatives[ElutionTime,MassToChargeRatio,Wavelength]],
						"Index"->Widget[Type->Number,Pattern:>GreaterP[0,1]]]],
					Widget[Type->Enumeration,	Pattern:>Alternatives[ElutionTime,MassToChargeRatio,Wavelength]],
					"Index"->Widget[Type->Number,Pattern:>GreaterP[0,1]]]

			},
			{
				OptionName -> DataSlice,
				Default -> Automatic,
				Description -> "For each member of DataSliceDimension, a single value or range of values over which the input data should be sliced to produce two-dimensional {x,y} data for peak picking.",
				ResolutionDescription -> "Given 3+ dimensional input data, the default slice will be determined based on the input data type and the ReferenceField option. For 2D input data, this option defaults to Null.",
				AllowNull -> True,
				Category -> "Data Slicing",
				Widget->Alternatives[
					"Single Value"->Widget[Type->Expression, Pattern:>UnitsP[], Size->Word],
					"Range"->Widget[Type -> Expression, Pattern :> Alternatives[UnitsP[];;UnitsP[], {UnitsP[];;UnitsP[]..}], Size -> Line]
				]
			},
			{
				OptionName -> SliceReductionFunction,
				Default -> Automatic,
				Description -> "For each member of DataSliceDimension, determines how the DataSlice should be flattened along that dimension if data is sliced over a range of values.",
				ResolutionDescription->"Given 3+ dimensional input data, defaults to Mean. For 2D input data, this option defaults to Null.",
				AllowNull -> True,
				Category -> "Data Slicing",
				Widget ->
					Alternatives[
						Widget[Type->Enumeration, Pattern:>Alternatives[Total,Mean,Max,Min]],
						Adder[Widget[Type->Enumeration, Pattern:>Alternatives[Total,Mean,Max,Min]]]
					]
			},
			{
				OptionName -> SliceReferencePeaks,
				Default -> Automatic,
				Description -> "A peaks analysis object which will be used as reference for slicing 3+ dimensional data. Peak positions will be used to set the default values for the DataSliceDimension and DataSlice options.",
				ResolutionDescription -> "Given 3+ dimensional input data, defaults to None. For 2D input data, this option defaults to Null.",
				AllowNull->True,
				Category -> "Data Slicing",
				Widget -> Alternatives[
					Widget[Type->Enumeration, Pattern:>Alternatives[None]],
					Widget[Type->Object, Pattern:>ObjectP[Object[Analysis,Peaks]]]
				]
			},
			
			{
				OptionName -> PeakThresholds,
				Default -> {},
				Description -> "Specify threshold regions for peak searching.",
				AllowNull -> True,
				Category -> "Method",
				Widget -> Alternatives[
					Adder[{
						"Domain" -> Widget[Type->Expression, Size->Word, Pattern:>{_?NumericQ,_?NumericQ}],
						"Height" -> Widget[Type->Number, Pattern:>RangeP[-Infinity, Infinity]]
					}],
					Widget[Type -> Enumeration, Pattern :> Alternatives[{}]]
				]
			},
			{
				OptionName -> UnknownPeakThresholds,
				Default -> {},
				Description -> "Specify threshold regions for finding unexpected peaks. ",
				AllowNull -> True,
				Category -> "Method",
				Widget -> Alternatives[
					Adder[{
						"Domain" -> Widget[Type->Expression, Size->Word, Pattern:>{_?NumericQ,_?NumericQ}],
						"Height" -> Widget[Type->Number, Pattern:>RangeP[-Infinity, Infinity]]
					}],
					Widget[Type -> Enumeration, Pattern :> Alternatives[{}]]
				]
			},
			{
				OptionName -> ManualPeaks,
				Default -> {},
				Description -> "Manually specify the left and right boundaries of a peak, including its baseline.",
				AllowNull -> True,
				Category -> "Method",
				Widget -> Alternatives[Adder[Alternatives[
					Adder[{
						"Left" -> Widget[Type->Expression, Size->Word, Pattern:>{_?NumericQ,_?NumericQ}],
						"Right" -> Widget[Type->Expression, Size->Word, Pattern:>{_?NumericQ,_?NumericQ}],
						"Assignment" -> (Widget[Type -> String, Size -> Word, Pattern :> _String] |
							Widget[Type -> Object, Pattern :> ObjectP[Model[Molecule]]])
					}],
					Widget[Type -> Enumeration, Pattern :> Alternatives[{}]]
				]], Widget[Type -> Enumeration, Pattern :> Alternatives[{}]]]
			},
			{
				OptionName -> ExpectedPeaks,
				Default -> {},
				Description -> "Specify the name and location of expected peaks.",
				AllowNull -> True,
				Category -> "Method",
				Widget -> Alternatives[
					Adder[{
						"Assignment" -> (Widget[Type -> String, Size -> Word, Pattern :> _String] |
							Widget[Type -> Object, Pattern :> ObjectP[Model[Molecule]]]),
						"ApexPosition" -> Widget[Type->Number, Pattern:>RangeP[-Infinity,Infinity]],
						"ApexDomain" -> Widget[Type->Expression, Size->Word, Pattern:>{_?NumericQ,_?NumericQ}]
					}],
					Widget[Type -> Enumeration, Pattern :> Alternatives[{}]]
				]
			},
		AnalysisPreviewSymbolOption,
		OutputOption,
		UploadOption
	}
];
