

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Container, ExtractionCartridge], {
	Description->"A disposable cartridge used in solid phase extraction or flash chromatography.",
	CreatePrivileges->None,
	Cache->Download,
	Fields -> {

(*		SeparationMode -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, SeparationMode /. Download[Field[Model]]],*)
(*			Pattern :> SeparationModeP,*)
(*			Description -> "The type of SPE for which this cartridge is suitable.",*)
(*			Category -> "Model Information",*)
(*			Abstract -> True*)
(*		},*)
(*		PackingMaterial -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, PackingMaterial /. Download[Field[Model]]],*)
(*			Pattern :> ColumnPackingMaterialP,*)
(*			Description -> "Chemical composition of the packing material in the cartridge.",*)
(*			Category -> "Physical Properties",*)
(*			Abstract -> True*)
(*		},*)
(*		FunctionalGroup -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, FunctionalGroup /. Download[Field[Model]]],*)
(*			Pattern :> SolidPhaseExtractionFunctionalGroupP,*)
(*			Description -> "The functional group displayed on the cartridge's stationary phase.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		ParticleSize -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, ParticleSize /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*Meter*Micro],*)
(*			Description -> "The average size of the particles that make up the packing material.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		PoreSize -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, PoreSize /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*Angstrom],*)
(*			Description -> "The average size of the pores within the cartridge's packing material.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		BedWeight -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, BedWeight /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*Gram],*)
(*			Description -> "The weight of the packing material in the cartridge.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		CasingMaterial -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, CasingMaterial /. Download[Field[Model]]],*)
(*			Pattern :> PlasticP,*)
(*			Description -> "The material that the exterior of the cartridge which houses the packing material is composed of.",*)
(*			Category -> "Physical Properties",*)
(*			Abstract -> True*)
(*		},*)
(*		InletFilterMaterial -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, InletFilterMaterial /. Download[Field[Model]]],*)
(*			Pattern :> FilterMembraneMaterialP,*)
(*			Description -> "The material of the inlet filter through which the sample must travel before reaching the stationary phase.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		InletFilterThickness -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, InletFilterThickness /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*Meter],*)
(*			Description -> "The thickness of the inlet filter through which the sample must travel before reaching the stationary phase.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		InletFilterPoreSize -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, InletFilterPoreSize /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*Micro*Meter],*)
(*			Description -> "The size of the pores in the inlet filter through which the sample must travel before reaching the stationary phase.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		OutletFilterMaterial -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, OutletFilterMaterial /. Download[Field[Model]]],*)
(*			Pattern :> FilterMembraneMaterialP,*)
(*			Description -> "The material of the outlet filter through which the sample must travel before exiting the cartridge.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		OutletFilterThickness -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, OutletFilterThickness /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*Meter],*)
(*			Description -> "The thickness of the outlet filter through which the sample must travel before exiting the cartridge.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		OutletFilterPoreSize -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, OutletFilterPoreSize /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*Micro*Meter],*)
(*			Description -> "The size of the pores in the outlet filter through which the sample must travel before exiting the cartridge.",*)
(*			Category -> "Physical Properties"*)
(*		},*)
(*		MinPressure -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, MinPressure /. Download[Field[Model]]],*)
(*			Pattern :> GreaterEqualP[0*PSI],*)
(*			Description -> "The minimum pressure to which the cartridge can be exposed without becoming damaged.",*)
(*			Category -> "Operating Limits"*)
(*		},*)
(*		MaxPressure -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, MaxPressure /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*PSI],*)
(*			Description -> "The maximum pressure to which the cartridge can be exposed without becoming damaged.",*)
(*			Category -> "Operating Limits"*)
(*		},*)
(*		NominalFlowRate -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, NominalFlowRate /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[(0*(Liter*Milli))/Minute],*)
(*			Description -> "The nominal flow rate at which the cartridge performs.",*)
(*			Category -> "Operating Limits"*)
(*		},*)
(*		MinFlowRate -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, MinFlowRate /. Download[Field[Model]]],*)
(*			Pattern :> GreaterEqualP[(0*(Liter*Milli))/Minute],*)
(*			Description -> "The minimum flow rate at which the cartridge performs.",*)
(*			Category -> "Operating Limits"*)
(*		},*)
(*		MaxFlowRate -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, MaxFlowRate /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[(0*(Liter*Milli))/Minute],*)
(*			Description -> "The maximum flow rate at which the cartridge performs.",*)
(*			Category -> "Operating Limits"*)
(*		},*)
(*		Diameter -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, Diameter /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*Milli*Meter],*)
(*			Description -> "The internal diameter of the cartridge body.",*)
(*			Category -> "Dimensions & Positions"*)
(*		},*)
(*		CartridgeLength -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, CartridgeLength /. Download[Field[Model]]],*)
(*			Pattern :> GreaterP[0*Milli*Meter],*)
(*			Description -> "The internal length of the cartridge body.",*)
(*			Category -> "Dimensions & Positions"*)
(*		},*)
(*		InletConnectionType -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, InletConnectionType /. Download[Field[Model]]],*)
(*			Pattern :> ReactionVesselConnectionTypeP,*)
(*			Description -> "The type of fitting needed to plumb the flow system into the cartridge.",*)
(*			Category -> "Compatibility"*)
(*		},*)
(*		OutletConnectionType -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, OutletConnectionType /. Download[Field[Model]]],*)
(*			Pattern :> ReactionVesselConnectionTypeP,*)
(*			Description -> "The type of fitting needed to plumb the cartridge back into the flow system.",*)
(*			Category -> "Compatibility"*)
(*		},*)
(*		IncompatibleSolvents -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, IncompatibleSolvents /. Download[Field[Model]]],*)
(*			Pattern :> {ObjectReferenceP[{Model[Sample, StockSolution], Model[Sample]}]..},*)
(*			Description -> "Chemicals that are incompatible for use with this cartridge.",*)
(*			Category -> "Compatibility",*)
(*			Abstract -> True*)
(*		},*)
(*		MinpH -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, MinpH /. Download[Field[Model]]],*)
(*			Pattern :> RangeP[0, 14],*)
(*			Description -> "The minimum pH to which the cartridge can be exposed without becoming damaged.",*)
(*			Category -> "Compatibility"*)
(*		},*)
(*		MaxpH -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, MaxpH /. Download[Field[Model]]],*)
(*			Pattern :> RangeP[0, 14],*)
(*			Description -> "The maximum pH to which the cartridge can be exposed without becoming damaged.",*)
(*			Category -> "Compatibility"*)
(*		},*)
(*		HoldUpVolume -> {*)
(*			Format -> Computable,*)
(*			Expression :> SafeEvaluate[{Field[Model]}, HoldUpVolume /. Download[Field[Model]]],*)
(*			Pattern :> GreaterEqualP[0 Milliliter],*)
(*			Description -> "The volume of retained liquid that cannot be recovered from the cartridge.",*)
(*			Category -> "Operating Limits"*)
(*		}*)
	}
}];
