(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Calibration, Thermocycler],{
	Description->"A calibration performed on an instrument or model",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		InstrumentCalibrated -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Instrument, Thermocycler][BackgroundCalibrationLog, 2],
				Object[Instrument, Thermocycler][RegionOfInterestCalibrationLog, 2],
				Object[Instrument, Thermocycler][UniformityCalibrationLog, 2],
				Object[Instrument, Thermocycler][DyeCalibrationLogs, CalibrationReport]
			],
			Description -> "The thermocycler instrument that the calibration was performed on.",
			Category -> "General"
		},
		ReportFilePDF -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[EmeraldCloudFile],
			Description -> "The file containing the report generated by the instrument of the calibration.",
			Category -> "Quality Assurance"
		},
		CalibrationDate ->{
			Format->Single,
			Class->Expression,
			Pattern:>_DateObject,
			Description->"The date and time the calibration occurred.",
			Category->"General"
		},
		ReportGenerationDate -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> _DateObject,
			Description -> "The date and time the calibration report was generated.",
			Category -> "General"
			},
		InstrumentInformation -> {
			Format -> Single,
			Class -> {String, String, String, String, String, String, String},
			Pattern :> {_String, _String, _String, _String, _String, _String, _String},
			Headers -> {"Name", "Instrument Type", "Serial Number", "Instrument Firmware Version", "Heated Cover Serial Number", "Heated Cover Firmware Version", "Heated Cover Type"},
			Description -> "The instrument's hardware and firmware information as recorded in the calibration report.",
			Category -> "Instrument Parameters"
		},
		HeatingBlockInformation -> {
			Format -> Single,
			Class -> {Link, String, String, String},
			Pattern :> {_Link, _String, _String, _String},
			Relation -> {Object[Part], Null, Null, Null},
			Headers -> {"Heating Block", "Block Type", "Block Serial Number", "Block Firmware Version"},
			Description -> "The heating block used during the calibration and its type, serial number and firmware version as recorded in the calibration report.",
			Category -> "Instrument Parameters"
		},
		InstrumentComputerSoftwareInformation -> {
			Format -> Single,
			Class -> {Link, String, String},
			Pattern :> {_Link, _String, _String},
			Relation -> {Object[Part, Computer], Null, Null},
			Headers -> {"Instrument Computer", "Software Product Name", "Operating System"},
			Description -> "The instrument's current computer and the software's name, version, and operating system as recorded in the calibration report.",
			Category -> "Instrument Parameters"
		},
		CalibrationPlate -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Container, Plate][CalibrationReports],
			Description -> "The plate used to calibrate the thermocycler for this report.",
			Category -> "General",
			Abstract -> True
		}
	}
}]