(* Mathematica Source File *)
(* Created by the Wolfram Language Plugin for IntelliJ, see http://wlplugin.halirutan.de/ *)
(* :Author: XuYi *)
(* :Date: 2025-09-06 *)

DefineObjectType[Object[Method, pHCalibration], {
  Description->"A method containing parameters specifying a calibration buffer set utilized by a seven excellence pH meter.",
  CreatePrivileges->None,
  Cache->Session,
  Fields -> {
    MethodFile -> {
      Format -> Single,
      Class -> Link,
      Pattern :> _Link,
      Relation -> Object[EmeraldCloudFile],
      Description -> "The file containing the raw method file generated by the instrument.",
      Category -> "General"
    },
    BufferFile -> {
      Format -> Single,
      Class -> Link,
      Pattern :> _Link,
      Relation -> Object[EmeraldCloudFile],
      Description -> "The file containing the raw buffer set file generated by the instrument.",
      Category -> "General"
    },
    CalibrationBufferSetName -> {
      Format -> Single,
      Class -> String,
      Pattern :> _String,
      Description -> "The name of the calibration buffer set to use on the seven excellence pH meter.",
      Category -> "General"
    },
    CalibrationMethodName -> {
      Format -> Single,
      Class -> String,
      Pattern :> _String,
      Description -> "The name of the calibration method to use on the seven excellence pH meter.",
      Category -> "General"
    },
    LowCalibrationBufferpH -> {
      Format -> Single,
      Class -> Real,
      Pattern :> RangeP[0,14],
      Description -> "The pH of the low calibration buffer that should be used to calibrate the pH probe.",
      Category -> "General"
    },
    MediumCalibrationBufferpH -> {
      Format -> Single,
      Class -> Real,
      Pattern :> RangeP[0,14],
      Description -> "The pH of the medium calibration buffer that should be used to calibrate the pH probe.",
      Category -> "General"
    },
    HighCalibrationBufferpH -> {
      Format -> Single,
      Class -> Real,
      Pattern :> RangeP[0,14],
      Description -> "The pH of the high calibration buffer that should be used to calibrate the pH probe.",
      Category -> "General"
    }
  }
}];