(* ::Text:: *)
(*\[Copyright] 2011-2025 Emerald Cloud Lab, Inc.*)

(* ::Package:: *)

DefineObjectType[Object[Method, Dissolution], {
	Description -> "A set of parameters for dissolving a solid sample in a dissolution medium.",
	CreatePrivileges -> None,
	Cache -> Session,
	Fields -> {
		MixingStrategy -> {
			Format -> Single,
			Class -> Expression,
			Pattern :> DissolutionStrategyP,
			Description -> "The strategy used to mix the solid sample in the dissolution medium.",
			Category -> "Instrument Parameters"
		},
		MediaTemperature->{
			Format->Single,
			Class->Real,
			Units->Celsius,
			Pattern:>GreaterEqualP[0 Kelvin],
			Description->"The nominal temperature of the media the instrument seeks to maintain for each vessel by using the heating jacket around the dissolution vessel. The recording of the temperature of the media during the experiment can be found in the Temperature field in the Data objects generated by the protocol.",
			Category->"Instrument Parameters"
		},
		MediaVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the medium used to dissolve the oral solid dosage.",
			Category->"Instrument Parameters"
		},
		MixRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * RPM],
			Units->RPM,
			Description->"The frequency at which the shaft is rotated during the experiment.",
			Category->"Instrument Parameters"
		},
		MixTime->{
			Format->Single,
			Class->Real,
			Units->Minute,
			Pattern:>GreaterEqualP[0 Minute],
			Description->"The duration of time the oral solid dosage is mixed during which the sampling occurs at the specified SamplingTime intervals. After the intial mixing period is completed, the optional InfinityMixing is performed at a higher rotation rate to achieve the final saturation point.",
			Category->"Instrument Parameters"
		},
		DissolutionVessels->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"The number of vessels used to dissolve the oral solid dosage.",
			Category->"Instrument Parameters"
		},
		InfinityMixRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * RPM],
			Units->RPM,
			Description->"The frequency of rotation used by the dissolution instrument at the end of the experiment to achieve final dissolution condition. This is typically set to a higher value than the MixRate to achieve the final saturation point.",
			Category->"Instrument Parameters"
		},
		InfinityMixTime->{
			Format->Single,
			Class->Real,
			Units->Minute,
			Pattern:>GreaterEqualP[0 Minute],
			Description->"The duration of time for which the oral solid dosage will be mixed at InfinityMixRate after MixTime to achieve the final saturation point.",
			Category->"Instrument Parameters"
		},
		SamplingTimes->{
			Format->Multiple,
			Class->Real,
			Units->Minute,
			Pattern:>GreaterEqualP[0 Minute],
			Description->"The list of the time points at which aliquots of the dissolution medium are taken.",
			Category->"Sampling"
		},
		SamplingVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterEqualP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the aliquot taken from the dissolution media at each SamplingTimes time point.",
			Category->"Sampling"
		},
		CollectionFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed at which the medium is aspirated during the experiment.",
			Category->"Pump Settings"
		},
		DispenseFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed at which the medium is dispensed during the experiment.",
			Category->"Pump Settings"
		},
		VesselReturnFlowRate->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milli * Liter / Second],
			Units->Milli * Liter / Second,
			Description->"The speed at which the medium is returned to the dissolution vessel.",
			Category->"Pump Settings"
		},
		SamplingFlushVolume->{
			Format->Single,
			Class->Real,
			Pattern:>GreaterP[0 * Milliliter],
			Units->Milliliter,
			Description->"The volume of the medium from the dissolution vessel used to flush the sampling lines at each sampling time point.",
			Category->"Pump Settings"
		},
		MediaReplace->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the media is replaced with a new medium after each aliquot is taken to maintain the constant volume of the media in the vessel.",
			Category->"Pump Settings"
		},
		RecycleSamplingMedium->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the buffer removed for sample flushing is returned from the lines back to the dissolution vessel. Refer to the instrument diagram of the liquid flow path during the instrument operation for more details.",
			Category->"Pump Settings"
		},
		NumberOfFilterUses->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"The number of times the AutosamplerFilter is used before being replaced with a new one. Null indicates that the filter is not used.",
			Category->"Pump Settings"
		},
		NumberOfSamplingWashCycles->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterP[0,1],
			Description->"Indicates the number of times the system wash cycle is performed between each sampling timepoint.",
			Category->"Pump Settings"
		},
		NumberOfSamplingFlushes->{
			Format->Single,
			Class->Integer,
			Pattern:>GreaterEqualP[1,1],
			Description->"The number of times the system wash cycle is performed between each sampling timepoint.",
			Category->"Pump Settings"
		},
		MethodFile->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[EmeraldCloudFile],
			Description->"The method file containing the run parameters for all samples in protocol.",
			Category->"General"
		}
	}
}];