(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Qualification,CapillaryELISA],{
	Description->"A protocol that verifies the functionality of the capillary-based ELISA instrument target.",
	CreatePrivileges->None,
	Cache->Session,
	Fields->{
		TestCartridge -> {
			Format -> Single,
			Class -> Link,
			Pattern :> ObjectP[Object[Part,CapillaryELISATestCartridge]],
			Relation -> Object[Part,CapillaryELISATestCartridge],
			Description -> "The verification cartridges that is used in this capillary ELISA instrument qualification to perform a series of diagnostic tests to ensure the instrument is running properly.",
			Category -> "General"
		},
		VerificationDataFilePath -> {
			Format -> Single,
			Class -> String,
			Pattern :> FilePathP,
			Description -> "The file path of the folder containing the verfication data file generated by the TestCartridge at the conclusion of the experiment.",
			Category -> "General",
			Developer -> True
		},
		VerificationDataFileName -> {
			Format -> Single,
			Class -> String,
			Pattern :> _String,
			Description -> "The file path of the data file generated by the TestCartridge at the conclusion of the experiment.",
			Category -> "General",
			Developer -> True
		},
		VerificationDataFile -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[EmeraldCloudFile],
			Description -> "The CSV file containing the verification report summary generated by the TestCartridge at the conclusion of the experiment.",
			Category -> "Experimental Results"
		}

	}
}];