(* ::Package:: *)

(* ::Text:: *)
(*© 2011-2023 Emerald Cloud Lab, Inc.*)
(*:Author: hanming.yang*)
(* :Date: 2023-6-16 *)

DefineObjectType[Object[Qualification, Training, Weighing], {
	Description->"The qualification test to verify the user's ability to weigh samples properly.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {
		(* micro balance *)
		MicrobalanceInstrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The instrument that was used to test the user's ability to tare and measure small masses (less than 1 gram) using a microbalance.",
			Category -> "Weighing Skills"
		},
		MicrobalanceSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the target instrument.",
			Category -> "General"
		},
		MicrobalanceSampleWeights -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Milligram],
			Units -> Milligram,
			Description -> "The weights of the objects or samples used to qualify the user's ability to use a microbalance.",
			Category -> "General"
		},
		MicrobalanceWeightHandles -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item, WeightHandle],
				Model[Item, Tweezer],
				Model[Item, Spatula],
				Object[Item, WeightHandle],
				Object[Item, Tweezer],
				Object[Item, Spatula]
			],
			IndexMatching -> MicrobalanceSamples,
			Description -> "For each member of MicrobalanceSamples, the weight tweezers/forks/handles used to pick up and move the weight to/from the balance.",
			Category -> "General"
		},
		MicrobalanceTransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "Containers which solid will be transferred into when weighing.",
			Category -> "General"
		},
		MicrobalanceData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Microbalance data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MicrobalanceTareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The weight data recorded after the Microbalance was zeroed.",
			Category -> "Experimental Results"
		},
		(* analytical balance *)
		BalanceInstrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The instrument that was used to test the user's ability to tare and measure typical masses (0.1-200 gram) using an analytical balance.",
			Category -> "Weighing Skills"
		},
		BalanceSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the target instrument.",
			Category -> "General"
		},
		BalanceSampleWeights -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Milligram],
			Units -> Milligram,
			Description -> "The weights of the objects or samples used to qualify the user's ability to use a balance.",
			Category -> "General"
		},
		BalanceWeightHandles -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item, WeightHandle],
				Model[Item, Tweezer],
				Model[Item, Spatula],
				Object[Item, WeightHandle],
				Object[Item, Tweezer],
				Object[Item, Spatula]
			],
			IndexMatching -> BalanceSamples,
			Description -> "For each member of BalanceSamples, the weight tweezers/forks/handles used to pick up and move the weight to/from the balance.",
			Category -> "General"
		},
		BalanceTransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "Containers which solid will be transferred into when weighing.",
			Category -> "General"
		},
		BalanceData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Balance data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		BalanceTareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The weight data recorded after the Balance was zeroed.",
			Category -> "Experimental Results"
		},
		(* macro balance *)
		ToploadingBalanceInstrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The instrument that was used to test the user's ability to tare and measure large masses (up to 6 kilograms) using a toploading balance.",
			Category -> "Weighing Skills"
		},
		ToploadingBalanceSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the target instrument.",
			Category -> "General"
		},
		ToploadingBalanceSampleWeights -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Gram],
			Units -> Gram,
			Description -> "The weights of the objects or samples used to qualify the user's ability to use a top loading balance.",
			Category -> "General"
		},
		ToploadingBalanceWeightHandles -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item, WeightHandle],
				Model[Item, Tweezer],
				Model[Item, Spatula],
				Object[Item, WeightHandle],
				Object[Item, Tweezer],
				Object[Item, Spatula]
			],
			IndexMatching -> ToploadingBalanceSamples,
			Description -> "For each member of ToploadingBalanceSamples, the weight tweezers/forks/handles used to pick up and move the weight to/from the balance.",
			Category -> "General"
		},
		ToploadingBalanceTransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "Containers which solid will be transferred into when weighing.",
			Category -> "General"
		},
		ToploadingBalanceData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The ToploadingBalance data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		ToploadingBalanceTareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The weight data recorded after the ToploadingBalance was zeroed.",
			Category -> "Experimental Results"
		},
		ContainersToCleanUp -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Container],
			Description -> "The list of containers from weighing module that needs to be cleaned up before storage.",
			Category -> "Storage & Handling"
		},
		ContainersToStore -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Object[Item]
			],
			Description -> "The list of containers from weighing module that should be stored directly.",
			Category -> "Storage & Handling"
		}
	}
}
]