(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Qualification, Training, Scissors], {
	Description -> "A protocol that verifies an operator's ability to work with scissors to cut samples into a requested weight.",
	CreatePrivileges -> None,
	Cache -> Session,
	Fields -> {
		SampleResources -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Object[Sample],
				Model[Item],
				Object[Item]
			],
			Description -> "For each member of WorkingSamples, The samples that are resource picked to be used in this qualification.",
			IndexMatching -> WorkingSamples,
			Category -> "General"
		},
		WorkingSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Sample],
			Description -> "For each member of SourceContainers, the individual samples that will be directly cut by scissors during the qualification.",
			Category -> "General"
		},
		SourceContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Container]|Model[Container],
			Description -> "For each member of WorkingSamples, indicate the containers to hold each individual WorkingSamples.",
			IndexMatching -> WorkingSamples,
			Category -> "General"
		},
		DestinationContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Container]|Model[Container],
			Description -> "For each member of WorkingSamples, indicate the transfer destination of WorkingSamples after cut by scissors.",
			IndexMatching -> WorkingSamples,
			Category -> "General"
		},
		TransferAmounts -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> MassP,
			Units -> Milligram,
			Description -> "For each member of WorkingSamples, indicate the amount that should be transferred.",
			IndexMatching -> WorkingSamples,
			Category -> "General"
		},
		MeasuredTransferWeights -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> MassP,
			Units -> Milligram,
			Description -> "For each member of WorkingSamples, indicate the amount that was actually transferred.",
			IndexMatching -> WorkingSamples,
			Category -> "Experimental Results"
		},
		SamplePreparationProtocols -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Protocol, ManualSamplePreparation],
			Description -> "The ManualSP protocol generated by this qualification.",
			Category -> "Sample Handling"
		},
		SamplePreparationUnitOperations -> {
			Format -> Multiple,
			Class -> Expression,
			Pattern :> SamplePreparationP,
			Description -> "The ManualSamplePreparation Unit Operations for the transfer with scissors.",
			Category -> "Sample Handling"
		}
	}
}]