(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Qualification, Training, Pipetting], {
	Description->"A qualification test to verify the user's ability to use pipettes properly.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {
		PipetteBuffer -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Object[Sample]
			],
			Description -> "The model or sample describing the liquid that will be used in this Qualification to test the linearity of the pipettors.",
			Category -> "General"
		},
		(* p1000 *)
		MicropipetteP1000Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Pipette],Model[Instrument,Pipette]],
			Description -> "The Eppendorf P1000 instrument used to test the user's ability to pipette volumes of a test sample with a micropipette.",
			Category -> "Pipetting Skills"
		},
		MicropipetteP1000InstrumentBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to pipette volumes of a test sample, with the Eppendorf P1000 pipette.",
			Category -> "Pipetting Skills"
		},
		MicropipetteP1000PipetteParameters -> {
			Format->Multiple,
			Class->{
				Container->Link,
				Volume->Real
			},
			Pattern:>{
				Container->_Link,
				Volume->VolumeP
			},
			Relation->{
				Container->Object[Container]|Object[Item],
				Volume->Null
			},
			Units->{
				Container->None,
				Volume->Microliter
			},
			Description->"Specifies how samples should be pipetted with the Eppendorf P1000 pipette.",
			Category -> "General"
		},
		MicropipetteP1000TransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "The containers that buffer will be pipetted into with the Eppendorf P1000 pipette.",
			Category -> "General"
		},
		MicropipetteP1000Tips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item],
				Object[Item]
			],
			Description -> "The model of the pipette tips used for this pipette in this qualification with the Eppendorf P1000 pipette.",
			Category -> "General"
		},
		MicropipetteP1000BufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Micro*Liter)],
			Units -> Microliter,
			Description -> "The volumes that will be pipetted into each container for this Qualification using the Eppendorf P1000 pipette.",
			Category -> "General"
		},
		MicropipetteP1000QualificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the Eppendorf P1000 pipette.",
			Category -> "General"
		},
		MicropipetteP1000Data -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf P1000 pipette data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MicropipetteP1000TareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf P1000 pipette tare data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MicropipetteP1000PracticeRuns -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterEqualP[0,1],
			Description -> "Indicates that the first n values of MicropipetteP1000BufferVolumes will not be assessed.",
			Category -> "General"
		},
		MicropipetteP1000Grade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria.",
			Category -> "General"
		},
		(* p5000 *)
		MicropipetteP5000Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Pipette],Model[Instrument,Pipette]],
			Description -> "The Eppendorf P5000 instrument used to test the user's ability to pipette volumes of a test sample with a micropipette.",
			Category -> "Pipetting Skills"
		},
		MicropipetteP5000InstrumentBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to pipette volumes of a test sample, with the Eppendorf P5000 pipette.",
			Category -> "Pipetting Skills"
		},
		MicropipetteP5000PipetteParameters -> {
			Format->Multiple,
			Class->{
				Container->Link,
				Volume->Real
			},
			Pattern:>{
				Container->_Link,
				Volume->VolumeP
			},
			Relation->{
				Container->Object[Container]|Object[Item],
				Volume->Null
			},
			Units->{
				Container->None,
				Volume->Microliter
			},
			Description->"Specifies how samples should be pipetted in this qualification with the Eppendorf P5000 pipette.",
			Category -> "General"
		},
		MicropipetteP5000TransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "The containers that buffer will be pipetted into with the Eppendorf P5000 pipette.",
			Category -> "General"
		},
		MicropipetteP5000Tips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item],
				Object[Item]
			],
			Description -> "The model of the pipette tips used for this pipette in this qualification with the Eppendorf P5000 pipette.",
			Category -> "General"
		},
		MicropipetteP5000BufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Micro*Liter)],
			Units -> Microliter,
			Description -> "The volumes that will be pipetted into each container for this Qualification using the Eppendorf P5000 pipette.",
			Category -> "General"
		},
		MicropipetteP5000QualificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the Eppendorf P5000 pipette.",
			Category -> "General"
		},
		MicropipetteP5000Data -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf P5000 pipette data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MicropipetteP5000TareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf P5000 pipette Tare data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MicropipetteP5000PracticeRuns -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterEqualP[0,1],
			Description -> "Indicates that the first n values of MicropipetteP5000BufferVolumes will not be assessed.",
			Category -> "General"
		},
		MicropipetteP5000Grade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria.",
			Category -> "General"
		},
		(* P20 *)
		MicropipetteP20Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Pipette],Model[Instrument,Pipette]],
			Description -> "The Eppendorf P20 instrument used to test the user's ability to pipette volumes of a test sample with a micropipette.",
			Category -> "Pipetting Skills"
		},
		MicropipetteP20InstrumentBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to pipette volumes of a test sample, with the Eppendorf P20 pipette.",
			Category -> "Pipetting Skills"
		},
		MicropipetteP20PipetteParameters -> {
			Format->Multiple,
			Class->{
				Container->Link,
				Volume->Real
			},
			Pattern:>{
				Container->_Link,
				Volume->VolumeP
			},
			Relation->{
				Container->Object[Container]|Object[Item],
				Volume->Null
			},
			Units->{
				Container->None,
				Volume->Microliter
			},
			Description->"Specifies how samples should be pipetted in this qualification with the Eppendorf P20 pipette.",
			Category -> "General"
		},
		MicropipetteP20TransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "The containers that buffer will be pipetted into with the Eppendorf P20 pipette.",
			Category -> "General"
		},
		MicropipetteP20Tips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item],
				Object[Item]
			],
			Description -> "The model of the pipette tips used for this pipette in this qualification with the Eppendorf P20 pipette.",
			Category -> "General"
		},
		MicropipetteP20BufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Micro*Liter)],
			Units -> Microliter,
			Description -> "The volumes that will be pipetted into each container for this Qualification with the Eppendorf P20 pipette.",
			Category -> "General"
		},
		MicropipetteP20QualificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the Eppendorf P20 pipette.",
			Category -> "General"
		},
		MicropipetteP20Data -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf P20 pipette data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MicropipetteP20TareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf P20 pipette Tare data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MicropipetteP20PracticeRuns -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterEqualP[0,1],
			Description -> "Indicates that the first n values of MicropipetteP20BufferVolumes will not be assessed.",
			Category -> "General"
		},
		MicropipetteP20Grade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria.",
			Category -> "General"
		},
		(* P2.5 *)
		MicropipetteP2P5Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Pipette],Model[Instrument,Pipette]],
			Description -> "The Eppendorf P2.5 instrument used to test the user's ability to pipette volumes of a test sample with a micropipette.",
			Category -> "Pipetting Skills"
		},
		MicropipetteP2P5InstrumentBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to pipette volumes of a test sample, with the Eppendorf P2.5 pipette.",
			Category -> "Pipetting Skills"
		},
		MicropipetteP2P5PipetteParameters -> {
			Format->Multiple,
			Class->{
				Container->Link,
				Volume->Real
			},
			Pattern:>{
				Container->_Link,
				Volume->VolumeP
			},
			Relation->{
				Container->Object[Container]|Object[Item],
				Volume->Null
			},
			Units->{
				Container->None,
				Volume->Microliter
			},
			Description->"Specifies how samples should be pipetted in this qualification with the Eppendorf P2.5 pipette.",
			Category -> "General"
		},
		MicropipetteP2P5TransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "The containers that buffer will be pipetted into with the Eppendorf P2.5 pipette.",
			Category -> "General"
		},
		MicropipetteP2P5Tips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item],
				Object[Item]
			],
			Description -> "The model of the pipette tips used for this pipette in this qualification with the Eppendorf P2.5 pipette.",
			Category -> "General"
		},
		MicropipetteP2P5BufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Micro*Liter)],
			Units -> Microliter,
			Description -> "The volumes that will be pipetted into each container for this Qualification using the specified Eppendorf P2.5 pipette.",
			Category -> "General"
		},
		MicropipetteP2P5QualificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the Eppendorf P2.5 pipette.",
			Category -> "General"
		},
		MicropipetteP2P5Data -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf P2.5 pipette data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MicropipetteP2P5TareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf P2.5 pipette Tare data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MicropipetteP2P5PracticeRuns -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterEqualP[0,1],
			Description -> "Indicates that the first n values of MicropipetteP2P5BufferVolumes will not be assessed.",
			Category -> "General"
		},
		MicropipetteP2P5Grade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria.",
			Category -> "General"
		},
		(* Serological pipette *)
		SerologicalPipettePipetusInstrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Pipette],Model[Instrument,Pipette]],
			Description -> "The pipetus serological pipette instrument used to test the user's ability to pipette volumes of a test sample.",
			Category -> "Pipetting Skills"
		},
		SerologicalPipettePipetusInstrumentBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to pipette volumes of a test sample, with the pipetus serological pipette.",
			Category -> "Pipetting Skills"
		},
		SerologicalPipettePipetusPipetteParameters -> {
			Format->Multiple,
			Class->{
				Container->Link,
				Volume->Real
			},
			Pattern:>{
				Container->_Link,
				Volume->VolumeP
			},
			Relation->{
				Container->Object[Container]|Object[Item],
				Volume->Null
			},
			Units->{
				Container->None,
				Volume->Microliter
			},
			Description->"Specifies how samples should be pipetted in this qualification with the pipetus serological pipette.",
			Category -> "General"
		},
		SerologicalPipettePipetusTransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "The containers that buffer will be pipetted into with the pipetus serological pipette.",
			Category -> "General"
		},
		SerologicalPipettePipetusTips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item],
				Object[Item]
			],
			Description -> "The model of the pipette tips used for this pipette in this qualification with the pipetus serological pipette.",
			Category -> "General"
		},
		SerologicalPipettePipetusBufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Micro*Liter)],
			Units -> Microliter,
			Description -> "The volumes that will be pipetted into each container for this Qualification using the pipetus serological pipette.",
			Category -> "General"
		},
		SerologicalPipettePipetusQualificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the pipetus serological pipette.",
			Category -> "General"
		},
		SerologicalPipettePipetusData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The pipetus serological pipette data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		SerologicalPipettePipetusTareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The pipetus serological pipette Tare data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		SerologicalPipettePipetusPracticeRuns -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterEqualP[0,1],
			Description -> "Indicates that the first n values of SerologicalPipettePipetusBufferVolumes will not be assessed.",
			Category -> "General"
		},
		SerologicalPipettePipetusGrade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria.",
			Category -> "General"
		},
		(* Positive displacement pipette *)
		PositiveDisplacementPipettePosDMR100Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Pipette],Model[Instrument,Pipette]],
			Description -> "The Pos-D MR-100 positive displacement pipette instrument used to test the user's ability to pipette volumes of a test sample.",
			Category -> "Pipetting Skills"
		},
		PositiveDisplacementPipettePosDMR100InstrumentBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to pipette volumes of a test sample, with the Pos-D MR-100 positive displacement pipette.",
			Category -> "Pipetting Skills"
		},
		PositiveDisplacementPipettePosDMR100PipetteParameters -> {
			Format->Multiple,
			Class->{
				Container->Link,
				Volume->Real
			},
			Pattern:>{
				Container->_Link,
				Volume->VolumeP
			},
			Relation->{
				Container->Object[Container]|Object[Item],
				Volume->Null
			},
			Units->{
				Container->None,
				Volume->Microliter
			},
			Description->"Specifies how samples should be pipetted in this qualification with the Pos-D MR-100 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR100TransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "The containers that buffer will be pipetted into with the Pos-D MR-100 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR100Tips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item],
				Object[Item]
			],
			Description -> "The model of the pipette tips used for this pipette in this qualification with the Pos-D MR-100 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR100BufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Micro*Liter)],
			Units -> Microliter,
			Description -> "The volumes that will be pipetted into each container for this Qualification using the specified Pos-D MR-100 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR100QualificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the Pos-D MR-100 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR100Data -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Pos-D MR-100 positive displacement pipette data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		PositiveDisplacementPipettePosDMR100TareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Pos-D MR-100 positive displacement pipette Tare data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		PositiveDisplacementPipettePosDMR100PracticeRuns -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterEqualP[0,1],
			Description -> "Indicates that the first n values of PositiveDisplacementPipettePosDMR100BufferVolumes will not be assessed.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR100Grade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria.",
			Category -> "General"
		},
		(* Pos-D 10 *)
		PositiveDisplacementPipettePosDMR10Instrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Pipette],Model[Instrument,Pipette]],
			Description -> "The Pos-D MR-10 positive displacement pipette instrument used to test the user's ability to pipette volumes of a test sample.",
			Category -> "Pipetting Skills"
		},
		PositiveDisplacementPipettePosDMR10InstrumentBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to pipette volumes of a test sample, with the Pos-D MR-10 positive displacement pipette.",
			Category -> "Pipetting Skills"
		},
		PositiveDisplacementPipettePosDMR10PipetteParameters -> {
			Format->Multiple,
			Class->{
				Container->Link,
				Volume->Real
			},
			Pattern:>{
				Container->_Link,
				Volume->VolumeP
			},
			Relation->{
				Container->Object[Container]|Object[Item],
				Volume->Null
			},
			Units->{
				Container->None,
				Volume->Microliter
			},
			Description->"Specifies how samples should be pipetted in this qualification with the Pos-D MR-10 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR10TransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "The containers that buffer will be pipetted into with the Pos-D MR-10 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR10Tips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item],
				Object[Item]
			],
			Description -> "The model of the pipette tips used for this pipette in this qualification with the Pos-D MR-10 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR10BufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Micro*Liter)],
			Units -> Microliter,
			Description -> "The volumes that will be pipetted into each container for this Qualification using the specified Pos-D MR-10 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR10QualificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the Pos-D MR-10 positive displacement pipette.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR10Data -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Pos-D MR-10 positive displacement pipette data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		PositiveDisplacementPipettePosDMR10TareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Pos-D MR-10 positive displacement pipette Tare data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		PositiveDisplacementPipettePosDMR10PracticeRuns -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterEqualP[0,1],
			Description -> "Indicates that the first n values of PositiveDisplacementPipettePosDMR10BufferVolumes will not be assessed.",
			Category -> "General"
		},
		PositiveDisplacementPipettePosDMR10Grade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria.",
			Category -> "General"
		},
		(* Multichannels *)
		(* 8-channel 300 uL *)
		MultichannelPipette8Channel300uLInstrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Pipette],Model[Instrument,Pipette]],
			Description -> "The Eppendorf 8-channel 300 uL instrument used to test the user's ability to pipette volumes of a test sample with a multichannel pipette.",
			Category -> "Pipetting Skills"
		},
		MultichannelPipette8Channel300uLInstrumentBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to pipette volumes of a test sample, with the Eppendorf 8-channel 300 uL pipette.",
			Category -> "Pipetting Skills"
		},
		MultichannelPipette8Channel300uLPipetteParameters -> {
			Format->Multiple,
			Class->{
				Container->Link,
				Volume->Real
			},
			Pattern:>{
				Container->_Link,
				Volume->VolumeP
			},
			Relation->{
				Container->Object[Container]|Object[Item],
				Volume->Null
			},
			Units->{
				Container->None,
				Volume->Microliter
			},
			Description->"Specifies how samples should be pipetted in this qualification with the Eppendorf 8-channel 300 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel300uLTransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "The containers that buffer will be pipetted into with the Eppendorf 8-channel 300 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel300uLTips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item],
				Object[Item]
			],
			Description -> "The model of the pipette tips used for this pipette in this qualification with the Eppendorf 8-channel 300 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel300uLBufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Micro*Liter)],
			Units -> Microliter,
			Description -> "The volumes that will be pipetted into each container for this Qualification using the specified Eppendorf 8-channel 300 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel300uLQualificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the Eppendorf 8-channel 300 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel300uLData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf 8-channel 300 uL pipette data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MultichannelPipette8Channel300uLTareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf 8-channel 300 uL pipette Tare data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MultichannelPipette8Channel300uLPracticeRuns -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterEqualP[0,1],
			Description -> "Indicates that the first n values of MultichannelPipette8Channel300uLBufferVolumes will not be assessed.",
			Category -> "General"
		},
		MultichannelPipette8Channel300uLGrade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria.",
			Category -> "General"
		},
		(* 8-channel 10 uL *)
		MultichannelPipette8Channel10uLInstrument -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Pipette],Model[Instrument,Pipette]],
			Description -> "The Eppendorf 8-channel 10 uL instrument used to test the user's ability to pipette volumes of a test sample with a multichannel pipette.",
			Category -> "Pipetting Skills"
		},
		MultichannelPipette8Channel10uLInstrumentBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to pipette volumes of a test sample, with the Eppendorf 8-channel 10 uL pipette.",
			Category -> "Pipetting Skills"
		},
		MultichannelPipette8Channel10uLPipetteParameters -> {
			Format->Multiple,
			Class->{
				Container->Link,
				Volume->Real
			},
			Pattern:>{
				Container->_Link,
				Volume->VolumeP
			},
			Relation->{
				Container->Object[Container]|Object[Item],
				Volume->Null
			},
			Units->{
				Container->None,
				Volume->Microliter
			},
			Description->"Specifies how samples should be pipetted in this qualification with the Eppendorf 8-channel 10 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel10uLTransferContainers -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Object[Container],
				Model[Container],
				Object[Item],
				Model[Item]
			],
			Description -> "The containers that buffer will be pipetted into with the Eppendorf 8-channel 10 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel10uLTips -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Item],
				Object[Item]
			],
			Description -> "The model of the pipette tips used for this pipette in this qualification with the Eppendorf 8-channel 10 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel10uLBufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Micro*Liter)],
			Units -> Microliter,
			Description -> "The volumes that will be pipetted into each container for this Qualification using the specified Eppendorf 8-channel 10 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel10uLQualificationSamples -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Sample],
				Model[Item],
				Object[Sample],
				Object[Item]
			],
			Description -> "Samples or Items with known expected results that are run on the Eppendorf 8-channel 10 uL pipette.",
			Category -> "General"
		},
		MultichannelPipette8Channel10uLData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf 8-channel 10 uL pipette data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MultichannelPipette8Channel10uLTareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Eppendorf 8-channel 10 uL pipette Tare data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		MultichannelPipette8Channel10uLPracticeRuns -> {
			Format -> Single,
			Class -> Integer,
			Pattern :> GreaterEqualP[0,1],
			Description -> "Indicates that the first n values of MultichannelPipette8Channel10uLBufferVolumes will not be assessed.",
			Category -> "General"
		},
		MultichannelPipette8Channel10uLGrade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria.",
			Category -> "General"
		}
	}
}]