(* ::Package:: *)

(* ::Text:: *)
(*\[Copyright] 2011-2023 Emerald Cloud Lab, Inc.*)

DefineObjectType[Object[Qualification,Ventilation],{
	Description->"A protocol that verifies the functionality of the ventilation system target.",
	CreatePrivileges->None,
	Cache->Download,
	Fields->{
		Anemometer->{
			Format->Single,
			Class->Link,
			Pattern:>_Link,
			Relation->Alternatives[
				Model[Instrument,Anemometer],
				Object[Instrument,Anemometer]
			],
			Description->"The instrument used to measure air velocity.",
			Category -> "General"
		},
		QualifiedParts->{
			Format->Multiple,
			Class->Link,
			Pattern:>_Link,
			Relation->Object[Part,Fan],
			Description->"The ventilation parts qualified in this protocol.",
			Category -> "General"
		},
		InstrumentOn->{
			Format->Single,
			Class->Boolean,
			Pattern:>BooleanP,
			Description->"Indicates if the operator identified the instrument is On or could be turned on before measuring airflow.",
			Category->"Experimental Results"
		},
		VentilationAirVelocity->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterEqualP[0*(Meter/Second)],
			Units->(Meter/Second),
			Description->"For each member of QualifiedParts, specifies the measured velocity of air generated by the instrument's ventilator.",
			Category->"Experimental Results",
			IndexMatching->QualifiedParts
		},
		VentilationAirTemperature->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterEqualP[0*Kelvin],
			Units->Celsius,
			Description->"For each member of QualifiedParts, specifies the measured temperature of air generated by the instrument's ventilator.",
			Category->"Experimental Results",
			IndexMatching->QualifiedParts
		},
		VentilationFlowRateRequirements->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterP[0*(Meter/Second)],
			Units->(Meter/Second),
			Description->"For each member of QualifiedParts, specifies the minimum flow rate of air generated by the instrument's ventilator for its safe and proper function.",
			Category->"Acceptance Criteria",
			IndexMatching->QualifiedParts
		},
		VentilationFlowRateRecommendations->{
			Format->Multiple,
			Class->Real,
			Pattern:>GreaterP[0*(Meter/Second)],
			Units->(Meter/Second),
			Description->"For each member of QualifiedParts, specifies the flow rate of air generated by the instrument's ventilator recommended by its manufacturer.",
			Category->"Acceptance Criteria",
			IndexMatching->QualifiedParts
		}
	}
}];
