(* Mathematica Source File *)
(* Created by the Wolfram Language Plugin for IntelliJ, see http://wlplugin.halirutan.de/ *)
(* :Author: adam.abushaer *)
(* :Date: 2023-02-14 *)

DefineObjectType[Object[Qualification,Training,Receiving], {
  Description -> "A qualification to test user's ability to receive an item that has arrived at ECL.",
  CreatePrivileges -> None,
  Cache -> Session,
  Fields -> {
    QualificationTransaction -> {
      Format -> Single,
      Class -> Link,
      Pattern :> _Link,
      Relation -> Object[Transaction, Order],
      Description -> "The transaction generated by the qualification for the operator to complete.",
      Category -> "General"
    },
    QualificationReceiveInventory -> {
      Format -> Single,
      Class -> Link,
      Pattern :> _Link,
      Relation -> Object[Maintenance, ReceiveInventory],
      Description -> "The ReceiveInventory subprotocol generated by the qualification that the operator enters and completes.",
      Category -> "General"
    },
    ReceivingItem ->{
      Format -> Single,
      Class -> Link,
      Pattern :> _Link,
      Relation -> Alternatives[
        Model[Item,Tips],Model[Item,Consumable],Model[Item,Cap],Model[Item,Spatula],Model[Item,Filter],Model[Item,Tweezer],Model[Item,WeighBoat],Model[Container,Vessel],
        Object[Item,Tips],Object[Item,Consumable],Object[Item,Cap],Object[Item,Spatula],Object[Item,Filter],Object[Item,Tweezer],Object[Item,WeighBoat],Object[Container,Vessel]
      ],
      Description -> "The item that an operator receives.",
      Category -> "General"
    }
  }
}]