(* ::Package:: *)

(* ::Text:: *)
(*© 2011-2023 Emerald Cloud Lab, Inc.*)


DefineObjectType[Object[Qualification,Training,GraduatedCylinderTransfer], {
	Description->"A protocol that verifies an operator's ability to use a graduated cylinder.",
	CreatePrivileges->None,
	Cache->Session,
	Fields -> {
		GraduatedCylinders->{
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Model[Container,GraduatedCylinder],Object[Container,GraduatedCylinder]],
			Description -> "The graduated cylinders that will be used to test the user's ability to accurately transfer volumes of a test sample using graduated cylinders.",
			Category -> "Graduated Cylinder Skills"
		},
		GraduatedCylinderReservoirBuffer->{
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Model[Sample],Object[Sample]],
			Description -> "The single reservoir of sample that will be transferred to the transfer container with all of the graduated cylinders.",
			Category -> "Graduated Cylinder Skills"
		},
		GraduatedCylinderBufferVolumes -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0*(Milli*Liter)],
			Units -> Milliliter,
			Description->"Specifies how much sample to transfer with each graduated cylinder.",
			Category -> "Graduated Cylinder Skills"
		},
		HandlingEnvironment -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[
				Model[Instrument, HandlingStation],
				Object[Instrument, HandlingStation]
			],
			Description -> "The environment in which transferring the test sample with various graduated cylinder happens.",
			Category -> "General"
		},
		GraduatedCylindersBalance -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Instrument,Balance],Model[Instrument,Balance]],
			Description -> "The balance that was used to test the user's ability to transfer a test sample, with various graduated cylinders.",
			Category -> "Graduated Cylinder Skills"
		},
		GraduatedCylindersTransferContainer -> {
			Format -> Single,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Alternatives[Object[Container],Model[Container]],
			Description -> "The container that buffer will be transferred into with graduated cylinders.",
			Category -> "Graduated Cylinder Skills"
		},
		GraduatedCylindersTareWeight -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The tared weight of the GraduatedCylindersTransferContainer.",
			Category -> "Experimental Results"
		},
		GraduatedCylindersData -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[Data],
			Description -> "The Graduated cylinder transfer data generated by this Qualification.",
			Category -> "Experimental Results"
		},
		GraduatedCylindersGrade -> {
			Format -> Single,
			Class -> Real,
			Pattern :> RangeP[0 Percent, 100 Percent],
			Units -> Percent,
			Description -> "The percentage of buffer volumes that met the qualification passing criteria for the graduated cylinder module.",
			Category -> "Experimental Results"
		},
		WeightStabilityDurations -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Second],
			Units -> Second,
			Description -> "The duration for which the balance reading needs to stay within a range defined by MaxWeightVariation before being considered stable and captured when measuring the weight of the samples of interest.",
			Category -> "General"
		},
		MaxWeightVariations -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Milligram],
			Units -> Milligram,
			Description -> "The max allowed amplitude the balance readings can fluctuate with for a duration defined by WeightStabilityDuration before being considered stable and captured when measuring the weight of the samples of interest.",
			Category -> "General"
		},
		TareWeightStabilityDurations -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Second],
			Units -> Second,
			Description -> "The duration for which the balance reading needs to stay within a range defined by MaxWeightVariation before being considered stable and captured when measuring the weight of the empty balance and containers.",
			Category -> "General"
		},
		MaxTareWeightVariations -> {
			Format -> Multiple,
			Class -> Real,
			Pattern :> GreaterEqualP[0 Milligram],
			Units -> Milligram,
			Description -> "The max allowed amplitude the balance readings can fluctuate with for a duration defined by WeightStabilityDuration before being considered stable and captured when measuring the weight of the empty balance and containers.",
			Category -> "General"
		},
		GraduatedCylinderImages -> {
			Format -> Multiple,
			Class -> Link,
			Pattern :> _Link,
			Relation -> Object[EmeraldCloudFile],
			Description -> "Images that imitate what the graduated cylinders should look like when filled to the target volumes.",
			Category -> "General",
			Developer -> True
		}
	}
}
]